/* 政读 · lectura por capas para las 24 unidades */
(function(){
  if(!window.ZhengduReading)return;
  state.reading.help??={};
  function renderTokens(text){return ZhengduReading.tokenize(text).map(x=>{if(x.punct)return esc(x.t);if(x.entry)return `<span class="rd-token" title="${esc(x.entry.p||'')} · ${esc(x.entry.m||'')}">${esc(x.t)}</span>`;return `<span class="rd-token unknown">${esc(x.t)}</span>`}).join('')}
  function helpKey(ui){return `u${ui}`}
  openReading=function(ui){const u=D.units[ui],r=u.reading;state.reading.help[helpKey(ui)]??={segments:0,pinyin:0,translation:0};const h=state.reading.help[helpKey(ui)];shell(`U${ui+1} · lectura por capas`,`<section class="read-card"><div class="kicker" style="color:var(--brand)">Paso 1 · leer sin traducir</div><div id="layerText" class="read-cn rd-layer-text">${esc(r.text)}</div><div id="layerPinyin" class="read-pinyin py rd-hidden">${esc(r.pinyin)}</div><div id="layerTranslation" class="translation rd-hidden">${esc(r.translation)}</div><div class="rd-layer-actions"><button id="layerSegment" class="secondary">🧩 Segmentar</button><button id="layerPinyinBtn" class="secondary">拼音 Pinyin</button><button id="layerTranslate" class="secondary">🇪🇸 Traducción</button><button id="layerAudio" class="secondary">🔊</button></div><p class="note">Usá la menor ayuda posible. El objetivo es reconocer sujeto, verbos, objetos y conectores antes de buscar una traducción completa.</p></section><section class="card"><h3>Protocolo de lectura</h3><ol class="rd-protocol"><li>Buscá primero el <b>sujeto institucional</b>.</li><li>Marcá los <b>verbos de acción política</b>.</li><li>Separá sus <b>objetos</b>: 政策、改革、发展、治理…</li><li>Identificá conectores: 通过、并、同时、以及、根据…</li><li>Recién entonces reconstruí el sentido general.</li></ol></section><button id="layerQuestions" class="primary full">Responder comprensión</button>`);
    const text=document.querySelector('#layerText'),py=document.querySelector('#layerPinyin'),tr=document.querySelector('#layerTranslation');
    document.querySelector('#layerSegment').onclick=()=>{text.innerHTML=renderTokens(r.text);h.segments++;save()};
    document.querySelector('#layerPinyinBtn').onclick=()=>{py.classList.toggle('rd-hidden');if(!py.classList.contains('rd-hidden')){h.pinyin++;save()}};
    document.querySelector('#layerTranslate').onclick=()=>{tr.classList.toggle('rd-hidden');if(!tr.classList.contains('rd-hidden')){h.translation++;save()}};
    document.querySelector('#layerAudio').onclick=()=>speak(r.text,.62);
    document.querySelector('#layerQuestions').onclick=()=>{const qs=makeReadingQs(u);runQuestions(qs,{title:`U${ui+1} · comprensión`,source:'reading-layered',onFinish:score=>{markDone(ui,'read',14);const helps=h.segments+h.pinyin+h.translation;modal.innerHTML=`<div class="shell"><div style="font-size:60px;text-align:center">📖</div><h2>${score}/${qs.length}</h2><p>Lectura completada.</p><section class="card"><h3>Traducción de control</h3><p>${esc(r.translation)}</p><p class="note">Ayudas acumuladas en esta lectura: ${helps}. Repetila más adelante intentando usar menos.</p></section><button id="layerDone" class="primary full">Volver a la ruta</button></div>`;document.querySelector('#layerDone').onclick=()=>{closeModal();renderLearn()}}})}
  };
})();