window.MINI_CLASSES=window.MINI_CLASSES||{};
const MC=(lecture,route,compare,exam,reading=[])=>({lecture,route,compare,exam,reading});
Object.assign(MINI_CLASSES,{
 gilgamesh:MC([
  'La Epopeya de Gilgamesh permite comenzar la teoría política antes de la aparición del tratado filosófico. No porque formule una doctrina constitucional, sino porque dramatiza un problema elemental del poder: qué ocurre cuando la fuerza excepcional del rey carece de medida. El Gilgamesh inicial es poderoso, heroico y al mismo tiempo políticamente insoportable para su ciudad; su exceso obliga a imaginar un límite.',
  'Ese límite aparece primero en Enkidu. No es una institución en sentido moderno, pero cumple una función de contrapeso: enfrenta al rey, lo obliga a reconocer un igual y transforma una potencia unilateral en una relación. A partir de allí la epopeya desplaza la pregunta del dominio hacia la amistad, la pérdida y la mortalidad. El gobernante descubre que no puede vencer el límite último de la condición humana.',
  'El regreso final a las murallas de Uruk es por eso políticamente decisivo. La gloria duradera no consiste en hacer inmortal al individuo, sino en producir una ciudad, una memoria y una obra común que sobrevivan al rey. Para un estudiante de teoría política, Gilgamesh sirve para pensar la diferencia entre fuerza y autoridad, entre heroicidad y gobierno, y entre la biografía del soberano y la continuidad de la comunidad.'
 ],['El rey excesivo y la queja de Uruk.','Enkidu como límite y reconocimiento.','Gloria, violencia y expansión heroica.','Muerte, mortalidad y fracaso de la inmortalidad.','Regreso a la ciudad y redefinición de la obra política.'],['Comparar con los espejos de príncipes egipcios: allí el límite aparece como prudencia y justicia, no como duelo heroico.','Comparar con Maquiavelo sólo con cautela: ambos piensan capacidad del gobernante, pero en géneros y universos normativos radicalmente diferentes.'],['Explicar por qué puede leerse políticamente sin convertirla en un tratado.','Distinguir fuerza personal de autoridad política.','Mostrar cómo la mortalidad transforma el sentido de la realeza.'],['Andrew George, The Epic of Gilgamesh.','Mario Liverani, estudios sobre poder y realeza en el antiguo Oriente.']),
 hammurabi:MC([
  'El llamado Código de Hammurabi es una excelente puerta de entrada para estudiar cómo la autoridad política se presenta como justicia. La famosa estela no debe imaginarse como un código moderno exhaustivo que los jueces consultaban artículo por artículo. Es una colección de decisiones y casos insertos entre un prólogo y un epílogo que construyen una imagen pública del rey como garante del orden.',
  'Esto permite observar una tensión central. La colección protege propiedad, regula contratos, fija responsabilidades y limita ciertos abusos, pero lo hace dentro de una sociedad profundamente jerárquica: las consecuencias jurídicas dependen del estatus de las personas. La justicia antigua no equivale a igualdad jurídica moderna. Precisamente por eso es útil: obliga a separar el concepto general de justicia de sus formas históricas concretas.',
  'Políticamente, la estela convierte capacidad judicial en legitimidad. El soberano no dice simplemente “mando porque puedo”, sino “mando para hacer justicia, proteger el orden y evitar que el fuerte oprima sin límite”. El estudiante debe aprender a leer simultáneamente norma, ideología regia y práctica institucional, sin reducir una dimensión a las otras.'
 ],['Prólogo y misión divina del rey.','Casos de propiedad, trabajo, familia y daño.','Diferenciación de sanciones por estatus.','Publicidad monumental y memoria del soberano.','Epílogo y maldiciones contra quien altere la justicia publicada.'],['Comparar con la ley natural de Cicerón: Hammurabi legitima justicia regia dentro de orden cósmico, pero no formula una teoría racional universal del derecho.','Comparar con legalismo chino: ambos valorizan reglas, aunque el marco político y administrativo es distinto.'],['Explicar por qué “código” es una etiqueta problemática.','Mostrar cómo una sociedad desigual puede tener una concepción exigente de justicia.','Relacionar publicidad jurídica y legitimación de la realeza.'],['Martha Roth, Law Collections from Mesopotamia and Asia Minor.']),
 merikare:MC([
  'Las Instrucciones para Merikare pertenecen al género sapiencial y muestran una concepción del gobierno muy distinta de la imagen simplificada del “despotismo oriental”. El gobernante aparece sometido a exigencias de prudencia, verdad, memoria y justicia. El poder real es fuerte, pero su eficacia depende de saber usarlo con medida.',
  'El concepto decisivo es Maat. Traducirlo sólo como justicia es insuficiente: reúne verdad, orden, equilibrio, corrección y adecuada articulación de relaciones. El rey gobierna bien cuando contribuye a mantener ese orden. La palabra, la selección de funcionarios y el uso discriminado de la coerción son tecnologías políticas para producir Maat.',
  'La obra es especialmente valiosa porque incorpora memoria del error. El consejo al príncipe no enseña únicamente virtudes abstractas: recuerda crisis, rebeliones y consecuencias de decisiones equivocadas. La prudencia política se vuelve entonces aprendizaje histórico. En términos contemporáneos, podríamos decir que la legitimidad del soberano depende tanto de su posición como de una práctica de gobierno capaz de evitar que la coerción destruya el orden que pretende preservar.'
 ],['Maat como horizonte del gobierno.','Palabra regia y selección de funcionarios.','Memoria de crisis y aprendizaje político.','Coerción selectiva y clemencia.','Realeza como responsabilidad por orden y prosperidad.'],['Comparar con Aristóteles: ambos vinculan gobierno con fines sustantivos, aunque parten de cosmologías diferentes.','Comparar con literatura medieval de espejos de príncipes.'],['Definir Maat sin reducirla a una sola palabra castellana.','Explicar por qué la prudencia es una virtud política.','Mostrar cómo el texto presupone límites internos al ejercicio del poder.']),
 peasant:MC([
  'El Campesino elocuente es una narración sobre injusticia, petición y palabra. Su interés teórico reside en que un sujeto socialmente inferior puede formular una exigencia de Maat frente a autoridades superiores. No cuestiona de manera moderna la institución monárquica; cuestiona la distancia entre el orden justo que el poder proclama y la práctica injusta de sus agentes.',
  'La elocuencia del campesino convierte la queja privada en argumento público. La justicia deja de ser sólo atributo del rey y se vuelve una norma que puede ser invocada contra funcionarios. Esa estructura es políticamente potente: una ideología de legitimidad puede proporcionar lenguaje para criticar al propio poder que la produce.',
  'Para teoría política, el texto permite trabajar tres niveles. Primero, la materialidad de una injusticia concreta. Segundo, la capacidad de la palabra para universalizarla como problema de justicia. Tercero, la responsabilidad jerárquica de una autoridad que debe hacer que Maat sea efectiva. Es un buen caso para discutir cuándo el pensamiento político situado comienza a producir argumentos de alcance más general.'
 ],['Despojo inicial y asimetría social.','Petición ante autoridades.','Elocuencia como transformación de agravio en demanda de justicia.','Maat como criterio invocado desde abajo.','Resolución y restauración del orden.'],['Comparar con Antígona: en ambos casos una obligación superior permite cuestionar una decisión de autoridad.','Comparar con teorías modernas de petición y esfera pública, evitando anacronismos.'],['Explicar cómo una norma regia puede ser utilizada críticamente desde abajo.','Distinguir crítica de funcionarios de rechazo de la monarquía.','Relacionar palabra, justicia y jerarquía.']),
 confucius:MC([
  'Confucio piensa la política desde la formación del carácter. Frente a una lectura moderna que identifica gobierno con leyes y sanciones, las Analectas preguntan qué tipo de personas y prácticas hacen posible un orden estable. El gobernante eficaz no es el que castiga más, sino aquel cuya conducta tiene fuerza ejemplar y alrededor del cual los roles sociales adquieren coherencia.',
  'Dos conceptos organizan esta perspectiva. De designa una virtud con capacidad de influencia; li refiere a ritos, formas y conductas apropiadas que educan disposiciones. El rito no es decoración ceremonial: estructura maneras de hablar, obedecer, respetar y juzgar. La política se vuelve una pedagogía distribuida en familia, escuela, administración y corte.',
  'La rectificación de nombres agrega una dimensión institucional. Si alguien lleva el nombre de gobernante, padre, ministro o hijo, su práctica debe corresponder a las responsabilidades vinculadas con ese nombre. Cuando títulos y conducta se separan, el lenguaje mismo del orden se vacía. Confucio permite así pensar legitimidad como correspondencia entre posición, virtud y desempeño.'
 ],['Crisis de Zhou y nostalgia reformista.','Junzi y formación de la persona ejemplar.','De y gobierno por ejemplo.','Li como práctica social y política.','Rectificación de nombres y responsabilidad de roles.'],['Comparar con Han Fei: virtud y ritual frente a reglas, técnicas y poder posicional.','Comparar con Aristóteles: ambos vinculan política y formación del carácter, pero difieren en instituciones y antropología.'],['Explicar por qué li es políticamente relevante.','Distinguir virtud confuciana de moralidad puramente privada.','Relacionar rectificación de nombres y legitimidad.']),
 mencius:MC([
  'Mencio desarrolla la tradición confuciana introduciendo con mucha fuerza el bienestar del pueblo como criterio de gobierno. Su famosa afirmación de que el pueblo tiene prioridad sobre el gobernante no equivale a soberanía popular moderna, pero sí altera el modo de pensar legitimidad: un rey que destruye sustento y humanidad de sus súbditos deja de comportarse como rey.',
  'La política menciana está conectada con una antropología moral. Los seres humanos poseen “brotes” de virtudes que pueden desarrollarse o atrofiarse. Por eso un orden político que condena a la población a hambre y precariedad no puede exigir conducta moral como si las condiciones materiales fueran irrelevantes. Gobierno benevolente implica instituciones y políticas que hagan posible la vida ética.',
  'La discusión sobre el tirano es crucial. Mencio puede sostener que matar a un déspota no es matar a un rey, porque la tiranía ha destruido el estatus normativo de la autoridad. Para un estudiante, este punto permite diferenciar tres ideas que suelen confundirse: bienestar popular, legitimidad política y soberanía democrática.'
 ],['Naturaleza humana y brotes morales.','Gobierno benevolente.','Sustento material y vida ética.','Pueblo como criterio de legitimidad.','Tirano y pérdida del mandato.'],['Comparar con Locke sobre resistencia: ambos permiten pérdida de autoridad, pero a partir de lenguajes normativos diferentes.','Comparar con Confucio para ver la intensificación del criterio popular.'],['Explicar por qué bienestar material es parte de la moral política.','No convertir “pueblo” en soberanía popular moderna.','Reconstruir la lógica de pérdida de legitimidad del tirano.']),
 mozi:MC([
  'Mozi representa una alternativa radical dentro del pensamiento chino antiguo. Critica costumbres aristocráticas, rituales costosos y guerras ofensivas desde un criterio práctico: las instituciones deben producir beneficios para la población y reducir daños. Su doctrina de preocupación imparcial cuestiona la prioridad absoluta de vínculos particulares cuando éstos justifican favoritismo o conflicto.',
  'La política mohista combina moral universalizante y organización meritocrática. Los funcionarios deberían ser promovidos por capacidad, no por nacimiento, y el gobierno debe establecer estándares comunes capaces de coordinar juicios. Esta defensa de uniformidad tiene un costado igualitario, pero también puede justificar una jerarquía muy disciplinada.',
  'Su crítica de la guerra ofensiva es especialmente importante. Mozi razona que prácticas condenadas cuando las realiza un individuo —robo, asesinato— no se vuelven justas simplemente porque las ejecute un Estado a gran escala. Es uno de los primeros lugares donde puede estudiarse una crítica sistemática de la doble moral entre violencia privada y pública.'
 ],['Crítica de lujo ritual y gasto aristocrático.','Preocupación imparcial.','Promoción de los capaces.','Estándares comunes y organización jerárquica.','Crítica de la guerra ofensiva.'],['Comparar con utilitarismo moderno sólo como analogía limitada.','Comparar con Confucio: ritual particularista frente a criterio más universalizante de beneficio.'],['Explicar preocupación imparcial.','Relacionar mérito y centralización.','Reconstruir la crítica mohista de la guerra.']),
 laozi:MC([
  'El Daodejing ofrece una crítica paradójica del exceso de gobierno. Cuantas más regulaciones, ambiciones y demostraciones de control produce el gobernante, más puede intensificar aquello que busca corregir. El concepto de wu wei —no-acción o acción no forzada— no propone inactividad absoluta, sino una forma de intervenir sin imponer constantemente esquemas artificiales.',
  'La sencillez política tiene una dimensión crítica. El texto sospecha de acumulación, guerra, ostentación y crecimiento de deseos producidos por jerarquías. El buen gobernante crea condiciones en las que el orden puede emerger sin convertir su propia presencia en espectáculo permanente.',
  'Para teoría política comparada, Laozi sirve para interrogar un supuesto muy extendido: que gobernar mejor significa necesariamente hacer más. La obra obliga a pensar costos de intervención, efectos no previstos y poder de formas indirectas de conducción. Pero debe evitarse convertir wu wei en una anticipación de laissez-faire liberal: su antropología y su crítica del deseo pertenecen a otro universo intelectual.'
 ],['Dao como orden no reducible a diseño humano.','Wu wei y acción no forzada.','Crítica de exceso normativo.','Sencillez y reducción de deseos políticos.','Gobierno indirecto y paradoja del control.'],['Comparar con Hayek sólo de manera heurística: ambos desconfían del control excesivo, pero por razones muy diferentes.','Comparar con legalismo para observar dos respuestas opuestas al desorden.'],['Definir wu wei sin decir “no hacer nada”.','Explicar la crítica del exceso de gobierno.','Evitar traducir el daoísmo a liberalismo económico.']),
 xunzi:MC([
  'Xunzi comparte con Confucio la centralidad de ritual y educación, pero parte de una antropología más pesimista. Los deseos humanos, si no son formados, generan competencia y conflicto. El orden no surge espontáneamente de una bondad natural; requiere instituciones, prácticas y aprendizaje capaces de transformar disposiciones.',
  'Esta posición vuelve al rito mucho más institucional. Li organiza jerarquías, distribuye bienes, canaliza deseos y hace previsible la interacción. La cultura política aparece como una construcción artificial en sentido positivo: precisamente porque no nacemos ya ordenados, la civilización es una obra colectiva.',
  'Xunzi es además un puente decisivo hacia el legalismo. Han Fei fue asociado a su escuela, pero extrae conclusiones diferentes: donde Xunzi sigue confiando en educación y rito, Han Fei enfatiza ley, técnica y posición. La comparación permite estudiar cómo una misma premisa —la insuficiencia de espontaneidad moral— puede producir teorías políticas divergentes.'
 ],['Naturaleza humana y deseos.','Artificialidad positiva de cultura.','Rito como orden institucional.','Educación y transformación.','Puente hacia debates legalistas.'],['Comparar con Mencio sobre naturaleza humana.','Comparar con Han Fei sobre si la respuesta es educación o dispositivos impersonales.'],['Reconstruir la controversia Mencio–Xunzi.','Explicar rito como institución.','Mostrar por qué “artificio” no significa falsedad.']),
 hanfeizi:MC([
  'Han Fei desconfía de teorías que hacen depender un Estado del carácter excepcionalmente virtuoso del gobernante. La cuestión es institucional: ¿cómo puede funcionar un aparato cuando ministros tienen intereses propios, información asimétrica y oportunidades de capturar al soberano? Su respuesta combina fa, shu y shi.',
  'Fa son estándares y reglas que permiten evaluar desempeño; shu son técnicas administrativas para controlar información y funcionarios; shi es poder derivado de la posición. La autoridad debe residir en un cargo y en mecanismos, no en carisma. Esta impersonalidad puede parecer moderna, pero está al servicio de una soberanía extremadamente concentrada.',
  'La riqueza de Han Fei está en esa tensión: intenta reducir arbitrariedad de ministros mediante reglas mientras preserva amplia discreción del soberano. Por eso es insuficiente clasificarlo simplemente como “autoritario”. Es una teoría sofisticada de principal-agente, burocracia y capacidad estatal dentro de un proyecto de centralización.'
 ],['Problema de ministros y captura.','Fa: reglas y estándares.','Shu: técnicas de administración.','Shi: poder de posición.','Recompensa, castigo y centralización.'],['Comparar con Weber sobre burocracia, sin borrar diferencia entre legalidad racional moderna y legalismo antiguo.','Comparar con Confucio y Xunzi.'],['Distinguir fa, shu y shi.','Explicar por qué impersonalidad no implica liberalismo.','Analizar el problema de información entre soberano y funcionarios.']),
 shangyang:MC([
  'El Libro del Señor Shang lleva el programa legalista hacia una transformación deliberada de sociedad y Estado. El objetivo no es conservar costumbres heredadas, sino construir capacidad estatal mediante leyes uniformes, registro de población, incentivos, agricultura y guerra.',
  'Shang Yang considera peligrosas las autonomías aristocráticas y los criterios morales particulares que compiten con el Estado. La ley debe ser clara y general en su aplicación para volver calculables las consecuencias. Mérito militar y productividad reemplazan privilegios de nacimiento como bases de promoción.',
  'La paradoja es que ciertas medidas igualadoras —uniformidad legal, debilitamiento de nobleza hereditaria, promoción por desempeño— sirven a una concentración extrema de poder. Esto ayuda a los estudiantes a separar igualdad formal ante ciertas reglas de libertad política y a comprender que construcción estatal y emancipación no son sinónimos.'
 ],['Reforma frente a tradición.','Ley uniforme.','Agricultura y guerra como bases fiscales y militares.','Mérito contra privilegio aristocrático.','Centralización territorial y administrativa.'],['Comparar con Tocqueville sobre centralización sólo para contrastar finalidades.','Comparar con Han Fei: Shang Yang enfatiza transformación social y militar.'],['Explicar relación entre reforma social y capacidad estatal.','Distinguir igualación de estatus de libertad.','Relacionar incentivos y construcción del Estado.']),
 kautilya:MC([
  'El Arthaśāstra trata el gobierno como una práctica técnica que integra economía, justicia, inteligencia, guerra y diplomacia. No existe una separación tajante entre administración interna y estrategia externa: un reino es fuerte cuando dispone de tesoro, información, funcionarios controlados y capacidad para evaluar un entorno cambiante.',
  'El famoso mandala describe relaciones entre reinos a partir de posición e intereses. No es una receta mecánica de que “el vecino es enemigo”, sino un esquema para pensar alianzas y rivalidades de manera relacional. La diplomacia incluye paz, guerra, neutralidad, preparación, alianza y doble política.',
  'Sin embargo, reducir Kautilya a cinismo sería un error. Prosperidad de la población y protección frente a abusos son condiciones de la fuerza regia. Un rey que destruye la base productiva debilita el mismo Estado que intenta fortalecer. El texto permite pensar conjuntamente razón estratégica y economía política del poder.'
 ],['Disciplina personal del rey.','Funcionarios, auditoría y corrupción.','Fiscalidad y economía.','Espionaje e información.','Mandala, guerra y diplomacia.'],['Comparar con Maquiavelo sobre prudencia estratégica.','Comparar con Han Fei sobre control administrativo.'],['Explicar por qué artha no equivale simplemente a riqueza privada.','Describir el mandala como modelo relacional.','Relacionar prosperidad y capacidad estatal.']),
 manu:MC([
  'Las Leyes de Manu pertenecen a una tradición normativa distinta del tratado político moderno. Dharma organiza deberes, estatus, etapas de vida, ritual y autoridad; la política aparece inserta en un orden moral y social mucho más amplio. El rey no crea desde cero la norma que aplica.',
  'La realeza tiene una función coercitiva esencial. Danda, el castigo, protege un orden jerárquico que se considera normativo. Sin sanción, los deberes se disolverían; con sanción arbitraria, el rey mismo destruiría el dharma. El gobierno es necesario precisamente porque el orden moral no se reproduce automáticamente.',
  'Para estudiantes contemporáneos, el texto exige una doble operación: comprender su lógica sin legitimar sus jerarquías de casta y género. Es un caso útil para distinguir análisis histórico de aprobación normativa y para comparar órdenes donde la autoridad política está subordinada a una norma religiosa-jurídica que la precede.'
 ],['Dharma como orden de deberes.','Varna, estatus y jerarquía.','Rey y administración de justicia.','Danda como coerción necesaria.','Relación entre norma social y poder político.'],['Comparar con Tomás de Aquino: autoridad política dentro de un orden normativo superior, aunque con teologías y estructuras sociales distintas.','Comparar con Hobbes sobre necesidad de coerción, destacando las diferencias de fundamento.'],['Explicar por qué el rey no es soberano legislador moderno.','Relacionar dharma y danda.','Analizar críticamente jerarquías sin anacronismo.'])
});