// Ajustes editoriales y capa de estudio del Atlas.
const iiggHub=HUBS.find(h=>h.id==='iigg');
if(iiggHub){iiggHub.people=['Luciano Nosetto','Gabriela Rodríguez Rial','María Cecilia Abdo Ferez','Ricardo Laleff Ilieff','Sabrina Morán','Mariana Cané','Fabricio Ezequiel Castro','Mirna Lucaccini'];iiggHub.activity='Investigación y docencia en teoría política moderna y contemporánea, republicanismo, Estado, subjetivación y epistemología disciplinar; fuerte presencia en proyectos UBA/CONICET y en el área Teoría y Filosofía Políticas de SAAP.';}
if(!HUBS.some(h=>h.id==='litoral'))HUBS.push({id:'litoral',scope:'arg',name:'Teoría y filosofía políticas — UNR / UNL / CONICET',place:'Rosario y Santa Fe · Argentina',method:'Teoría política contemporánea, historia política e intelectual, derechas, democracia, republicanismo y crisis de lo político',people:['Gastón Souroujon','Cecilia Lesgart','Sergio Morresi','Natacha Bacolla','equipos UNR/UNL-CONICET'],activity:'Núcleo visible en el área de Teoría y Filosofía Políticas del Congreso SAAP, con paneles sobre escenario contemporáneo, democracia, derechas y relecturas conceptuales.',url:'https://www.fcpolit.unr.edu.ar/',color:'#8f2f35'});
const apt=EVENTS.find(e=>e.name.includes('APT Conference'));if(apt){apt.date='Conferencia anual';apt.place='Association for Political Theory · Estados Unidos';apt.status='Recurrente';apt.desc='Encuentro especializado de teoría y filosofía política. Para sede y fechas de cada edición, consultar el calendario oficial de APT.';}

// Genealogías principales: la vista troncal deliberadamente no intenta incluir a todos los autores.
const CLASSIC_GENEALOGIES=[
 {id:'republica',name:'República, virtud y libertad',color:'#9f3d2d',desc:'De la polis y la constitución mixta a la libertad republicana como no-dominación.',works:['republic','politics','polybius','cicero','discourses','montesquieu','rousseau','federalist','tocqueville','pettit']},
 {id:'soberania',name:'Soberanía, contrato y obligación',color:'#2d617f',desc:'La formación moderna de la autoridad soberana, el consentimiento, los derechos y el problema de la obediencia.',works:['bodin','leviathan','spinoza','locke','rousseau','sieyes','hegel','rawls','nozick']},
 {id:'liberalismo',name:'Liberalismo, representación y democracia',color:'#456d58',desc:'De derechos, límites y representación a pluralismo, igualdad democrática y justicia institucional.',works:['locke','montesquieu','federalist','constant','tocqueville','mill','mill-gov','berlin','rawls','habermas']},
 {id:'critica',name:'Idealismo, socialismo y hegemonía',color:'#68547d',desc:'De la libertad institucional hegeliana a la crítica del capitalismo, el Estado y la construcción hegemónica.',works:['hegel','manifesto','marx18','lenin','luxemburg','gramsci','laclau','mouffe']},
 {id:'poder',name:'Poder, decisión y subjetivación',color:'#474c55',desc:'Genealogías que desplazan la mirada desde la ley hacia moral, violencia, disciplina, identidad y formas de subjetivación.',works:['nietzsche','weber','schmitt','arendt-origins','foucault','butler','ranciere','mbembe']},
 {id:'emancipacion',name:'Emancipación, colonialidad y América Latina',color:'#b87925',desc:'Independencia, cuestión nacional, dependencia, liberación, colonialidad y construcción del pueblo.',works:['bolivar-j','marti','mariategui','prebisch','freire','cardoso','zavaleta','quijano','dussel','laclau']},
 {id:'antiguos',name:'Órdenes antiguos y gobierno',color:'#9a6324',desc:'Una ampliación comparativa del origen de las preguntas sobre justicia, virtud, ley, administración y buen gobierno.',works:['gilgamesh','hammurabi','merikare','confucius','mencius','hanfeizi','kautilya','republic','politics']}
];

const DG=(summary,architecture,keys,debates,reception,study,secondary=[])=>({summary,architecture,keys,debates,reception,study,secondary});
const DEEP_GUIDES={
 gilgamesh:DG(
 ['La epopeya no es un tratado político, pero contiene una reflexión extraordinariamente temprana sobre los límites del poder personal. Gilgamesh aparece primero como un rey cuya fuerza carece de medida; la ciudad y los dioses responden creando un contrapeso en Enkidu.','El núcleo político está en la transformación del soberano: la experiencia de amistad, pérdida y mortalidad desplaza la búsqueda de gloria individual hacia una conciencia de la ciudad, las obras comunes y los límites humanos.'],
 ['Prólogo: Uruk y el problema del rey excesivo.','Enkidu como límite, igual y compañero.','Combate, gloria y expansión del horizonte regio.','Muerte de Enkidu y crisis de la pretensión heroica.','Regreso a Uruk: la ciudad como obra duradera frente a la mortalidad.'],
 {'realeza':'Poder excepcional que necesita medida para convertirse en gobierno.','civilización':'Paso de la fuerza natural a normas, vínculos, ciudad y lenguaje.','mortalidad':'Límite ontológico que impide convertir poder y gloria en dominio absoluto.','ciudad':'Obra colectiva que sobrevive al individuo y reordena el sentido de la realeza.'},
 ['¿Debe leerse políticamente un poema épico sin proyectar categorías modernas?','¿La transformación de Gilgamesh es moral, política o ambas?','La relación entre poder regio, ciudad y legitimidad antes de una teoría política sistemática.'],
 ['Historia de la realeza mesopotámica.','Debates sobre la prehistoria de la teoría política y los límites del canon griego.'],
 ['Retener la oposición fuerza/medida.','Usar Enkidu como figura de límite y reciprocidad.','Relacionar mortalidad con la imposibilidad de soberanía absoluta.'],
 ['Andrew George, estudios y edición crítica de Gilgamesh.','Mario Liverani, historia política del antiguo Oriente.']),
 hammurabi:DG(
 ['El Código combina prólogo, colección de decisiones normativas y epílogo. Su significado político no reside sólo en cada regla, sino en la representación del rey como agente de justicia que protege el orden y hace visible una capacidad de juzgar.','La obra muestra que ley, jerarquía y desigualdad pueden coexistir dentro de una pretensión de justicia: la norma diferencia estatus sociales, pero al mismo tiempo limita ciertas formas de arbitrariedad.'],
 ['Prólogo teológico: elección del rey y misión de justicia.','Casos sobre propiedad, familia, trabajo, daño y responsabilidad.','Jerarquías de estatus en la aplicación de sanciones.','Epílogo: memoria, publicidad y autorrepresentación del soberano.'],
 {'justicia':'Misión regia de impedir que el fuerte destruya al débil, dentro de una sociedad jerárquica.','ley':'Decisiones formuladas casuísticamente, no un código moderno exhaustivo.','realeza':'Centro que publica y simboliza el orden jurídico.','publicidad':'La estela convierte la justicia en una representación visible del poder.'},
 ['¿Es correcto llamarlo “código” en sentido moderno?','Justicia sustantiva versus desigualdad de estatus.','Norma jurídica, propaganda regia y práctica judicial.'],
 ['Historia del derecho.','Teorías de estatalidad temprana y legitimación monárquica.'],
 ['Distinguir texto legal de práctica real.','No confundir universalidad de la justicia con igualdad moderna.','Observar cómo la autoridad se legitima mediante una función jurídica.'],
 ['Martha Roth, estudios sobre las colecciones legales mesopotámicas.','Dominique Charpin, trabajos sobre derecho y sociedad babilónica.']),
 merikare:DG(
 ['Las Instrucciones para Merikare presentan el gobierno como una práctica que exige prudencia, memoria histórica y control del uso de la fuerza. La palabra del rey, su relación con funcionarios y su atención a la justicia forman parte de una tecnología de restauración del orden.','La Maat no es simplemente “moral”: articula verdad, equilibrio, justicia y buen funcionamiento del mundo social. La autoridad legítima debe reproducir ese orden y evitar que la coerción indiscriminada lo destruya.'],
 ['Consejos sobre funcionarios, palabra y conducta del rey.','Memoria de errores políticos y rebeliones.','Uso selectivo de coerción y clemencia.','Relación entre justicia, culto y estabilidad.'],
 {'maat':'Orden verdadero y justo que el gobierno debe sostener.','prudencia':'Capacidad de medir consecuencias y aprender de experiencias previas.','palabra':'Instrumento de mando, persuasión y justicia.','coerción':'Necesaria, pero políticamente costosa cuando es indiscriminada.'},
 ['Maat como cosmología, ética o concepto político.','El estatuto autoral y la datación del texto.','La posibilidad de teoría política en literatura sapiencial.'],
 ['Egiptología política.','Comparación de espejos de príncipes y literatura de consejo.'],
 ['Identificar la relación Maat–realeza.','Distinguir prudencia de mera astucia.','Leer el texto como reflexión sobre crisis y restauración.']),
 confucius:DG(
 ['Las Analectas construyen una política centrada en formación moral, ritual y ejemplo. El gobierno no comienza por el castigo, sino por la capacidad de orientar conductas mediante modelos de excelencia.','El gobernante debe cultivar de (virtud/potencia moral), respetar li (ritos y formas apropiadas) y favorecer una sociedad donde los nombres y roles correspondan a prácticas responsables.'],
 ['Cultivo del junzi, la persona ejemplar.','Rito y aprendizaje como formación política.','Gobierno por virtud frente a castigo.','Rectificación de nombres y responsabilidad de los roles.','Relaciones, reciprocidad y orden social.'],
 {'de':'Virtud eficaz que hace posible gobernar por ejemplo.','li':'Rito, forma y práctica que educan disposiciones.','junzi':'Persona ejemplar formada para actuar correctamente.','rectificación de nombres':'Correspondencia entre títulos, expectativas y conducta efectiva.'},
 ['¿Confucio propone conservadurismo jerárquico o una reforma meritocrática?','Virtud personal versus diseño institucional.','Cómo traducir conceptos chinos sin occidentalizarlos.'],
 ['Confucianismo imperial.','Debates contemporáneos sobre meritocracia, ética de roles y democracia confuciana.'],
 ['Comparar gobierno por virtud y por castigo.','Explicar por qué el rito tiene dimensión política.','Relacionar educación, carácter e instituciones.']),
 mencius:DG(
 ['Mencio radicaliza la relación entre gobierno moral y bienestar del pueblo. Un rey que destruye las condiciones de vida y actúa como tirano pierde el estatuto moral que sostiene su autoridad.','La benevolencia no es sentimentalismo: exige políticas materiales capaces de asegurar subsistencia y condiciones para el cultivo moral.'],
 ['Naturaleza humana y brotes de virtud.','Gobierno benevolente y economía moral del pueblo.','Mandato y legitimidad.','Crítica del tirano.'],
 {'ren':'Benevolencia que debe estructurar conducta y gobierno.','pueblo':'Base material y moral de la comunidad política.','mandato':'Legitimación celeste que puede perderse por mal gobierno.','tirano':'Gobernante que destruye las condiciones de su propia legitimidad.'},
 ['¿Existe en Mencio un derecho de resistencia?','Popularidad política versus soberanía popular moderna.','Naturaleza humana y diseño institucional.'],
 ['Neo-confucianismo.','Teorías contemporáneas de legitimidad confuciana.'],
 ['Recordar la centralidad del bienestar material.','Distinguir pueblo como criterio de legitimidad de democracia electoral.','Relacionar antropología moral y política.']),
 hanfeizi:DG(
 ['Han Fei parte de una desconfianza hacia la dependencia de la virtud personal. Un Estado estable necesita reglas públicas, técnicas administrativas y una posición de autoridad que no pueda ser capturada por ministros o clanes.','El legalismo desplaza la pregunta desde “¿cómo formar un gobernante bueno?” hacia “¿qué dispositivos permiten que el aparato funcione aun con actores interesados?”.'],
 ['Crítica de modelos morales y del gobierno por antigüedad.','Fa: estándares y leyes.','Shu: técnicas de control administrativo.','Shi: poder de la posición institucional.','Recompensas, castigos y control de ministros.'],
 {'fa':'Estándares públicamente utilizables.','shu':'Técnicas administrativas para evaluar y controlar funcionarios.','shi':'Potencia inherente a la posición, no al carisma personal.','Estado':'Aparato que debe reducir discrecionalidad de intermediarios.'},
 ['¿Legalismo equivale a autoritarismo?','Impersonalidad legal y concentración soberana.','Relación entre burocracia, mérito y coerción.'],
 ['Formación del imperio Qin.','Teoría comparada del Estado y burocracia.'],
 ['Diferenciar fa, shu y shi.','Compararlo con Confucio: virtud versus dispositivos.','Observar su modernidad aparente sin convertirlo en Hobbes chino.']),
 kautilya:DG(
 ['El Arthaśāstra presenta el poder como una práctica técnica: impuestos, espionaje, justicia, administración, guerra, alianzas y economía forman una misma ciencia del gobierno.','Su realismo no implica ausencia de normatividad. El rey eficaz debe proteger el reino, evitar abusos administrativos y sostener prosperidad, porque la capacidad estatal depende de recursos y cooperación social.'],
 ['Formación y disciplina del rey.','Administración, tesoro y funcionarios.','Justicia y control interno.','Inteligencia y espionaje.','Mandala de reinos, alianzas y guerra.'],
 {'artha':'Prosperidad y poder material como dimensión autónoma de gobierno.','mandala':'Modelo relacional del entorno estratégico.','danda':'Capacidad coercitiva y disciplina.','administración':'Infraestructura de información, fiscalidad y control.'},
 ['Datación y composición estratificada.','Realismo versus dharma.','Comparaciones con Maquiavelo y sus límites.'],
 ['Estudios estratégicos.','Historia del pensamiento político indio y teoría comparada.'],
 ['Explicar por qué no es sólo un manual militar.','Relacionar información y capacidad estatal.','Evitar equiparar directamente Kautilya con Maquiavelo.']),
 republic:DG(
 ['La República parte de una pregunta aparentemente moral —qué es la justicia— y la amplía hasta convertirla en una investigación sobre educación, conocimiento, constitución y psicología política. La ciudad funciona como “letras grandes” para leer el alma, pero el argumento no se reduce a una analogía simple.','Platón intenta mostrar que un régimen estable depende de una jerarquía correcta entre saber, deseo y honor. La política queda así vinculada a una teoría del conocimiento: gobernar bien exige distinguir apariencia de realidad y educar deseos, no sólo distribuir cargos.'],
 ['Libro I: definiciones convencionales de justicia y desafío de Trasímaco.','Libros II–IV: origen de la ciudad, educación de guardianes y justicia como orden de funciones.','Libros V–VII: comunidad de guardianes, filósofos gobernantes, línea dividida y caverna.','Libros VIII–IX: degeneración de regímenes y correspondencia entre tipos de alma y constitución.','Libro X: poesía, inmortalidad y mito de Er.'],
 {'justicia':'Orden en el que cada parte cumple su función bajo una jerarquía adecuada.','filósofo-rey':'Figura que une conocimiento del bien y capacidad de gobierno.','paideia':'Educación que forma deseos, percepción y criterio político.','caverna':'Imagen de formación, conocimiento y obligación de retornar al mundo común.','timocracia/oligarquía/democracia/tiranía':'Secuencia de regímenes que expresa transformaciones del carácter y del deseo.'},
 ['¿La ciudad ideal es un programa literal, una analogía moral o una construcción crítica?','La crítica platónica a la democracia y la experiencia ateniense.','La relación entre conocimiento y autoridad: ¿epistocracia?','Género y comunidad de mujeres guardianas.'],
 ['Neoplatonismo y filosofía cristiana.','Strauss y lecturas esotéricas; Popper y crítica antitotalitaria; debates contemporáneos sobre epistocracia.'],
 ['Para examen: reconstruir el argumento desde Trasímaco hasta la ciudad justa.','No separar la caverna del problema de quién debe gobernar.','Usar la secuencia de regímenes para explicar psicología política.','Comparar con Leyes para ver el desplazamiento hacia instituciones.'],
 ['Julia Annas, introducciones a la República.','G. R. F. Ferrari, estudios sobre ciudad y alma.','C. D. C. Reeve, trabajos sobre conocimiento y gobierno.']),
 politics:DG(
 ['La Política combina investigación empírica, clasificación de regímenes y filosofía normativa. Aristóteles no busca una única constitución válida para todo lugar: distingue el mejor régimen en absoluto, el mejor dadas ciertas condiciones y los mecanismos que explican estabilidad y revolución.','El concepto de polis organiza toda la obra. La comunidad política no existe sólo para sobrevivir, sino para vivir bien; por eso ciudadanía, virtud, propiedad, educación y distribución de cargos son problemas internos de una teoría del régimen.'],
 ['Libro I: comunidad, oikos, esclavitud y adquisición.','Libros II–III: crítica a constituciones, ciudadanía y definición de régimen.','Libros IV–VI: tipología, politeia, clase media, estabilidad y cambio.','Libros VII–VIII: mejor régimen, educación y vida buena.'],
 {'polis':'Comunidad autosuficiente orientada a la vida buena.','ciudadano':'Quien participa en funciones deliberativas y judiciales, definición dependiente del régimen.','politeia':'Constitución y, en sentido específico, régimen mixto orientado al bien común.','bien común':'Criterio que separa formas rectas de desviadas.','clase media':'Base sociológica de moderación y estabilidad en ciertos regímenes.'},
 ['Naturalidad de la polis y carácter histórico de las comunidades.','La defensa de esclavitud natural.','Democracia y oligarquía como regímenes de pobres y ricos, no sólo de muchos y pocos.','Aristóteles entre republicanismo, perfeccionismo y ciencia política comparada.'],
 ['Republicanismo cívico.','Escolástica medieval.','Teoría de constituciones y ciudadanía.'],
 ['Distinguir régimen de conjunto de instituciones.','Explicar rectos/desviados por finalidad, no sólo número.','Recordar la importancia de la clase media y causas de revolución.','Comparar con Platón: pluralidad constitucional frente a unidad ideal.'],
 ['Fred D. Miller, estudios sobre naturaleza, justicia y derechos en Aristóteles.','Carnes Lord, trabajos sobre Aristóteles político.']),
 polybius:DG(
 ['El Libro VI de las Historias explica el ascenso romano mediante una teoría dinámica de los regímenes. Monarquía, aristocracia y democracia pueden degenerar; la constitución mixta reduce ese riesgo distribuyendo poder entre magistraturas, Senado y pueblo.','La importancia de Polibio para la teoría política reside en unir ciclos históricos y arquitectura institucional: las instituciones son fuertes cuando cada parte necesita y controla a las otras.'],
 ['Anaciclosis: ciclo de formas rectas y corruptas.','Constitución romana como mezcla.','Cónsules, Senado y pueblo.','Disciplina, religión cívica y expansión.'],
 {'anaciclosis':'Secuencia recurrente de nacimiento y corrupción de regímenes.','constitución mixta':'Combinación de principios monárquico, aristocrático y democrático.','equilibrio':'Dependencia mutua que previene predominio estable de una parte.','imperio':'Expansión que la constitución ayuda a explicar, pero también tensiona.'},
 ['¿Polibio describe Roma o la idealiza?','Equilibrio social versus equilibrio institucional.','Relación entre éxito imperial y virtud republicana.'],
 ['Cicerón.','Maquiavelo.','Tradición de gobierno mixto y constitucionalismo.'],
 ['Retener la lógica ciclo/mezcla.','Compararlo con Aristóteles y con Montesquieu.']),
 cicero:DG(
 ['Cicerón traduce filosofía griega al vocabulario jurídico y cívico romano. Res publica significa una cosa del pueblo, pero el pueblo no es mera multitud: está unido por acuerdo sobre derecho y comunidad de intereses.','La constitución mixta y la virtud del estadista aparecen como defensas frente a facción, corrupción y concentración de poder. La ley natural permite además pensar un estándar de justicia que no depende enteramente de la legislación positiva.'],
 ['Definición de res publica y populus.','Formas de gobierno y constitución mixta.','Figura del rector rei publicae.','Justicia, derecho y comunidad.','En De legibus: razón y ley natural.'],
 {'res publica':'Orden común que pertenece a un pueblo jurídicamente articulado.','libertas':'Condición cívica incompatible con dominación arbitraria.','ley natural':'Razón normativa que permite juzgar leyes positivas.','virtus':'Excelencia cívica orientada al servicio de la comunidad.'},
 ['Cicerón republicano versus defensor aristocrático del Senado.','El estatuto del “estadista rector”.','Continuidad entre filosofía estoica y derecho romano.'],
 ['Agustín.','Humanismo cívico renacentista.','Republicanismo neo-romano.','Tradición del derecho natural.'],
 ['Relacionar pueblo con derecho.','Distinguir libertad republicana de libertad privada moderna.','Vincular constitución mixta y crisis tardorrepublicana.']),
 citygod:DG(
 ['Agustín desarma la identificación entre Roma y un orden político providencial. La ciudad terrena y la ciudad de Dios no son dos Estados concretos, sino dos orientaciones del amor que atraviesan la historia.','La política queda relativizada pero no anulada. Debido al pecado, coerción y autoridad pueden ser necesarias para sostener una paz temporal; sin embargo, ningún imperio puede reclamar ser la encarnación perfecta de justicia.'],
 ['Libros I–V: crítica a la religión cívica y explicación no providencialista del éxito romano.','Libros XI–XIV: origen de las dos ciudades.','Libros XV–XVIII: desarrollo histórico entremezclado.','Libros XIX–XXII: paz, justicia, fines y destino último.'],
 {'dos ciudades':'Comunidades definidas por orientaciones del amor, no por fronteras estatales.','paz':'Orden relativo de bienes que incluso comunidades imperfectas buscan.','pecado':'Condición que impide realizar justicia perfecta políticamente.','providencia':'Historia con sentido trascendente que no legitima automáticamente un imperio particular.'},
 ['¿Agustín despolitiza el cristianismo o funda un realismo político?','Relación con Cicerón: ¿puede Roma ser res publica sin verdadera justicia?','Coerción religiosa y tolerancia.'],
 ['Teología política medieval.','Realismo cristiano.','Debates modernos sobre secularización.'],
 ['No identificar dos ciudades con Iglesia/Estado.','Explicar la paz temporal.','Comparar su definición de república con Cicerón.']),
 aquinas:DG(
 ['Tomás integra Aristóteles con teología cristiana y derecho natural. El gobierno se justifica porque seres humanos necesitan coordinación para perseguir un bien común que supera intereses particulares.','La monarquía puede ser eficaz para producir unidad, pero su corrupción es la tiranía. Por eso la cuestión política central no es sólo quién gobierna, sino cómo orientar autoridad y ley hacia bienes comunes y limitar desviaciones.'],
 ['Finalidad social del gobierno.','Comparación de formas de gobierno.','Monarquía y riesgo de tiranía.','Bien común, ley y virtud.'],
 {'bien común':'Fin compartido que hace legítimo al gobierno.','ley natural':'Participación racional en un orden normativo que orienta la ley humana.','tiranía':'Gobierno para interés privado del gobernante.','prudencia política':'Juicio práctico aplicado a la conducción de la comunidad.'},
 ['Tomás como monárquico o constitucionalista.','Resistencia al tirano y límites de la acción privada.','Relación entre gracia, naturaleza y política.'],
 ['Escolástica tardía.','Derecho natural moderno.','Tradición católica del bien común.'],
 ['Distinguir bien común de suma de preferencias.','Explicar por qué la tiranía es corrupción de la finalidad del gobierno.']),
 prince:DG(
 ['El príncipe analiza la política desde la contingencia, la fundación y la conservación del Estado. Maquiavelo separa la virtud política de la bondad moral convencional: un gobernante debe aprender a no ser bueno cuando la necesidad lo exige.','Virtù no significa virtud cristiana, sino capacidad de leer coyunturas, actuar con decisión, crear apoyos y reducir dependencia de fortuna. El texto es inseparable de la fragmentación italiana y de la cuestión de cómo fundar un orden capaz de sostenerse.'],
 ['Caps. I–XI: tipos de principados y modos de adquisición.','Caps. XII–XIV: armas propias y mercenarias.','Caps. XV–XIX: cualidades del príncipe, temor, amor y reputación.','Caps. XX–XXV: fortalezas, consejeros, fortuna.','Cap. XXVI: exhortación política italiana.'],
 {'virtù':'Capacidad política de actuar eficazmente frente a contingencia.','fortuna':'Dimensión imprevisible que puede ser parcialmente dominada.','necesidad':'Restricciones que obligan a apartarse de moralidad convencional.','armas propias':'Capacidad autónoma sin dependencia de fuerzas ajenas.','apariencia':'Dimensión pública del juicio político y de la reputación.'},
 ['¿Maquiavelo enseña inmoralidad o autonomía de lo político?','El carácter republicano o principesco de su proyecto.','Ironía, retórica y destinatario del texto.'],
 ['Razón de Estado.','Realismo político.','Weber y ética de la responsabilidad.','Strauss y lectura del “maestro del mal”; Skinner y contextualismo republicano.'],
 ['Distinguir virtù de virtud moral.','Conectar armas propias con autonomía política.','Leer cap. XV como quiebre metodológico.','Compararlo con Discursos antes de concluir que Maquiavelo es simplemente autoritario.'],
 ['Quentin Skinner, estudios sobre Maquiavelo y libertad republicana.','J. G. A. Pocock, *The Machiavellian Moment*.']),
 discourses:DG(
 ['Los Discursos permiten ver un Maquiavelo republicano interesado por la duración de un orden libre. El conflicto entre plebe y grandes no aparece sólo como patología: adecuadamente institucionalizado, puede producir leyes favorables a la libertad.','La república necesita mecanismos de renovación porque toda forma política se corrompe. Religión cívica, milicia, acusación pública y retorno a principios son dispositivos para contener esa corrupción.'],
 ['Libro I: fundación, conflicto social e instituciones.','Libro II: expansión, guerra y comparación con Roma.','Libro III: renovación, liderazgo y ejemplos históricos.'],
 {'libertad':'No depender de voluntad arbitraria y participar en instituciones comunes.','tumultos':'Conflictos sociales que pueden tener productividad institucional.','corrupción':'Pérdida de hábitos y estructuras capaces de sostener vida libre.','retorno a principios':'Mecanismo de renovación frente al desgaste institucional.'},
 ['¿Conflicto productivo o mera herramienta de equilibrio?','Expansión imperial y libertad republicana.','Relación entre Discursos y El príncipe.'],
 ['Republicanismo atlántico.','Pocock, Skinner y neo-republicanismo.'],
 ['Usar Roma como laboratorio, no como modelo mecánico.','Explicar por qué los tumultos pueden producir libertad.','Relacionar corrupción y diseño institucional.']),
 bodin:DG(
 ['Bodin formula una de las definiciones clásicas de soberanía como poder absoluto y perpetuo de una república. “Absoluto” no significa caprichoso: el soberano no está sujeto a las leyes ordinarias que él mismo hace, pero sí a ley divina, natural y ciertos compromisos estructurales.','Su teoría responde a un mundo de jurisdicciones superpuestas y guerras civiles religiosas. La soberanía permite imaginar una instancia última de decisión capaz de garantizar unidad jurídica.'],
 ['Definición de república y familia.','Atributos de soberanía.','Leyes, magistrados y formas de gobierno.','Propiedad y límites estructurales.'],
 {'soberanía':'Poder perpetuo y supremo de la república.','majestad':'Conjunto de prerrogativas que expresan la supremacía.','ley':'Mandato del soberano dentro de un orden más amplio de obligaciones.','república':'Gobierno recto de varias familias y de lo que les es común.'},
 ['Bodin como absolutista o jurista de límites.','Indivisibilidad de soberanía y pluralidad de órganos.','Diferencia entre forma de Estado y forma de gobierno.'],
 ['Hobbes.','Teoría moderna del Estado.','Derecho público y soberanía constitucional.'],
 ['Retener absoluto/perpetuo/indivisible.','No equiparar soberanía con poder ilimitado en todos los sentidos.']),
 leviathan:DG(
 ['Hobbes construye una teoría política a partir de individuos aproximadamente iguales en vulnerabilidad, capaces de razón instrumental y movidos por deseos. Sin un poder común, la incertidumbre sobre intenciones ajenas genera una estructura de conflicto que hace insegura la cooperación.','El contrato no es un pacto con el soberano, sino una autorización recíproca entre individuos para constituir una persona artificial que pueda representarlos y dictar reglas comunes. La soberanía resuelve un problema de coordinación y autoridad, no simplemente de violencia.'],
 ['Parte I: sensación, lenguaje, pasiones, razón y estado de naturaleza.','Leyes de naturaleza y contrato.','Parte II: generación del Commonwealth, representación y derechos del soberano.','Libertad de súbditos y límites prácticos de obediencia.','Partes III–IV: religión, interpretación y conflicto de autoridades.'],
 {'estado de naturaleza':'Condición sin autoridad común capaz de garantizar cumplimiento.','leyes de naturaleza':'Preceptos racionales orientados a paz, insuficientes sin garantía coercitiva.','autorización':'Acto por el cual una acción del representante cuenta como propia de los representados.','persona artificial':'Unidad política producida por representación.','soberanía':'Poder común necesario para hacer estables reglas y expectativas.'},
 ['¿El estado de naturaleza es historia, experimento mental o estructura recurrente?','Libertad como ausencia de impedimentos versus obediencia política.','Hobbes como absolutista, liberal proto-moderno o teórico de representación.','Religión y disputa por autoridad interpretativa.'],
 ['Teoría moderna del Estado y soberanía.','Teoría de juegos y problemas de cooperación.','Debates contemporáneos sobre representación.'],
 ['Reconstruir la secuencia igualdad → desconfianza → guerra potencial → leyes de naturaleza → autorización.','No decir que el contrato se firma con el soberano.','Explicar representación como clave del Leviatán.'],
 ['Richard Tuck, estudios sobre Hobbes.','Quentin Skinner, trabajos sobre libertad y representación en Hobbes.']),
 locke:DG(
 ['Locke parte de un estado de naturaleza normativamente ordenado por ley natural. El problema no es ausencia total de derechos, sino falta de juez común, incertidumbre en la interpretación y debilidad para hacer cumplir normas.','La sociedad política surge para proteger vida, libertad y propiedad. El poder legislativo es supremo en función, pero fiduciario: está limitado por fines, reglas generales y el consentimiento. Cuando traiciona ese mandato, el pueblo conserva un derecho de resistencia.'],
 ['Estado de naturaleza y ley natural.','Propiedad mediante trabajo y límites originarios.','Consentimiento y formación de sociedad política.','Poder legislativo, ejecutivo y federativo.','Prerrogativa, disolución del gobierno y resistencia.'],
 {'propiedad':'Sentido amplio de vidas, libertades y bienes; también teoría específica de apropiación.','consentimiento':'Fuente de autoridad política, con problemas entre consentimiento expreso y tácito.','fiducia':'Gobierno como poder confiado para fines determinados.','prerrogativa':'Discreción ejecutiva para bien público donde la ley no alcanza.','resistencia':'Recurso del pueblo cuando el gobierno destruye la confianza.'},
 ['Propiedad, dinero y desigualdad.','Colonialismo y apropiación de tierras.','Tolerancia y sus límites.','Individualismo versus republicanismo en Locke.'],
 ['Liberalismo.','Constitucionalismo estadounidense.','Teorías de derechos y gobierno limitado.'],
 ['Distinguir sociedad y gobierno.','Explicar por qué el legislativo es supremo pero no soberano absoluto.','Relacionar propiedad y consentimiento.']),
 montesquieu:DG(
 ['Montesquieu propone una ciencia comparativa de las leyes. Una ley no puede entenderse aisladamente: clima, economía, costumbres, religión, tamaño del territorio y estructura social forman relaciones que condicionan qué instituciones son posibles.','Su concepto de libertad política no equivale a hacer lo que se quiere; depende de seguridad y moderación. La famosa separación de poderes es parte de una arquitectura más amplia de frenos, cuerpos intermedios y distribución social del poder.'],
 ['Libros I–VIII: naturaleza y principio de gobiernos.','Libros XI–XIII: libertad política, constitución inglesa y fiscalidad.','Libros XIV–XXVI: clima, comercio, costumbres y religión.','Libros XXVI–XXXI: relaciones entre órdenes jurídicos e historia.'],
 {'naturaleza/principio':'Estructura de un régimen y pasión que lo pone en movimiento.','moderación':'Condición institucional que evita concentración y abuso.','libertad política':'Seguridad producida por un orden donde el poder frena al poder.','espíritu general':'Configuración histórica de múltiples causas sociales e institucionales.'},
 ['¿Separación o balance de poderes?','Determinismo climático versus explicación multicausal.','Montesquieu republicano, liberal o aristocrático.'],
 ['Constitucionalismo moderno.','Federalist.','Tocqueville y sociología política comparada.'],
 ['No reducir la obra a tres poderes.','Explicar naturaleza/principio.','Vincular libertad con moderación.']),
 rousseau:DG(
 ['Rousseau formula una paradoja decisiva: construir un orden en el que cada uno obedezca a todos sin obedecer a una voluntad particular. La solución es la soberanía popular expresada en la voluntad general, que se dirige al interés común y se formula en leyes generales.','El soberano no es el gobierno. El pueblo legisla; el gobierno ejecuta y administra. Esta distinción permite comprender por qué Rousseau puede defender soberanía popular radical y, al mismo tiempo, admitir diversas formas de gobierno.'],
 ['Libro I: libertad, pacto y cuerpo político.','Libro II: soberanía, voluntad general, ley y legislador.','Libro III: gobierno, formas y degeneración.','Libro IV: asambleas, sufragio, tribunado, censura y religión civil.'],
 {'voluntad general':'Voluntad dirigida a lo común; no suma estadística de preferencias.','soberanía':'Poder legislativo del pueblo, inalienable e indivisible.','ley':'Acto general en origen y objeto.','gobierno':'Cuerpo intermediario encargado de ejecución.','libertad civil':'Autonomía política dentro de un orden de leyes que uno integra como ciudadano.'},
 ['Voluntad general y riesgo totalitario.','Escala territorial y condiciones sociales de la república.','Legislador y paradoja fundacional.','Religión civil y pluralismo.'],
 ['Revolución francesa.','Republicanismo y democracia directa.','Idealismo alemán.'],
 ['Distinguir voluntad general de voluntad de todos.','Distinguir soberano de gobierno.','Explicar la transformación de libertad natural en civil.'],
 ['Joshua Cohen, trabajos sobre Rousseau y democracia.','Judith Shklar, estudios sobre Rousseau.']),
 federalist:DG(
 ['El Federalista defiende la Constitución estadounidense combinando diagnóstico de facciones, teoría de representación y arquitectura institucional. Madison parte de que las causas de la facción no pueden eliminarse sin destruir libertad; por ello deben controlarse sus efectos.','La república extensa, el federalismo y la separación funcional de poderes permiten multiplicar intereses y hacer más costosa la captura estable del gobierno. El diseño constitucional usa la ambición para controlar la ambición.'],
 ['Federalist 10: facción y república extensa.','Federalist 39: carácter republicano y federal.','Federalist 47–51: separación, controles y ambición.','Federalist 70: energía del ejecutivo.','Federalist 78: poder judicial.'],
 {'facción':'Grupo impulsado por pasión o interés adverso a derechos de otros o interés agregado.','república extensa':'Escala que multiplica intereses y dificulta mayorías facciosas estables.','checks and balances':'Controles institucionales derivados de distribución de funciones y ambiciones.','representación':'Filtro y mecanismo de extensión del gobierno popular.'},
 ['¿Pluralismo o elitismo?','Qué significa “república” frente a democracia.','Federalismo dual, nacionalismo y soberanía popular.'],
 ['Constitucionalismo presidencial.','Pluralismo estadounidense.','Teoría institucional contemporánea.'],
 ['Saber explicar Federalist 10 y 51.','Relacionar diagnóstico antropológico con diseño institucional.']),
 burke:DG(
 ['Burke critica la idea de que una sociedad pueda reconstruirse enteramente desde principios abstractos. Las instituciones contienen saber histórico no reducible a diseño racional y conectan generaciones mediante herencia, costumbre y responsabilidad.','Su defensa de tradición no implica inmovilismo: la prudencia política admite reforma, pero exige distinguir reforma de destrucción y considerar consecuencias no intencionadas.'],
 ['Crítica a derechos abstractos desvinculados de prácticas.','Sociedad como asociación intergeneracional.','Cuerpos intermedios y representación.','Revolución, violencia y prudencia.'],
 {'prudencia':'Juicio político sensible a circunstancias y consecuencias.','tradición':'Depósito histórico de prácticas y saberes, no mera antigüedad.','prejuicio':'Disposición heredada que puede condensar experiencia moral.','representación':'Juicio independiente del representante, no simple mandato imperativo.'},
 ['Burke liberal whig versus fundador del conservadurismo.','Reforma y tradición.','Crítica del racionalismo y legitimidad del orden heredado.'],
 ['Conservadurismo moderno.','Debates sobre representación trustee.'],
 ['No reducirlo a “estar contra toda revolución”.','Comparar prudencia con racionalismo constitucional.']),
 hegel:DG(
 ['La Filosofía del derecho entiende la libertad como algo que debe objetivarse en instituciones. Una voluntad aislada puede ser formalmente libre, pero sólo alcanza libertad concreta cuando participa en prácticas de reconocimiento, derechos, familia, sociedad civil y Estado.','La sociedad civil es un descubrimiento decisivo: un ámbito moderno de necesidades, mercado, corporaciones y administración que no coincide con el Estado. Sus desigualdades y conflictos requieren mediaciones políticas.'],
 ['Derecho abstracto: propiedad, contrato e injusticia.','Moralidad: intención, bienestar y bien.','Eticidad: familia.','Sociedad civil: sistema de necesidades, administración de justicia, policía y corporación.','Estado: constitución, poderes y relaciones exteriores.'],
 {'libertad concreta':'Libertad realizada en instituciones racionales y reconocimiento mutuo.','eticidad':'Orden de prácticas e instituciones donde libertad se vuelve habitual.','sociedad civil':'Sistema moderno de necesidades e intereses particulares mediado jurídicamente.','Estado':'Unidad política que articula universal y particular sin ser mera suma de individuos.'},
 ['¿Hegel justifica el Estado prusiano?','Estado racional versus Estado empírico.','Corporaciones, pobreza y límites de sociedad civil.','Reconocimiento como concepto político.'],
 ['Marx.','Teoría del reconocimiento.','Comunitarismo y republicanismo institucional.'],
 ['Distinguir sociedad civil de Estado.','Explicar por qué libertad necesita instituciones.','Comprender la secuencia derecho–moralidad–eticidad.'],
 ['Shlomo Avineri, *Hegel’s Theory of the Modern State*.','Allen Wood, estudios sobre Hegel político.']),
 tocqueville:DG(
 ['Tocqueville trata democracia primero como condición social: una tendencia histórica hacia igualdad de condiciones. El problema político es qué instituciones y costumbres pueden hacer compatible esa igualdad con libertad.','Sus riesgos centrales son tiranía de la mayoría, individualismo y centralización administrativa. Asociaciones, autogobierno local, prensa, religión y hábitos cívicos funcionan como contrapesos.'],
 ['Igualdad de condiciones como hecho generador.','Instituciones federales y locales.','Asociaciones y costumbres.','Tiranía de la mayoría.','Individualismo y despotismo suave.'],
 {'igualdad de condiciones':'Tendencia estructural que redefine expectativas sociales y políticas.','mores/moeurs':'Costumbres y hábitos que sostienen instituciones.','asociación':'Escuela práctica de cooperación y límite a aislamiento.','despotismo suave':'Dominación tutelar compatible con igualdad y vida privada.'},
 ['¿Tocqueville es liberal, republicano o aristocrático?','Raza, esclavitud y colonialismo en su análisis.','Democracia como destino histórico y agencia política.'],
 ['Sociología política.','Pluralismo y sociedad civil.','Teoría de democracia liberal.'],
 ['No reducir democracia a elecciones.','Explicar el vínculo igualdad–individualismo–centralización.']),
 manifesto:DG(
 ['El Manifiesto combina historia, teoría social y intervención política. La burguesía aparece como fuerza revolucionaria que universaliza mercado y transforma relaciones sociales; al mismo tiempo produce proletarización y crisis recurrentes.','La lucha de clases no funciona como una fórmula monocausal: el texto intenta identificar una estructura de antagonismo capaz de producir organización política transnacional.'],
 ['Burgueses y proletarios: dinámica histórica del capitalismo.','Proletarios y comunistas: relación entre movimiento y programa.','Crítica de socialismos rivales.','Posición de comunistas ante partidos existentes.'],
 {'burguesía':'Clase que controla medios de producción y revoluciona continuamente relaciones sociales.','proletariado':'Clase desposeída que vende fuerza de trabajo y puede organizarse políticamente.','lucha de clases':'Conflicto estructural que adquiere formas históricas específicas.','internacionalismo':'Escala política producida por universalización capitalista.'},
 ['Determinismo histórico versus estrategia.','Universalidad europea y expansión colonial.','Clase y otras formas de dominación.'],
 ['Partidos socialistas y comunistas.','Marxismos del siglo XX.','Teoría crítica del capitalismo.'],
 ['Distinguir descripción histórica de programa político.','Ubicar papel revolucionario de burguesía antes de su crítica.']),
 marx18:DG(
 ['El 18 Brumario es uno de los textos más ricos de Marx para la autonomía relativa de la política. Las clases no aparecen directamente en escena: necesitan organización, representación, lenguajes, partidos y formas estatales.','El bonapartismo muestra que un Ejecutivo puede adquirir autonomía frente a fracciones de clase al presentarse como representante de la nación y apoyarse en un aparato burocrático-militar.'],
 ['Herencia histórica y repetición.','Fracciones de clase y coaliciones.','Representación política e ideología.','Campesinado parcelario y problema de representación.','Bonapartismo y aparato estatal.'],
 {'representación':'Proceso por el que intereses sociales son articulados políticamente, no simple reflejo.','bonapartismo':'Autonomización del Ejecutivo en una coyuntura de bloqueo social.','Estado':'Aparato históricamente sedimentado con capacidades propias.','coyuntura':'Configuración contingente de fuerzas y temporalidades.'},
 ['¿Autonomía relativa del Estado?','Clase en sí, representación y organización.','Bonapartismo como concepto exportable a otros contextos.'],
 ['Gramsci.','Poulantzas.','Sociología histórica del Estado y populismo.'],
 ['Usarlo para corregir lecturas economicistas de Marx.','Recordar campesinado, representación y burocracia.']),
 mill:DG(
 ['Mill defiende la individualidad como componente del bienestar humano y social. El principio de daño limita coerción jurídica y también presión social, porque una opinión mayoritaria puede ser tan conformista como una ley.','La libertad de expresión no se justifica sólo por derechos subjetivos: incluso opiniones falsas pueden obligar a comprender mejor verdades recibidas.'],
 ['Principio de daño.','Libertad de pensamiento y discusión.','Individualidad y experimentos de vida.','Límites de autoridad social sobre el individuo.'],
 {'daño':'Razón principal para coerción legítima sobre adultos competentes.','individualidad':'Desarrollo de capacidades mediante elección y experimentación.','opinión pública':'Fuente de coerción social distinta del Estado.','libertad de expresión':'Institución epistémica y moral para evitar dogmatismo.'},
 ['Definir daño y distinguirlo de ofensa.','Paternalismo y excepciones.','Colonialismo y límites del universalismo milliano.'],
 ['Liberalismo contemporáneo.','Debates sobre libertad de expresión y paternalismo.'],
 ['Saber formular con precisión el principio de daño.','Explicar la defensa epistémica de la expresión.']),
 weber:DG(
 ['Weber define el Estado moderno por la pretensión exitosa de monopolizar el uso legítimo de la violencia física dentro de un territorio. La política es la lucha por participar en poder o influir en su distribución.','La conferencia contrapone ética de convicción y ética de responsabilidad, pero no las presenta como opciones mutuamente excluyentes. El político maduro necesita convicciones y capacidad de asumir consecuencias previsibles de sus actos.'],
 ['Estado y violencia legítima.','Tipos de políticos profesionales.','Partidos, liderazgo y burocracia.','Ética de convicción y responsabilidad.','Pasión, responsabilidad y mesura.'],
 {'Estado':'Institución que reclama con éxito monopolio de violencia legítima en territorio.','legitimidad':'Creencia en validez de formas de dominación.','responsabilidad':'Atención a consecuencias de la acción política.','burocracia':'Forma racionalizada de administración que puede adquirir autonomía.'},
 ['¿Realismo weberiano?','Liderazgo plebiscitario y democracia.','Relación entre valores y ciencia.'],
 ['Sociología del Estado.','Realismo político.','Teorías de liderazgo y burocracia.'],
 ['No confundir legitimidad con justicia.','No presentar las dos éticas como elección binaria.']),
 gramsci:DG(
 ['Los Cuadernos reformulan el problema de poder en sociedades donde el Estado no puede comprenderse sólo como coerción. Hegemonía designa una dirección intelectual y moral que articula alianzas, instituciones y sentido común.','El “Estado integral” combina sociedad política y sociedad civil. Esto desplaza la estrategia desde una toma instantánea del aparato coercitivo hacia una guerra de posición en múltiples instituciones.'],
 ['Hegemonía y dirección.','Sociedad civil y Estado integral.','Intelectuales y organización.','Guerra de maniobra / guerra de posición.','Sentido común, filosofía de la praxis y bloque histórico.'],
 {'hegemonía':'Dirección capaz de construir consentimiento activo alrededor de un proyecto.','Estado integral':'Unidad ampliada de coerción y consenso.','intelectuales orgánicos':'Funciones de organización y elaboración vinculadas a grupos sociales.','guerra de posición':'Lucha prolongada por posiciones en sociedades civiles complejas.','bloque histórico':'Articulación entre fuerzas materiales, instituciones e ideas.'},
 ['Concepto cambiante de hegemonía en los Cuadernos.','Sociedad civil como terreno de libertad o dominación.','Partido, príncipe moderno y organización.'],
 ['Eurocomunismo.','Cultural studies.','Laclau y Mouffe.','Teoría latinoamericana de hegemonía y populismo.'],
 ['Distinguir hegemonía de propaganda.','Explicar Estado integral.','Relacionar estrategia con estructura de sociedad civil.']),
 schmitt:DG(
 ['Schmitt busca un criterio específico de lo político: la distinción amigo/enemigo. No significa que toda política sea guerra efectiva, sino que existe la posibilidad extrema de conflicto entre colectividades.','Su crítica al liberalismo apunta a la ilusión de neutralizar política mediante discusión, economía o derecho. La soberanía reaparece en la decisión sobre situaciones excepcionales donde las normas no determinan por sí solas qué hacer.'],
 ['Concepto de lo político y amigo/enemigo.','Unidad política y posibilidad de guerra.','Crítica de neutralización liberal.','En Teología política: soberano y excepción.'],
 {'amigo/enemigo':'Criterio de intensidad política entre colectividades.','decisión':'Momento que no puede deducirse completamente de norma general.','excepción':'Situación límite que revela quién puede suspender o interpretar el orden.','soberanía':'Capacidad de decidir sobre excepción.'},
 ['Schmitt y su compromiso nazi.','Descripción de política versus prescripción autoritaria.','Liberalismo, pluralismo y enemigo interno.'],
 ['Agamben y teoría de excepción.','Mouffe y agonismo.','Debates sobre constitucionalismo de emergencia.'],
 ['No reducir amigo/enemigo a enemistad personal.','Relacionar excepción con límites del normativismo.']),
 arendt:DG(
 ['La condición humana distingue labor, trabajo y acción. La política aparece con la acción: actuar y hablar ante otros en un espacio de pluralidad donde nadie controla completamente consecuencias.','Arendt recupera una idea no instrumental de libertad. Ser libre no es sólo estar protegido de interferencias, sino poder iniciar algo nuevo con otros y aparecer públicamente.'],
 ['Vita activa: labor, trabajo y acción.','Mundo común y espacio de aparición.','Pluralidad, natalidad y acción.','Poder, promesa y perdón.','Crítica de la sociedad moderna y del predominio de lo social.'],
 {'acción':'Actividad entre plurales que inicia procesos imprevisibles.','pluralidad':'Condición de igualdad y diferencia entre actores.','natalidad':'Capacidad humana de comenzar algo nuevo.','poder':'Surge cuando personas actúan concertadamente; no equivale a violencia.','mundo común':'Espacio duradero de objetos, instituciones y significados compartidos.'},
 ['Política versus “lo social”.','Idealización de la polis griega.','Acción, instituciones y estabilidad.','Poder y violencia.'],
 ['Republicanismo contemporáneo.','Teorías de esfera pública.','Estudios sobre revolución y totalitarismo.'],
 ['Distinguir labor/trabajo/acción.','Distinguir poder de violencia.','Relacionar libertad con natalidad.']),
 rawls:DG(
 ['Rawls intenta formular principios de justicia para la estructura básica de una sociedad democrática. La posición original y el velo de ignorancia son dispositivos de representación: modelan condiciones equitativas para elegir principios sin conocer ventajas contingentes.','Los dos principios protegen libertades básicas y regulan desigualdades mediante igualdad justa de oportunidades y principio de diferencia. La prioridad de las libertades impide intercambiarlas por ganancias agregadas.'],
 ['Circunstancias de justicia y posición original.','Velo de ignorancia.','Dos principios de justicia y orden lexical.','Bienes primarios y estructura básica.','Instituciones, estabilidad y sentido de justicia.'],
 {'posición original':'Situación hipotética que representa imparcialidad entre ciudadanos.','velo de ignorancia':'Restricción de información sobre posición social, talentos y concepciones del bien.','principio de diferencia':'Desigualdades sólo justificadas si mejoran expectativas de los menos aventajados.','estructura básica':'Principales instituciones que distribuyen derechos, oportunidades y ventajas.','justicia como equidad':'Concepción liberal igualitaria basada en cooperación entre libres e iguales.'},
 ['Crítica libertaria de Nozick.','Crítica comunitarista.','Feminismo y exclusión de familia de la estructura básica.','Capacidades versus bienes primarios.'],
 ['Renovación de teoría normativa.','Liberalismo político.','Debates sobre igualdad, justicia global y democracia.'],
 ['Memorizar los principios con prioridad correcta.','Entender posición original como representación, no contrato histórico.','Explicar por qué utilitarismo es el adversario principal.'],
 ['Samuel Freeman, trabajos sobre Rawls.','Thomas Pogge, estudios sobre justicia rawlsiana.']),
 foucault:DG(
 ['Vigilar y castigar reconstruye el pasaje desde el suplicio público hacia formas disciplinarias de poder. El cambio no significa simplemente humanización: el poder se vuelve más continuo, detallado y productivo.','La disciplina produce cuerpos útiles mediante vigilancia, examen, normalización y organización del espacio y tiempo. El panoptismo es un diagrama de poder que hace que la visibilidad funcione como mecanismo de autocontrol.'],
 ['Suplicio y poder soberano.','Reforma penal y nueva economía del castigo.','Disciplina: cuerpos dóciles, horarios, ejercicios.','Panoptismo y examen.','Prisión y producción de delincuencia.'],
 {'disciplina':'Conjunto de técnicas que individualizan, adiestran y normalizan cuerpos.','poder-saber':'Relación por la que conocimiento y poder se producen mutuamente.','normalización':'Comparación de individuos con estándares y distribución alrededor de una norma.','panoptismo':'Principio de visibilidad asimétrica que automatiza vigilancia.','genealogía':'Historia de prácticas contingentes sin origen unitario ni progreso lineal.'},
 ['¿Foucault elimina agencia y resistencia?','Poder productivo versus represivo.','Continuidades entre soberanía, disciplina y biopolítica.'],
 ['Teoría crítica, feminismo y estudios de gubernamentalidad.','Butler, Agamben, teoría carcelaria.'],
 ['No decir que poder es una cosa poseída por el Estado.','Explicar examen como combinación saber/poder.','Distinguir disciplina de mera represión.']),
 pateman:DG(
 ['Pateman muestra que el contractualismo moderno puede presentar libertad universal mientras presupone relaciones patriarcales. El “contrato sexual” nombra la dimensión invisibilizada mediante la cual la ciudadanía masculina y la subordinación femenina se constituyen conjuntamente.','La crítica no consiste en pedir simplemente que las mujeres ingresen al contrato existente, sino en revisar categorías de individuo, propiedad en la persona, trabajo y esfera privada.'],
 ['Crítica del relato clásico del contrato.','Matrimonio y derecho sexual masculino.','Trabajo, propiedad en la persona y ciudadanía.','Patriarcado moderno como relación contractual.'],
 {'contrato sexual':'Estructura patriarcal presupuesta por contratos políticos y privados.','patriarcado':'Orden moderno de subordinación que no desaparece con igualdad formal.','esfera privada':'Ámbito políticamente estructurado, no exterior al poder.','ciudadanía':'Estatus históricamente masculinizado.'},
 ['Universalismo feminista y diferencia.','Trabajo sexual, matrimonio y consentimiento.','Pateman frente a Rawls y contractualismo contemporáneo.'],
 ['Feminismo político.','Estudios de ciudadanía y cuidado.'],
 ['Usar el texto para interrogar supuestos del contrato social.','Explicar por qué privado/público es una división política.']),
 habermas:DG(
 ['Facticidad y validez intenta mostrar cómo el derecho moderno puede ser simultáneamente coercitivo y legítimo. La respuesta está en procedimientos democráticos mediante los cuales destinatarios de normas pueden considerarse también sus autores.','Autonomía privada y pública son cooriginarias: derechos individuales hacen posible participación democrática, y la participación democrática especifica y protege derechos.'],
 ['Tensión entre facticidad y validez.','Sistema de derechos.','Principio discursivo y democracia.','Parlamento, tribunales y esfera pública.','Circulación de poder comunicativo.'],
 {'acción comunicativa':'Coordinación orientada al entendimiento mediante razones.','cooriginalidad':'Interdependencia entre derechos privados y autonomía pública.','esfera pública':'Red de comunicación que detecta problemas y forma opinión.','legitimidad':'Aceptabilidad de normas generadas bajo procedimientos discursivos inclusivos.'},
 ['Idealización deliberativa y desigualdad real.','Poder, conflicto y exclusión en esfera pública.','Tribunales constitucionales y democracia.'],
 ['Democracia deliberativa.','Constitucionalismo discursivo.','Debates con agonismo y republicanismo.'],
 ['Explicar cooriginalidad.','No equiparar deliberación con consenso efectivo permanente.']),
 pettit:DG(
 ['Pettit reconstruye libertad republicana como no-dominación. Una persona puede no sufrir interferencia y, sin embargo, ser no libre si vive a merced de un poder capaz de intervenir arbitrariamente.','La respuesta institucional es un orden donde poder esté controlado, contestable y orientado por intereses comunes. El republicanismo no busca ausencia total de interferencia, sino interferencia no arbitraria bajo control público.'],
 ['Crítica a libertad como no-interferencia.','Dominación y dependencia.','Instituciones republicanas.','Contestación y control.'],
 {'no-dominación':'No estar sujeto a capacidad de interferencia arbitraria ajena.','arbitrariedad':'Poder no controlado por intereses y procedimientos compartidos.','contestabilidad':'Capacidad efectiva de cuestionar decisiones públicas.','república':'Orden diseñado para reducir dependencias arbitrarias públicas y privadas.'},
 ['Diferencia con Berlin.','¿Puede existir interferencia intensa sin dominación?','Medición y alcance de dominación estructural.'],
 ['Neo-republicanismo.','Teoría democrática y laboral.'],
 ['Usar el ejemplo del esclavo con amo benevolente.','Distinguir interferencia de dominación.']),
 bolivar-j:DG(
 ['La Carta de Jamaica interpreta la crisis imperial y plantea el problema de construir nuevas unidades políticas en sociedades atravesadas por guerra, fragmentación territorial y herencias coloniales.','Bolívar combina universalismo republicano con fuerte atención a condiciones locales. No supone que una forma constitucional pueda copiarse sin mediaciones entre geografía, historia y estructura social.'],
 ['Diagnóstico del dominio español.','Diversidad regional y dificultad de unidad.','Formas de gobierno posibles.','Proyección continental e independencia.'],
 {'independencia':'Ruptura de subordinación colonial y problema de construcción de autoridad nueva.','unidad americana':'Horizonte político condicionado por fragmentación territorial.','constitución':'Forma que debe adaptarse a condiciones históricas.','soberanía':'Capacidad efectiva de autodeterminación postimperial.'},
 ['Bolívar republicano y centralista.','Unidad latinoamericana versus pluralidad regional.','Uso posterior del bolivarianismo.'],
 ['Republicanismos hispanoamericanos.','Nacionalismos y latinoamericanismo.'],
 ['Leer la Carta como diagnóstico geopolítico y constitucional.','Evitar convertirla en programa unitario cerrado.']),
 marti:DG(
 ['Nuestra América critica gobiernos que importan categorías e instituciones sin conocer las sociedades que pretenden gobernar. El principio “conocer el país y gobernarlo conforme al conocimiento” convierte epistemología y política en un mismo problema.','Martí vincula emancipación cultural, república y resistencia frente a nuevas formas de imperialismo. La independencia formal es insuficiente si persisten jerarquías sociales y subordinación intelectual.'],
 ['Crítica del “aldeano vanidoso”.','Gobierno situado y conocimiento social.','Raza, pueblo y república.','Advertencia frente al expansionismo estadounidense.'],
 {'nuestra América':'Comunidad histórica y política diferenciada de modelos metropolitanos.','pueblo':'Pluralidad social que debe ser conocida y articulada, no borrada.','antiimperialismo':'Defensa de autonomía frente a nuevas formas de dominación.','gobierno situado':'Instituciones pensadas desde realidad histórica propia.'},
 ['Universalismo y particularidad americana.','Raza y mestizaje.','Martí como antecedente de decolonialidad.'],
 ['Latinoamericanismo.','Pensamiento antiimperialista.'],
 ['Relacionar conocimiento y gobierno.','Distinguir independencia política de emancipación cultural.']),
 mariategui:DG(
 ['Los Siete ensayos muestran un marxismo que rechaza la copia mecánica de secuencias europeas. El problema indígena se vincula con estructura agraria, propiedad de la tierra y supervivencia de relaciones coloniales.','Mariátegui convierte traducción teórica en método: categorías generales se usan sólo si son capaces de reconstruir particularidades históricas peruanas y potencialidades políticas concretas.'],
 ['Esquema de evolución económica.','Problema indígena y problema de la tierra.','Educación, religión, regionalismo y centralismo.','Literatura como campo de formación nacional.'],
 {'indigenismo':'Problema político-material ligado a tierra y poder, no sólo identidad cultural.','tierra':'Núcleo económico y político de subordinación indígena.','marxismo situado':'Uso creativo de categorías universales en una formación específica.','mito':'Dimensión movilizadora de proyectos colectivos.'},
 ['Mariátegui marxista heterodoxo o romántico.','Comunidad indígena y socialismo.','Universalidad del marxismo y especificidad latinoamericana.'],
 ['Aricó.','Zavaleta.','Marxismos latinoamericanos y decoloniales.'],
 ['Explicar por qué problema indígena = problema de tierra.','Usarlo como ejemplo de traducción no eurocéntrica de teoría.']),
 peron:DG(
 ['La comunidad organizada intenta formular una filosofía social que supere tanto individualismo liberal como colectivismo totalizante. La persona se realiza en comunidad, pero la comunidad sólo es legítima si no absorbe la dignidad individual.','Organización no significa simple verticalidad: es la forma institucional mediante la cual intereses y funciones sociales se articulan en una totalidad orientada a justicia social.'],
 ['Crisis del individualismo moderno.','Persona y comunidad.','Libertad, justicia y función social.','Organización como mediación política.'],
 {'comunidad organizada':'Orden social donde individuo y totalidad se articulan institucionalmente.','justicia social':'Principio de integración material y moral de la comunidad.','organización':'Mediación entre agregación individual y absorción colectivista.','persona':'Sujeto que conserva dignidad dentro de la comunidad.'},
 ['Relación con corporativismo, comunitarismo y doctrina social católica.','Texto filosófico versus doctrina partidaria.','Continuidades entre Comunidad organizada y Conducción política.'],
 ['Teoría política peronista.','Debates argentinos sobre comunidad, organización y populismo.'],
 ['Distinguir comunidad de colectivismo.','Analizar organización como concepto político, no sólo partidario.']),
 prebisch:DG(
 ['Prebisch desplaza la economía política latinoamericana desde supuestos de intercambio simétrico hacia una estructura centro–periferia. La posición periférica condiciona difusión técnica, precios, restricción externa y posibilidades de desarrollo.','La consecuencia política es decisiva: el desarrollo requiere capacidades estatales, planificación e industrialización, no simple adaptación al mercado mundial.'],
 ['Centro y periferia.','Deterioro relativo de términos de intercambio.','Industrialización.','Estado, productividad y restricción externa.'],
 {'centro-periferia':'Estructura desigual de difusión tecnológica y especialización internacional.','desarrollo':'Transformación productiva, no mero crecimiento cuantitativo.','Estado':'Agente capaz de modificar estructura productiva.','dependencia externa':'Restricciones derivadas de inserción asimétrica internacional.'},
 ['Alcance empírico del deterioro de términos de intercambio.','Estructuralismo versus dependentismo.','Industrialización y sus límites.'],
 ['CEPAL.','Teoría de dependencia.','Economía política del desarrollo.'],
 ['Entender centro/periferia como relación estructural.','Relacionarlo con Cardoso-Faletto y dependentismo.']),
 freire:DG(
 ['Freire concibe educación como relación política. La pedagogía “bancaria” trata a estudiantes como recipientes pasivos y reproduce jerarquías; la educación problematizadora parte del diálogo y de la capacidad de nombrar el mundo.','Concientización no significa recibir una doctrina correcta, sino desarrollar una praxis en la que reflexión y acción se transforman mutuamente.'],
 ['Oprimidos y pedagogía de liberación.','Crítica de educación bancaria.','Diálogo y problematización.','Praxis, concientización y transformación.'],
 {'opresión':'Relación que limita capacidad de sujetos para actuar como agentes.','diálogo':'Práctica recíproca de conocimiento y transformación.','praxis':'Unidad de reflexión y acción.','concientización':'Proceso crítico de comprensión de condiciones y capacidad de intervención.'},
 ['Pedagogía y vanguardismo.','Humanismo, cristianismo y marxismo.','Aplicaciones fuera de educación formal.'],
 ['Pedagogía crítica.','Teología de liberación.','Movimientos sociales latinoamericanos.'],
 ['No confundir diálogo con ausencia de conflicto.','Explicar praxis como unidad, no sucesión de teoría y práctica.']),
 cardoso:DG(
 ['Cardoso y Faletto rechazan explicar dependencia sólo como imposición externa. Las estructuras internacionales operan mediante coaliciones internas, clases, Estados y estrategias de desarrollo.','Esto permite hablar de desarrollo dependiente: puede existir industrialización y crecimiento sin desaparición de dependencia, porque cambian las formas de articulación entre capital interno, externo y Estado.'],
 ['Crítica del economicismo externo.','Situaciones históricas de dependencia.','Clases y alianzas internas.','Estado, inversión extranjera y desarrollo asociado.'],
 {'dependencia':'Relación histórica mediada por estructuras políticas internas y vínculos externos.','desarrollo dependiente':'Crecimiento compatible con reproducción de asimetrías.','alianzas de clase':'Mediaciones políticas que dan forma concreta a dependencia.','Estado':'Actor que organiza modalidades nacionales de inserción.'},
 ['Diferencias con Frank y dependentismo radical.','Capacidad de desarrollo bajo dependencia.','Actualidad del marco frente a globalización.'],
 ['Sociología histórica latinoamericana.','Economía política internacional.'],
 ['Distinguir dependencia como situación concreta de dependencia como etiqueta general.']),
 zavaleta:DG(
 ['Zavaleta parte de que ciertas sociedades no pueden comprenderse mediante modelos de homogeneidad social. “Sociedad abigarrada” nombra la coexistencia desigual de temporalidades, formas productivas, comunidades y estructuras políticas.','El conocimiento político tiene entonces un problema epistemológico: el Estado no refleja transparentemente la sociedad, y momentos de crisis pueden producir una “disponibilidad” cognitiva excepcional para comprenderla.'],
 ['Formación social abigarrada.','Masa y momento constitutivo.','Estado y nación.','Lo nacional-popular como articulación política.'],
 {'abigarramiento':'Coexistencia no integrada de formas sociales y temporalidades.','masa':'Forma de irrupción colectiva que transforma capacidad política.','momento constitutivo':'Acontecimiento que reorganiza relaciones duraderas entre Estado y sociedad.','nacional-popular':'Proceso conflictivo de articulación de sujetos y construcción nacional.'},
 ['Zavaleta marxista o pensador nacional-popular.','Comparabilidad fuera de Bolivia.','Crisis como método de conocimiento.'],
 ['García Linera.','Teoría latinoamericana del Estado y heterogeneidad.'],
 ['Usar abigarramiento como categoría histórica, no sinónimo de diversidad.','Relacionar crisis y conocimiento.']),
 quijano:DG(
 ['Quijano sostiene que la desaparición formal del colonialismo no elimina una matriz de poder que clasifica poblaciones racialmente, organiza trabajo y jerarquiza formas de conocimiento. Esa persistencia es la colonialidad del poder.','Modernidad y colonialidad no son etapas separadas: se constituyen conjuntamente a escala mundial. Por eso la crítica al eurocentrismo es epistemológica y política.'],
 ['Formación histórica de clasificación racial.','Articulación de formas de trabajo en capitalismo mundial.','Eurocentrismo como perspectiva de conocimiento.','América Latina como lugar constitutivo de modernidad.'],
 {'colonialidad':'Persistencia estructural de relaciones coloniales después de independencia formal.','raza':'Clasificación social moderna producida en expansión colonial.','eurocentrismo':'Perspectiva que universaliza una experiencia histórica particular.','modernidad':'Proceso mundial inseparable de conquista y clasificación colonial.'},
 ['Relación entre colonialidad y capitalismo.','Uso histórico del concepto de raza.','Debate decolonial y críticas poscoloniales.'],
 ['Giro decolonial.','Dussel, Mignolo y debates latinoamericanos sobre modernidad.'],
 ['Distinguir colonialismo de colonialidad.','Explicar por qué Europa no es un origen aislado de modernidad.']),
 dussel:DG(
 ['Las 20 tesis proponen reconstruir política desde la potentia de la comunidad: la capacidad originaria de un pueblo para producir y reproducir vida común. Las instituciones son potestas, poder delegado que puede servir o fetichizarse.','El poder obediencial invierte la imagen del mando: una autoridad legítima ejerce poder delegado al servicio de la comunidad y especialmente atendiendo a quienes sufren exclusión del orden vigente.'],
 ['Potentia y potestas.','Poder obediencial.','Instituciones y fetichización.','Pueblo, víctimas y transformación.','Principios material, democrático y de factibilidad.'],
 {'potentia':'Capacidad política originaria de la comunidad.','potestas':'Institucionalización delegada de esa capacidad.','fetichización':'Inversión por la cual la institución se presenta como fuente autónoma de poder.','poder obediencial':'Ejercicio de autoridad como servicio delegado.','pueblo':'Bloque histórico emergente frente a exclusión y crisis institucional.'},
 ['Populismo y pueblo.','Normatividad material versus procedimental.','Relación con Levinas, Marx y filosofía de liberación.'],
 ['Filosofía política de liberación.','Teoría decolonial y debates latinoamericanos.'],
 ['Distinguir potentia/potestas.','Explicar fetichización institucional.']),
 laclau:DG(
 ['La razón populista analiza “pueblo” no como grupo sociológico dado, sino como efecto de articulación. Demandas inicialmente diferentes pueden formar una cadena de equivalencias cuando perciben un adversario o límite común.','Un significante vacío —“pueblo”, “justicia”, “cambio”— puede representar esa pluralidad sin absorber completamente sus diferencias. Populismo es entonces una lógica política de construcción de fronteras, no una ideología con contenido fijo.'],
 ['Demandas democráticas y populares.','Lógica de diferencia y equivalencia.','Frontera antagónica.','Significante vacío y representación.','Afecto, identificación y construcción del pueblo.'],
 {'demanda':'Unidad mínima que puede permanecer diferencial o articularse equivalencialmente.','cadena de equivalencias':'Articulación de demandas diversas por oposición a un límite común.','significante vacío':'Nombre que representa una totalidad imposible de cerrar plenamente.','hegemonía':'Operación por la que una particularidad asume representación más universal.','pueblo':'Resultado político de una articulación, no esencia previa.'},
 ['Populismo como forma o contenido.','Instituciones y frontera populista.','Afecto y liderazgo.','Críticas liberales y marxistas.'],
 ['Estudios contemporáneos de populismo.','Mouffe y democracia agonista.','Teoría política latinoamericana.'],
 ['No definir populismo por demagogia.','Explicar demanda → equivalencia → frontera → significante.','Relacionar con Gramsci sin identificarlos.'])
};

function defaultStudyGuide(w){
 const cs=w.concepts||[];
 return {
  summary:[w.thesis,`La obra se comprende mejor si se distingue el problema histórico que enfrenta —${w.problem.replace(/^¿|\?$/g,'')}— de los usos posteriores que la convirtieron en una referencia de ${w.trad}.`],
  architecture:[`Planteo del problema: ${w.problem}`,`Desarrollo de una respuesta organizada alrededor de ${cs.slice(0,3).join(', ')}.`,`Consecuencias para instituciones, autoridad o formas de vida política.`,`Recepciones posteriores que modifican el sentido original del texto.`],
  keys:Object.fromEntries(cs.map(c=>[c,`Concepto central en la obra; conviene precisar su significado histórico y evitar equipararlo automáticamente con su uso contemporáneo.`])),
  debates:[`Cómo relacionar el contexto de ${w.date} con pretensiones más generales del argumento.`,`Qué aspectos son descriptivos, normativos o estratégicos.`,`Hasta dónde puede trasladarse su vocabulario fuera de ${w.trad}.`],
  reception:[`Recepción dentro de ${w.trad}.`,`Relecturas contemporáneas en teoría política e historia del pensamiento.`],
  study:[`Formular en una oración el problema central.`,`Reconstruir la tesis sin depender de una cita aislada.`,`Definir al menos tres conceptos en el sentido específico del texto.`,`Comparar una recepción posterior con el contexto original.`],
  secondary:['Strauss & Cropsey, Sabine y Wolin como mapas historiográficos generales.','Buscar bibliografía especializada desde el buscador académico del Atlas.']
 };
}
function getStudyGuide(w){return DEEP_GUIDES[w.id]||defaultStudyGuide(w);}
