Object.assign(POSTDOC_GUIDES,{
 gilgamesh:PD([
  `La Epopeya de Gilgamesh debe situarse antes que nada como una composición estratificada, transmitida y reelaborada durante siglos, cuya forma babilónica estándar organiza materiales mucho más antiguos. No es un tratado de filosofía política y tampoco puede leerse como si contuviera una teoría del Estado en sentido moderno. Su interés para la teoría política reside en otra parte: dramatiza la transformación de una potencia regia excesiva en una forma de autoridad consciente de límites, reciprocidades y mortalidad. El punto de partida es una ciudad que padece a su propio rey. Gilgamesh posee fuerza y preeminencia, pero el exceso de esa fuerza produce queja, y la queja de Uruk desencadena la intervención divina que crea a Enkidu como contrapeso.`,
  `La obra permite distinguir con particular nitidez fuerza, prestigio heroico, realeza y gobierno. Gilgamesh no deja de ser poderoso; lo que cambia es la relación entre poder y medida. La amistad con Enkidu introduce reciprocidad allí donde inicialmente había unilateralidad, y la muerte del compañero desarticula la fantasía de excepcionalidad que sostenía la identidad heroica. El viaje en busca de Utnapishtim convierte la mortalidad en problema político indirecto: si el soberano no puede abolir su condición humana, la duración de la comunidad no puede fundarse en la perpetuidad biológica del gobernante.`,
  `El retorno final a las murallas de Uruk reorganiza retrospectivamente la epopeya. La ciudad, su materialidad y su memoria aparecen como aquello que puede persistir más allá del individuo. Una lectura políticamente cuidadosa no convierte las murallas en “instituciones” modernas, pero sí advierte un desplazamiento conceptual: la obra duradera del rey es una obra común, visible y transmisible. Desde esta perspectiva, Gilgamesh es una fuente privilegiada para estudiar una prehistoria de la reflexión sobre límites del poder, responsabilidad regia y diferencia entre dominación personal y orden civilizado.`
 ],[
  `La arquitectura del poema parte del exceso regio y de la respuesta comunitaria a ese exceso. Enkidu no es simplemente un amigo: su creación responde narrativamente al problema de un poder sin igual. El combate que precede a la amistad funciona como reconocimiento recíproco; Gilgamesh descubre una fuerza que no puede tratar como materia pasiva.`,
  `La empresa contra Humbaba y el episodio del Toro Celeste desplazan la cuestión hacia gloria, fama y riesgo. La violencia heroica produce prestigio, pero también consecuencias que el héroe no controla. La muerte de Enkidu muestra que la expansión de capacidad no equivale a dominio de contingencia y destino.`,
  `El duelo produce una crisis de identidad. Gilgamesh ya no teme sólo la muerte de otro; reconoce su propia finitud y abandona temporalmente la ciudad. La búsqueda de Utnapishtim es una tentativa de resolver ontológicamente un problema que la epopeya finalmente devuelve al plano humano.`,
  `El fracaso en obtener inmortalidad y el regreso a Uruk no constituyen una simple resignación. El poema reorienta la grandeza desde la excepción individual hacia la inscripción del soberano en una comunidad histórica. El rey sigue siendo singular, pero su singularidad adquiere sentido dentro de una obra colectiva que lo excede.`
 ],{realeza:`Institución personal y sacralizada que concentra autoridad, pero cuya legitimidad narrativa se juzga por su relación con la ciudad y no sólo por la magnitud de la fuerza del rey.`,civilización:`Proceso de incorporación a redes de lenguaje, sexualidad, alimentación, vestimenta, amistad y vida urbana; la oposición Enkidu salvaje/Enkidu civilizado permite interrogar qué prácticas hacen posible la vida común.`,mortalidad:`Límite antropológico que desactiva la pretensión de excepcionalidad absoluta y obliga a redefinir la permanencia política.`,poder:`Capacidad efectiva de imponer, combatir y emprender acciones extraordinarias; la epopeya muestra que poder sin medida puede volverse políticamente autodestructivo.`,ciudad:`Horizonte de continuidad material y simbólica que da forma política a la memoria del rey.`},[
  `La primera controversia metodológica consiste en determinar qué significa hacer teoría política con un poema épico. Una lectura rigurosa debe evitar dos extremos: excluirlo porque carece de conceptos sistemáticos, o atribuirle categorías modernas que su lenguaje no contiene. La cuestión es reconstruir problemas normativos y políticos efectivamente dramatizados por la obra.`,
  `La relación entre realeza y crítica es también discutida. El poema no propone abolir la monarquía; el problema es el mal ejercicio de una posición regia legítima. Esto permite pensar formas preconstitucionales de limitación normativa del soberano sin proyectar separación de poderes o soberanía popular.`,
  `La figura de Enkidu abre debates sobre alteridad, civilización y poder. Su domesticación puede leerse como incorporación cultural, pero también como pérdida de una forma de vida anterior. La epopeya no ofrece una teoría lineal del progreso y obliga a mantener abiertas las ambivalencias de la civilización urbana.`
 ],[
  `Gilgamesh fue central para la reconstrucción moderna de la literatura mesopotámica y modificó la imagen decimonónica de un Oriente reducido a religión y despotismo. Su recuperación permite mostrar que las sociedades mesopotámicas produjeron narrativas complejas sobre legitimidad, límites y vida urbana.`,
  `En historia comparada del pensamiento, la epopeya ha sido utilizada para estudiar modelos de realeza, memoria y civilización. Su relación con tradiciones bíblicas, especialmente el motivo del diluvio, abrió además un campo de comparación textual que vuelve visible la circulación de repertorios en el antiguo Cercano Oriente.`,
  `Dentro de una historia universal de la teoría política, su valor no consiste en reemplazar a Platón como “primer filósofo político”, sino en problematizar el supuesto de que la reflexión políticamente significativa comienza sólo cuando aparece el tratado filosófico griego.`
 ],[
  `Comparada con las Instrucciones para Merikare, la epopeya trabaja el límite del soberano mediante experiencia heroica, amistad y mortalidad, mientras la literatura egipcia lo hace mediante prudencia, consejo y Maat.`,
  `Comparada con Maquiavelo, ambas obras examinan capacidad de un gobernante frente a fortuna o contingencia, pero el parecido es funcional y no doctrinal: los lenguajes normativos, antropologías y géneros son radicalmente diferentes.`,
  `Comparada con Hobbes, Gilgamesh permite invertir la pregunta moderna: no parte de individuos sin soberano que necesitan autoridad común, sino de una ciudad que ya posee un soberano y debe encontrar una medida para su exceso.`
 ],['Andrew George, The Epic of Gilgamesh: A New Translation.','Andrew George, The Babylonian Gilgamesh Epic.','Benjamin R. Foster, The Epic of Gilgamesh.','Mario Liverani, Myth and Politics in Ancient Near Eastern Historiography.','Marc Van De Mieroop, A History of the Ancient Near East.'],['Explicar por qué una epopeya puede ser fuente de reflexión política sin ser un tratado.','Reconstruir la secuencia exceso regio–Enkidu–amistad–mortalidad–retorno a Uruk.','Distinguir poder personal de autoridad políticamente medida.','Analizar el valor político de la ciudad y la memoria.','Formular los límites de una comparación con teorías posteriores.']),
 hammurabi:PD([
  `La estela de Hammurabi debe leerse simultáneamente como monumento regio, colección jurídica y programa de legitimación. La categoría moderna de “código” es útil como convención, pero puede inducir a error si sugiere exhaustividad, sistematicidad legislativa y aplicación judicial idénticas a las de un código contemporáneo. Los denominados artículos son formulaciones casuísticas que ejemplifican modos de resolver conflictos y que se encuentran encuadradas por un prólogo y un epílogo donde el rey se representa como elegido para establecer justicia.`,
  `El rasgo políticamente decisivo es que la coerción regia se presenta bajo una misión normativa. El rey no afirma simplemente una superioridad fáctica; se atribuye la tarea de impedir que el fuerte oprima al débil, estabilizar expectativas, proteger formas de propiedad y familia y hacer visible una capacidad de juzgar. Esta pretensión de justicia convive con profundas desigualdades jurídicas entre estatus sociales. La tensión obliga a distinguir universalidad retórica de justicia e igualdad moderna: una norma puede aspirar a ordenar imparcialmente determinadas relaciones sin abolir jerarquías constitutivas de la sociedad.`,
  `La monumentalidad del texto es parte de su política. La imagen de Hammurabi ante Shamash y la inscripción pública vinculan autoridad humana y orden divino; además producen memoria. La ley no aparece como creación ex nihilo de una voluntad soberana moderna, sino como ejercicio regio de una justicia inscrita en un cosmos normativo. Para teoría política, el documento permite estudiar cómo el poder se juridifica, cómo la publicidad puede operar como recurso de legitimación y cómo la idea de justicia puede coexistir con órdenes sociales fuertemente estratificados.`
 ],[
  `El prólogo construye una genealogía de legitimidad: los dioses asignan a Hammurabi una misión de gobierno y justicia. Este encuadre impide separar radicalmente derecho, teología y realeza.`,
  `La colección casuística trata propiedad, comercio, deuda, trabajo, responsabilidad profesional, familia, herencia y lesiones. La diversidad de materias muestra que la capacidad política se proyecta sobre relaciones económicas y domésticas, no sólo sobre delitos públicos.`,
  `La diferenciación de sanciones según condición jurídica revela que la equivalencia normativa no es igualdad de sujetos. El orden se piensa como articulación jerárquica de posiciones diferenciadas.`,
  `El epílogo vuelve a situar la colección en el plano de la memoria política: Hammurabi se presenta como rey justo y maldice a futuros gobernantes que borren o alteren la inscripción.`
 ],{justicia:`Función regia de establecimiento de un orden correcto mediante decisiones que contienen violencia privada, protegen posiciones reconocidas y permiten resolver disputas; no equivale a igualdad jurídica moderna.`,ley:`Conjunto de formulaciones casuísticas y principios de decisión insertos en una tradición jurídica más amplia; no debe suponerse una codificación exhaustiva.`,realeza:`Posición sacralizada que concentra capacidad judicial, administrativa y militar, legitimada por su responsabilidad de mantener orden.`,orden:`Configuración jerárquica de relaciones sociales que el soberano debe estabilizar y reproducir.`,publicidad:`Dimensión monumental de la norma que transforma la justicia en representación visible y memoria del gobierno.`},[
  `El debate filológico-jurídico más importante concierne al estatuto de la colección: ley vinculante, colección escolástica, monumento ideológico o combinación de funciones. La evidencia documental de práctica judicial obliga a evitar una lectura literalista de la estela como código aplicado mecánicamente.`,
  `Existe además un problema de traducción conceptual. Términos asociados a justicia, equidad y orden no corresponden de modo transparente a las categorías del derecho moderno. Una lectura comparativa debe preservar su especificidad semántica.`,
  `La célebre lex talionis suele aislarse del conjunto. Sin embargo, el análisis político exige situarla dentro de un sistema de estatus, compensaciones y responsabilidades donde sanción, propiedad y jerarquía forman una arquitectura común.`
 ],[
  `La estela adquirió enorme importancia en la historia moderna del derecho por su antigüedad y monumentalidad, aunque la historiografía reciente ha corregido la imagen de Hammurabi como legislador moderno.`,
  `En estudios de estatalidad temprana se utiliza para analizar centralización, administración y capacidad de producción de normas. Su valor aumenta cuando se compara con archivos judiciales y contratos efectivamente utilizados.`,
  `Para la historia de teoría política, contribuye a desmontar la identificación entre Oriente antiguo y mera arbitrariedad despótica: muestra un discurso complejo de responsabilidad regia y justicia, aunque dentro de una estructura desigual.`
 ],[
  `Comparar con Manu permite estudiar dos órdenes donde la autoridad política actúa dentro de normatividades jerárquicas superiores al capricho del gobernante.`,
  `Comparar con Han Fei aclara la diferencia entre justicia regia sacralizada y una teoría más explícita de estándares administrativos impersonales.`,
  `Comparar con Cicerón permite observar la distancia entre una justicia inscrita en realeza y una teoría racionalizada de ley natural.`
 ],['Martha T. Roth, Law Collections from Mesopotamia and Asia Minor.','Dominique Charpin, Writing, Law, and Kingship in Old Babylonian Mesopotamia.','Marc Van De Mieroop, King Hammurabi of Babylon.','Raymond Westbrook, Studies in Biblical and Cuneiform Law.','Kathryn Slanski, estudios sobre monumentos jurídicos mesopotámicos.'],['Explicar por qué “Código” es una convención historiográfica problemática.','Analizar prólogo y epílogo como teoría de legitimación.','Mostrar la coexistencia entre justicia y jerarquía de estatus.','Distinguir norma monumental de práctica judicial.','Comparar la función política de la ley con una tradición posterior sin anacronismo.']),
 merikare:PD([
  `Las Instrucciones para Merikare pertenecen a una literatura de consejo regio cuya relevancia política desmiente la caricatura del faraón como poder sin reflexión sobre límites. Su voz textual, probablemente pseudepigráfica y transmitida en manuscritos posteriores, sitúa al príncipe frente a un repertorio de problemas concretos: selección de funcionarios, uso de la palabra, tratamiento de adversarios, memoria de errores y relación entre justicia y estabilidad. El texto no limita al rey mediante una constitución externa; lo somete a una normatividad interna de buen gobierno.`,
  `Maat es el eje de esa normatividad. Reducirla a “justicia” empobrece el concepto: articula verdad, orden, equilibrio, corrección ritual y adecuada reciprocidad social. El rey es responsable de hacer efectiva Maat y de contener isfet, el desorden. Por eso la eficacia política y la corrección normativa no se presentan como términos opuestos. Una decisión brutal puede ser contraproducente precisamente porque destruye las condiciones del orden que el soberano debe preservar.`,
  `El texto contiene además una política de la memoria. El consejo recuerda errores de gobierno y consecuencias no deseadas, especialmente en relación con violencia y conflicto. La prudencia aparece así como capacidad de aprender de la experiencia histórica. Para una teoría política comparada, Merikare permite estudiar un tipo de racionalidad gubernamental donde legitimidad, conocimiento práctico y orden cósmico-social se encuentran estrechamente vinculados.`
 ],[
  `El consejo construye al gobernante como sujeto que debe dominar palabra y juicio antes que violencia. La elocuencia y la escucha son capacidades de gobierno.`,
  `La selección de funcionarios muestra que el orden político depende de mediaciones administrativas: el rey no gobierna solo, y la calidad de sus agentes afecta directamente la justicia.`,
  `Los pasajes sobre enemigos y rebelión distinguen coerción necesaria de violencia indiscriminada. La prudencia consiste en calcular efectos políticos, no en renunciar al poder.`,
  `La relación entre culto, justicia y estabilidad integra dimensiones que una lectura moderna tendería a separar. La corrección del gobierno participa del mantenimiento de un orden total.`
 ],{maat:`Principio de verdad, justicia, equilibrio y orden relacional que constituye simultáneamente criterio moral, político y cosmológico del gobierno.`,realeza:`Responsabilidad institucional y sacralizada de sostener Maat mediante juicio, administración y coerción medida.`,prudencia:`Capacidad de evaluar circunstancias, aprender de errores y seleccionar medios proporcionados a fines de estabilidad y justicia.`,palabra:`Instrumento político de consejo, persuasión, orden y resolución de conflictos; la palabra correcta forma parte del poder regio.`,coerción:`Recurso legítimo pero peligroso cuya eficacia depende de medida, oportunidad y relación con el restablecimiento del orden.`},[
  `La datación y composición del texto son discutidas, por lo que el contexto histórico no debe presentarse como reflejo transparente de un único reinado. La historia intelectual debe distinguir escenario literario y momento de transmisión.`,
  `El estatuto político de Maat suscita debates importantes: cosmología, ética, ideología de Estado o principio de conectividad social. Las mejores lecturas evitan elegir una sola dimensión y examinan su carácter relacional.`,
  `La categoría moderna de “espejo de príncipes” puede ser comparativamente útil, pero no debe borrar las especificidades de la cultura escribal egipcia ni su concepción de realeza.`
 ],[
  `La literatura sapiencial egipcia fue tradicionalmente estudiada en filología y religión más que en teoría política. Su reincorporación a una historia intelectual amplia permite reconocer formas de argumentación sobre gobierno previas a Grecia.`,
  `El concepto de Maat ha sido central en trabajos de Jan Assmann y otros egiptólogos para pensar integración social, memoria y justicia.`,
  `Comparaciones con literatura de consejo de otras civilizaciones permiten estudiar convergencias funcionales sin postular una línea genealógica única.`
 ],[
  `Comparar con Ptahhotep y otros sebayt para reconstruir una tradición egipcia de prudencia, jerarquía y palabra.`,
  `Comparar con Aristóteles permite distinguir prudencia práctica dentro de una teoría de la polis de prudencia regia inscrita en Maat.`,
  `Comparar con Maquiavelo resulta productivo si se conserva la diferencia entre una racionalidad de conservación del orden normativo y una autonomía más fuerte de la necesidad política.`
 ],['Jan Assmann, Ma’at: Gerechtigkeit und Unsterblichkeit im Alten Ägypten.','Erik Hornung, Conceptions of God in Ancient Egypt.','Richard Parkinson, Poetry and Culture in Middle Kingdom Egypt.','Marcelo Campagno, trabajos sobre Estado y realeza egipcios.','Miriam Lichtheim, Ancient Egyptian Literature.'],['Definir Maat como concepto multidimensional.','Explicar cómo el texto articula justicia y eficacia.','Reconstruir la función política de palabra y funcionarios.','Analizar memoria del error como fuente de prudencia.','Distinguir limitación normativa del rey de constitucionalismo moderno.']),
 peasant:PD([
  `El Campesino elocuente es una narración literaria de extraordinaria importancia para una historia de la argumentación política. Un hombre socialmente inferior, víctima de un abuso, transforma una pérdida concreta en una serie de discursos sobre justicia. La estructura narrativa hace visible una cuestión central: el poder produce un lenguaje normativo —Maat— que puede ser invocado por quienes sufren las desviaciones de sus agentes. La crítica no procede desde una teoría externa a la monarquía, sino desde las propias pretensiones de legitimidad del orden.`,
  `La elocuencia del protagonista no es un adorno retórico. El habla convierte el agravio particular en una cuestión general de responsabilidad. El campesino apela a la autoridad superior porque presupone que existe una diferencia entre la conducta injusta de un funcionario y el ideal que legitima al conjunto. La narración explora así la posibilidad de una crítica inmanente: una norma oficial puede volverse instrumento para exigir coherencia al poder.`,
  `El relato conserva, sin embargo, una asimetría radical. El campesino depende de que autoridades más altas escuchen y decidan. No existe derecho subjetivo moderno ni procedimiento igualitario. Esta limitación no reduce su importancia; permite precisamente estudiar cómo surge una pretensión de justicia en un orden jerárquico y cómo la palabra pública puede crear un espacio de exigencia sin abolir la estructura monárquica.`
 ],[
  `El despojo inicial fija la materialidad del conflicto y la desigualdad entre las partes. La teoría de justicia emerge de una experiencia concreta y no de una abstracción descontextualizada.`,
  `Las peticiones sucesivas amplían el registro: de restitución individual a reflexión sobre funciones del juez, deberes del poderoso y relación entre verdad y autoridad.`,
  `La decisión de prolongar la elocuencia del campesino introduce una ambigüedad ética: la autoridad admira el discurso y a la vez demora la reparación. El texto permite interrogar la estetización del sufrimiento por parte del poder.`,
  `La resolución restaura el orden mediante intervención superior. No hay democratización, pero sí reconocimiento de que la jerarquía se legitima por capacidad de responder a una demanda justa.`
 ],{justicia:`Pretensión de correspondencia entre orden normativo proclamado y tratamiento efectivo de una persona perjudicada.`,palabra:`Capacidad de transformar agravio privado en argumento general y de hacer visible la obligación del superior.`,autoridad:`Relación jerárquica cuya legitimidad se prueba en la capacidad de corregir abusos y restablecer Maat.`,maat:`Criterio compartido que permite una crítica inmanente del poder desde dentro de su propio lenguaje normativo.`,petición:`Forma de acción política dependiente, pero argumentativa, mediante la cual un subordinado interpela a una instancia superior.`},[
  `Una controversia metodológica concierne a la relación entre literatura y práctica. El relato no demuestra que cualquier campesino pudiera litigar de ese modo; su valor reside en lo que la cultura escribal considera inteligible como argumento de justicia.`,
  `La crítica inmanente no debe confundirse con resistencia democrática. El texto presupone y reafirma la jerarquía al mismo tiempo que la somete a un estándar.`,
  `El tratamiento estético de la elocuencia abre una lectura más inquietante: el poder puede disfrutar y administrar la voz del subordinado antes de reparar la injusticia. Esa dimensión complejiza una interpretación puramente celebratoria.`
 ],[
  `El texto ha sido central para estudios de literatura del Reino Medio y, más recientemente, para reconstrucciones de justicia y racionalidad política egipcias.`,
  `En teoría política comparada ofrece un caso particularmente fuerte para estudiar voz subalterna, petición y obligación sin proyectar derechos modernos.`,
  `Su relación con Maat permite integrar análisis literario, institucional y normativo en una misma reconstrucción histórica.`
 ],[
  `Comparar con Antígona permite contrastar dos formas de impugnación: petición dentro de la jerarquía frente a una desobediencia que invoca deberes irreductibles al decreto político.`,
  `Comparar con tradiciones modernas de derecho de petición ayuda a identificar continuidades funcionales y discontinuidades institucionales.`,
  `Comparar con Habermas puede ser heurístico para pensar fuerza de la argumentación, siempre que no se atribuya al Egipto medio una esfera pública moderna.`
 ],['Richard Parkinson, The Tale of the Eloquent Peasant.','Miriam Lichtheim, Ancient Egyptian Literature.','Jan Assmann, Ma’at.','Antonio Loprieno, Ancient Egyptian: A Linguistic Introduction y estudios literarios.','Marcelo Campagno, trabajos sobre política y sociedad egipcia.'],['Reconstruir el pasaje de agravio a argumento general.','Explicar crítica inmanente mediante Maat.','Analizar la ambivalencia de la demora de la justicia.','Distinguir petición jerárquica de derecho subjetivo moderno.','Mostrar por qué un texto literario puede contener teoría política situada.']),
 confucius:PD([
  `Las Analectas son una compilación estratificada de dichos y escenas vinculados con Confucio y sus discípulos. Su forma fragmentaria es parte del problema interpretativo: no existe una exposición sistemática comparable a un tratado moderno, pero sí una arquitectura normativa consistente en torno a cultivo personal, ritual, gobierno ejemplar y correcta ocupación de roles. La política confuciana comienza menos por diseñar instituciones que por preguntar qué disposiciones hacen posible que una estructura de autoridad funcione sin depender continuamente de castigo.`,
  `El concepto de de designa una eficacia virtuosa que irradia desde la persona ejemplar. Li, traducido como rito, incluye ceremonial pero también hábitos, modales y formas apropiadas de relación. Gobernar mediante virtud y rito no significa ausencia de instituciones: significa que la estabilidad de las instituciones depende de prácticas incorporadas que vuelven previsible el comportamiento. La ley penal puede contener conductas, pero no produce por sí sola vergüenza, juicio o sentido de responsabilidad.`,
  `La rectificación de nombres aporta un componente específicamente político. Un título —gobernante, ministro, padre— establece expectativas normativas. Cuando conducta y nombre divergen, el lenguaje deja de ordenar correctamente las relaciones. La teoría confuciana vincula entonces semántica, rol y legitimidad. Para estudiantes formados en tradiciones occidentales, el desafío es no reducir Confucio a moral privada: su ética de roles es simultáneamente una teoría de administración, educación y autoridad.`
 ],[
  `El junzi representa un ideal de formación que desplaza la excelencia desde nacimiento aristocrático hacia cultivo. Esta transformación contiene un potencial meritocrático, aunque no democrático.`,
  `Li disciplina deseos y comportamientos mediante hábitos públicos. Su eficacia es pre-reflexiva: un orden estable no requiere deliberar cada regla desde cero.`,
  `El gobierno por de se opone al gobierno centrado en castigo. La oposición no elimina coerción; jerarquiza formas de producción de obediencia.`,
  `La rectificación de nombres conecta lenguaje y responsabilidad. Un régimen se desordena cuando posiciones siguen existiendo nominalmente pero pierden contenido normativo.`,
  `La centralidad del aprendizaje muestra que la política confuciana posee una dimensión pedagógica permanente: formar gobernantes y gobernados es una tarea institucional.`
 ],{de:`Virtud o potencia moral eficaz que produce deferencia y orientación sin recurrir prioritariamente a coerción.`,li:`Conjunto de ritos, formas y prácticas que modelan disposiciones y estructuran relaciones sociales.`,junzi:`Persona ejemplar formada mediante estudio, autocultivo y práctica ritual; ideal ético con función política.`,rectificación_de_nombres:`Exigencia de correspondencia entre denominaciones sociales y desempeño efectivo de obligaciones vinculadas a cada rol.`,ren:`Humanidad o benevolencia que orienta relaciones correctas y da contenido moral al cultivo.`},[
  `La interpretación contemporánea discute si Confucio debe leerse como conservador jerárquico o como reformador meritocrático. La respuesta depende de distinguir defensa de roles de defensa incondicional de cualquier titular de esos roles.`,
  `Existe un debate entre lecturas perfeccionistas y políticas: ¿el objetivo es producir buenas personas o un buen orden? Las Analectas dificultan la separación porque conciben ambos procesos como interdependientes.`,
  `La traducción de ren, li, de y junzi es un problema teórico. Equivalentes occidentales como virtud, ritual o noble pueden iluminar y distorsionar al mismo tiempo; una aproximación rigurosa conserva los términos y explica su campo semántico.`
 ],[
  `La tradición confuciana se convirtió en uno de los repertorios normativos más influyentes de Asia oriental, transformándose en períodos Han, Song y posteriores.`,
  `En debates contemporáneos, Confucio ha sido recuperado en discusiones sobre meritocracia, democracia confuciana, ética de roles y ciudadanía.`,
  `La comparación global ha cuestionado la oposición simplista entre “Occidente institucional” y “Oriente moral”, mostrando la densidad política de conceptos rituales y educativos.`
 ],[
  `Comparar con Mencio permite observar una radicalización del criterio de bienestar popular y una antropología moral más explícita.`,
  `Comparar con Xunzi muestra cómo una tradición común produce respuestas distintas sobre naturaleza humana y artificialidad institucional.`,
  `Comparar con Han Fei es indispensable: virtud y rito frente a estándares, técnicas y poder posicional.`,
  `Comparar con Aristóteles permite estudiar convergencias entre formación del carácter y buen gobierno sin postular equivalencia conceptual.`
 ],['Edward Slingerland, Confucius: Analects.','A. C. Graham, Disputers of the Tao.','Herbert Fingarette, Confucius: The Secular as Sacred.','Roger Ames y Henry Rosemont, The Analects of Confucius.','Stephen Angle, Contemporary Confucian Political Philosophy.'],['Explicar la relación de de, li y gobierno.','Mostrar por qué la rectificación de nombres es una tesis política.','Distinguir meritocracia de democracia.','Comparar Confucio con Han Fei en torno a obediencia.','Justificar por qué la ética de roles no es mera moral privada.']),
 mencius:PD([
  `Mencio desarrolla el confucianismo en un contexto de competencia entre escuelas y de consolidación de grandes unidades territoriales. Su teoría combina una antropología moral optimista con una exigente concepción del gobierno benevolente. Los seres humanos poseen “brotes” de virtud, pero esos brotes requieren condiciones sociales y educativas para desarrollarse. La política no puede exigir conducta moral ignorando las condiciones materiales de vida.`,
  `Esta premisa fundamenta una economía moral del gobierno. El soberano debe asegurar sustento, reducir cargas destructivas y permitir que las familias mantengan condiciones mínimas de estabilidad. El bienestar del pueblo no es un añadido filantrópico: participa de la legitimidad del régimen. Un gobernante que destruye sistemáticamente esas condiciones deja de ocupar normativamente la posición de rey aunque conserve poder fáctico.`,
  `La célebre discusión sobre matar a un tirano ilustra esta lógica. Mencio sostiene que eliminar a quien ha perdido humanidad y justicia no equivale a matar a un rey. No es todavía una teoría moderna de soberanía popular o derecho individual de revolución; es una teoría de deslegitimación basada en cumplimiento del rol y Mandato. Su importancia comparativa radica precisamente en mostrar un lenguaje no contractual de limitación del poder.`
 ],[
  `La teoría de los brotes morales establece capacidad humana para benevolencia, justicia, ritual y sabiduría. La política debe cultivar, no fabricar desde cero, esas disposiciones.`,
  `El gobierno benevolente conecta tributación, agricultura, seguridad y educación con formación moral. La economía es políticamente relevante porque afecta posibilidades éticas.`,
  `El pueblo funciona como criterio de evaluación del gobernante. La legitimidad no se identifica con preferencia electoral, sino con una responsabilidad sustantiva de gobierno.`,
  `El Mandato puede perderse. La caída de un tirano puede reinterpretarse como consecuencia de haber dejado de ser legítimo antes de su derrota.`,
  `La persuasión de reyes es parte del método: Mencio presenta filosofía política como intervención práctica ante gobernantes reales.`
 ],{benevolencia:`Principio moral y gubernamental que exige tratar a la población de manera compatible con su capacidad de florecimiento.`,pueblo:`Comunidad cuyo bienestar material y moral constituye un criterio fundamental de legitimidad, sin equivaler a un demos soberano moderno.`,mandato:`Fuente trascendente y moral de legitimidad que puede perderse cuando el gobernante destruye las obligaciones de su rol.`,virtud:`Disposición cultivable fundada en capacidades morales humanas y requerida para gobernar correctamente.`,naturaleza_humana:`Concepción según la cual existen tendencias iniciales hacia la virtud que pueden desarrollarse o ser dañadas por circunstancias.`},[
  `La cuestión del “derecho de rebelión” debe formularse con cautela. Mencio legitima el reemplazo del tirano, pero no desarrolla una doctrina de derechos individuales o procedimientos populares de deposición.`,
  `La relación entre antropología y política genera una discusión clásica con Xunzi. Si la naturaleza humana es buena, la función institucional se concibe de modo distinto que si los deseos espontáneos son conflictivos.`,
  `El uso contemporáneo de Mencio en teorías de democracia confuciana plantea el problema de hasta dónde conceptos antiguos pueden transformarse sin perder identidad histórica.`
 ],[
  `Mencio fue canonizado como uno de los textos centrales del confucianismo y tuvo enorme importancia en la tradición neo-confuciana.`,
  `En filosofía política contemporánea se lo utiliza para discutir bienestar, legitimidad, virtud pública y posibilidades de una modernidad confuciana.`,
  `Su teoría del tirano ofrece un punto de comparación privilegiado con doctrinas occidentales de resistencia sin reducirlas a un mismo vocabulario.`
 ],[
  `Comparar con Confucio muestra continuidad en virtud y rito, pero mayor énfasis en bienestar popular y pérdida de legitimidad.`,
  `Comparar con Xunzi permite reconstruir una controversia interna sobre naturaleza humana e instituciones.`,
  `Comparar con Locke ilumina dos caminos distintos hacia la resistencia: ruptura del mandato fiduciario frente a pérdida moral del estatus regio.`
 ],['D. C. Lau, Mencius.','Bryan Van Norden, Virtue Ethics and Consequentialism in Early Chinese Philosophy.','A. C. Graham, Disputers of the Tao.','David Elstein, Democracy in Contemporary Confucian Philosophy.','Stephen Angle, Contemporary Confucian Political Philosophy.'],['Explicar la teoría de los brotes morales.','Relacionar condiciones materiales y virtud.','Distinguir legitimidad popular de soberanía popular.','Reconstruir la lógica de pérdida del Mandato.','Comparar Mencio con Locke sin equiparar sus fundamentos.']),
 mozi:PD([
  `El Mozi conserva materiales de una escuela que rivalizó seriamente con confucianos durante los Reinos Combatientes. Su teoría política es notable por articular una moral de preocupación imparcial, una crítica del lujo aristocrático, una defensa del mérito y una condena sistemática de la guerra ofensiva. El criterio recurrente es funcional: doctrinas y prácticas deben evaluarse por sus efectos sobre orden, prosperidad y bienestar de la población.`,
  `La llamada “preocupación imparcial” no exige ausencia de relaciones particulares, sino una ampliación de la consideración moral que impida que lealtades estrechas justifiquen daño a otros. La escuela vincula este principio con organización política jerárquica: para superar desacuerdos, la sociedad necesita estándares coordinados y autoridades capaces de unificar juicios. Existe así una tensión productiva entre universalismo moral y disciplina administrativa.`,
  `La crítica de la guerra ofensiva es uno de los argumentos más radicales del corpus. Mozi pregunta por qué acciones condenadas como robo o asesinato cuando las realiza un individuo reciben honores cuando las realiza un Estado a gran escala. Esta inversión expone la doble moral de la violencia política y convierte al texto en antecedente comparativo indispensable para teorías de guerra justa, aun cuando su marco no sea el del derecho internacional moderno.`
 ],[
  `El ataque al gasto funerario y musical cuestiona prácticas aristocráticas por sus costos sociales. La cultura no se evalúa sólo por tradición, sino por consecuencias.`,
  `La preocupación imparcial busca reducir conflicto producido por favoritismos de familia, clan y Estado.`,
  `La promoción de los capaces introduce un principio de mérito que desafía herencia aristocrática.`,
  `La “elevación de los dignos” y la conformidad con superiores producen un modelo de coordinación fuertemente vertical.`,
  `Los capítulos contra la guerra ofensiva aplican un mismo criterio moral a violencia individual y estatal.`
 ],{imparcialidad:`Extensión de preocupación moral más allá de círculos particulares, destinada a reducir favoritismo, agresión y conflicto.`,mérito:`Criterio de selección de funcionarios por capacidad y contribución al orden, en oposición a privilegio puramente hereditario.`,guerra:`Objeto de una crítica consecuencial y moral especialmente dirigida contra agresión ofensiva.`,orden:`Coordinación de juicios y conductas mediante estándares compartidos y una jerarquía política capaz de implementarlos.`,beneficio:`Criterio práctico que considera consecuencias para población y comunidad al evaluar instituciones y costumbres.`},[
  `La comparación con utilitarismo moderno es tentadora por el lenguaje de beneficio, pero debe evitarse identificar una doctrina antigua de consecuencias sociales con una teoría de maximización cuantitativa de utilidad.`,
  `La preocupación imparcial ha sido interpretada como amor universal, cuidado inclusivo o norma de trato. Cada traducción modifica su relación con vínculos particulares.`,
  `El verticalismo político mohista plantea una paradoja: una ética relativamente igualitaria de consideración puede combinarse con una estructura administrativa disciplinaria.`
 ],[
  `Aunque la escuela mohista perdió centralidad institucional frente al confucianismo, sus textos sobrevivieron y fueron recuperados como una de las alternativas más sistemáticas del pensamiento chino antiguo.`,
  `La historiografía contemporánea ha destacado sus contribuciones a lógica, epistemología, mérito administrativo y crítica de guerra.`,
  `En teoría comparada, Mozi expande el repertorio más allá de la oposición simplificada Confucio/legalismo y muestra un pluralismo intelectual notable en China preimperial.`
 ],[
  `Comparar con Confucio permite contrastar ritual y relaciones graduadas con preocupación más imparcial y evaluación consecuencial.`,
  `Comparar con Han Fei permite estudiar dos proyectos de coordinación jerárquica que difieren profundamente en fundamento moral.`,
  `Comparar con tradiciones de guerra justa ayuda a identificar la singularidad de una crítica que parte de continuidad moral entre homicidio privado y guerra estatal.`
 ],['Ian Johnston, The Mozi: A Complete Translation.','Chris Fraser, The Philosophy of the Mòzĭ.','A. C. Graham, Disputers of the Tao.','Carine Defoort, estudios sobre Mohismo.','Bryan Van Norden, Introduction to Classical Chinese Philosophy.'],['Definir preocupación imparcial sin convertirla en utilitarismo.','Explicar relación entre mérito y jerarquía.','Reconstruir el argumento contra guerra ofensiva.','Analizar la tensión entre igual consideración y disciplina política.','Situar al mohismo como escuela rival, no marginal desde su origen.']),
 laozi:PD([
  `El Daodejing es un texto breve, estratificado y deliberadamente paradójico. Su relevancia política reside en una crítica de las formas de gobierno que producen aquello que buscan corregir. Cuanto más se multiplican regulaciones, distinciones, ambiciones y demostraciones de poder, más pueden intensificarse deseo, competencia y desorden. El texto no propone una doctrina institucional detallada; interroga la lógica misma de la intervención política.`,
  `Wu wei suele traducirse como no-acción, pero la traducción puede sugerir pasividad. Se trata más bien de acción no forzada, no ostentosa y no dominadora: una forma de conducción que crea condiciones sin saturar la vida social con voluntad gubernamental. El buen gobernante aparece casi ausente porque no convierte su propia agencia en centro permanente del orden.`,
  `La crítica del deseo y del lujo distingue al daoísmo de un liberalismo económico avant la lettre. El objetivo no es liberar preferencias para que se expresen en mercado, sino disminuir mecanismos políticos y culturales que producen deseos competitivos. La simplicidad tiene una dimensión normativa. Para teoría política, el texto ofrece un repertorio excepcional para pensar límites de planificación, efectos no intencionales y poder de la no-imposición.`
 ],[
  `El Dao funciona como horizonte de procesos que exceden diseño humano. La política es buena cuando se ajusta a esa dinámica en lugar de pretender dominarla completamente.`,
  `Wu wei redefine eficacia: hacer menos puede producir más orden si la intervención agresiva generaba resistencia y complejidad.`,
  `La imagen del agua condensa una ética de flexibilidad, posición baja y potencia no competitiva.`,
  `La sencillez política se vincula con reducción de deseos, armas y ostentación.`,
  `El sabio gobernante no desaparece; ejerce una forma indirecta y difícil de identificar de autoridad.`
 ],{dao:`Orden o vía de procesos que no puede ser plenamente capturado por categorías y diseños humanos, y que funciona como límite a la pretensión de control.`,wu_wei:`Acción no forzada que evita intervenciones excesivas y busca eficacia mediante ajuste a procesos antes que imposición.`,simplicidad:`Ideal de reducción de artificios, deseos competitivos y complejidad política producida.`,gobierno:`Práctica de conducción cuya excelencia se mide por su capacidad de no convertirse en fuente de desorden.`,deseo:`Fuerza social que puede ser intensificada artificialmente por prestigio, jerarquía y políticas de competencia.`},[
  `La autoría y datación del Daodejing son complejas. El texto debe estudiarse como compilación y tradición, no como obra monolítica de un individuo históricamente transparente llamado Laozi.`,
  `El significado político de wu wei divide interpretaciones: quietismo, técnica de gobierno, crítica antiestatal o ética de no-dominación. El corpus admite tensiones que no conviene resolver artificialmente.`,
  `Las apropiaciones libertarias o neoliberales modernas suelen ignorar la crítica daoísta del deseo, la riqueza y la competencia; la analogía con laissez-faire debe presentarse como recepción, no como identidad.`
 ],[
  `El daoísmo influyó profundamente en pensamiento religioso, filosófico y político chino, interactuando con confucianismo y legalismo.`,
  `En teoría política comparada se lo recupera para discutir gobierno mínimo, ecología, poder indirecto y críticas de racionalidad intervencionista.`,
  `Su estilo aforístico y paradójico lo convirtió en un texto particularmente abierto a apropiaciones modernas, lo que vuelve indispensable distinguir recepción y contexto.`
 ],[
  `Comparar con Han Fei muestra dos respuestas opuestas al desorden: reducción de imposición frente a intensificación de estándares y control.`,
  `Comparar con Hayek puede iluminar una crítica común a pretensiones de diseño total, pero sus fundamentos antropológicos, económicos y normativos son radicalmente distintos.`,
  `Comparar con Foucault permite pensar formas indirectas de poder, aunque el daoísmo no ofrece una genealogía de dispositivos modernos.`
 ],['D. C. Lau, Tao Te Ching.','Roger Ames y David Hall, Dao De Jing: Making This Life Significant.','A. C. Graham, Disputers of the Tao.','Edward Slingerland, Effortless Action.','Brook Ziporyn, trabajos sobre filosofía daoísta.'],['Definir wu wei con precisión.','Explicar la crítica a la sobreintervención.','Distinguir daoísmo de laissez-faire.','Analizar la política de la simplicidad.','Reconocer problemas de autoría y estratificación textual.']),
 xunzi:PD([
  `Xunzi comparte la centralidad confuciana del rito y la educación, pero modifica profundamente su fundamento antropológico. Los deseos humanos no están espontáneamente armonizados; si se los deja competir sin formas, producen conflicto. La cultura y las instituciones son artificios humanos necesarios para convertir esa conflictividad en cooperación. Su tesis sobre que la naturaleza humana es “mala” no significa que los individuos sean demoníacos, sino que la virtud no emerge automáticamente de inclinaciones iniciales.`,
  `Li adquiere así una función institucional más explícita. Los ritos distribuyen, distinguen, limitan y educan. No son ornamentos conservadores: constituyen una tecnología histórica de formación de disposiciones. La artificialidad, en Xunzi, tiene un sentido positivo. Aquello que ha sido construido por sabios puede ser superior a la espontaneidad precisamente porque responde reflexivamente a problemas de coordinación.`,
  `Esta posición convierte a Xunzi en un interlocutor fundamental para teorías de institucionalización. Su vínculo histórico e intelectual con Han Fei permite además ver cómo de una antropología relativamente pesimista pueden derivarse proyectos distintos. Xunzi mantiene la confianza en educación, ritual y cultivo; el legalismo enfatiza reglas, incentivos y poder posicional. La diferencia es crucial para comprender el pluralismo del pensamiento chino clásico.`
 ],[
  `La tesis sobre naturaleza humana identifica deseos y competencias que, sin transformación, generan disputa.`,
  `El aprendizaje y la deliberación producen una segunda naturaleza social. La virtud es adquirida, no simple expresión de esencia originaria.`,
  `Los ritos ordenan jerarquías y distribuciones, haciendo posible satisfacción regulada de deseos.`,
  `La autoridad de sabios depende de haber elaborado formas capaces de resolver problemas humanos recurrentes.`,
  `La teoría del lenguaje y rectificación de nombres complementa el orden ritual mediante distinciones públicas estables.`
 ],{rito:`Institución cultural que distribuye bienes y posiciones, limita deseos y produce disposiciones apropiadas para la cooperación.`,instituciones:`Construcciones humanas deliberadas que transforman tendencias conflictivas en un orden social sostenible.`,educación:`Proceso de formación que altera hábitos y vuelve posible la virtud adquirida.`,naturaleza_humana:`Conjunto de inclinaciones iniciales que no bastan para producir orden moral; requieren transformación.`,artificio:`Producto reflexivo de actividad humana que puede mejorar la espontaneidad y constituye la civilización.`},[
  `La traducción de la tesis xing e como “naturaleza humana mala” puede inducir una lectura teológica ajena al texto. El debate se centra en qué significa exactamente “mala” y cómo se relaciona con capacidad de aprendizaje.`,
  `La controversia con Mencio no es sólo antropológica: modifica el estatuto de política. Si la virtud debe ser construida, la arquitectura ritual e institucional adquiere mayor peso causal.`,
  `La relación con legalismo debe manejarse sin teleología. Que Han Fei haya sido asociado a su enseñanza no convierte a Xunzi en legalista ni hace de su teoría una etapa inevitable hacia Qin.`
 ],[
  `Xunzi fue menos canonizado que Mencio en ciertas fases del confucianismo, pero su importancia intelectual ha sido revalorizada en estudios modernos.`,
  `Su concepción de ritual como tecnología de formación resulta especialmente productiva para diálogos con teoría institucional y filosofía social.`,
  `La obra proporciona un puente conceptual entre debates confucianos y legalistas sin borrar la diferencia entre ambos.`
 ],[
  `Comparar con Mencio es indispensable para reconstruir dos antropologías políticas rivales dentro del confucianismo.`,
  `Comparar con Han Fei permite distinguir formación moral de diseño de incentivos y control.`,
  `Comparar con Hobbes es tentador por el conflicto de deseos, pero Hobbes parte de individuos y soberanía moderna, mientras Xunzi privilegia ritual y educación.`
 ],['Eric Hutton, Xunzi: The Complete Text.','A. C. Graham, Disputers of the Tao.','Paul Goldin, Rituals of the Way.','T. C. Kline y Philip Ivanhoe, Virtue, Nature, and Moral Agency in the Xunzi.','Bryan Van Norden, Introduction to Classical Chinese Philosophy.'],['Reconstruir la tesis sobre naturaleza humana sin caricaturizarla.','Explicar función distributiva y pedagógica del rito.','Mostrar el sentido positivo de artificio.','Comparar Xunzi con Mencio y Han Fei.','Relacionar antropología y diseño institucional.']),
 hanfeizi:PD([
  `Han Fei formula uno de los análisis más sofisticados del gobierno administrativo en la China preimperial. Su problema central no es cómo encontrar un soberano moralmente perfecto, sino cómo construir mecanismos que funcionen cuando actores poseen intereses propios, información incompleta y capacidad para manipular al gobernante. El foco se desplaza desde virtud personal hacia arquitectura de incentivos, estándares y control.`,
  `Tres nociones permiten organizar el corpus: fa, shu y shi. Fa refiere a estándares y reglas públicamente utilizables; shu a técnicas mediante las cuales el soberano evalúa, compara palabras y resultados y evita captura por ministros; shi a la potencia de la posición institucional, distinta del talento personal. Juntas constituyen una teoría de impersonalización parcial del gobierno.`,
  `La paradoja fundamental es que esa impersonalidad administrativa sirve a una concentración extrema de autoridad. El gobernante debe hacer previsible la conducta de otros sin hacerse él mismo completamente previsible; debe limitar arbitrariedad de funcionarios preservando discreción soberana. Han Fei permite así estudiar una configuración que no encaja en la oposición simple entre Estado de derecho y despotismo: reglas fuertes pueden coexistir con un centro políticamente no limitado por esas mismas reglas.`
 ],[
  `La crítica a gobierno por virtud señala que una institución no puede depender de la aparición excepcional de sabios.`,
  `Fa hace evaluable el desempeño mediante criterios relativamente estables. La claridad normativa busca reducir manipulación de lenguaje y favoritismo.`,
  `Shu responde al problema principal-agente: los ministros controlan información y pueden perseguir intereses propios.`,
  `Shi separa eficacia política de cualidades personales. Una posición institucional bien construida multiplica capacidad de un gobernante ordinario.`,
  `Recompensas y castigos deben ser confiables para alinear comportamientos. La racionalización de incentivos sustituye confianza moral.`
 ],{fa:`Estándares, modelos y reglas que permiten comparar conducta y desempeño de manera relativamente impersonal.`,shu:`Técnicas administrativas de evaluación, secreto, nombramiento y control utilizadas por el soberano para gobernar a sus agentes.`,shi:`Potencia derivada de la posición institucional y de la configuración del poder, no del carisma individual.`,autoridad:`Capacidad concentrada del soberano para definir y hacer operar mecanismos de coordinación.`,administración:`Red de funcionarios cuyo control es el problema político central debido a asimetrías de información e intereses.`},[
  `La etiqueta “legalismo” reúne autores diferentes y fue construida retrospectivamente. Una lectura especializada debe distinguir Han Fei de Shang Yang y Shen Buhai en lugar de tratarlos como doctrina homogénea.`,
  `La aparente afinidad con burocracia moderna ha generado comparaciones anacrónicas. Hay impersonalidad, medición y control, pero no un Estado de derecho que limite recíprocamente gobernante y gobernados.`,
  `El estatuto de moralidad es discutido: ¿Han Fei rechaza toda norma moral o sostiene una ética de supervivencia y orden estatal? La respuesta requiere separar crítica del moralismo confuciano de ausencia total de criterios.`
 ],[
  `Las ideas asociadas al legalismo participaron de la construcción de capacidad estatal Qin y continuaron influyendo incluso bajo vocabularios confucianos posteriores.`,
  `La teoría contemporánea recupera Han Fei para pensar burocracia, información, incentivos y principal-agente, aunque esas traducciones analíticas deben permanecer históricamente controladas.`,
  `Su presencia en teoría política global cuestiona la idea de que la reflexión institucional premoderna fuera monopolio grecorromano.`
 ],[
  `Comparar con Confucio expone la oposición entre confianza en formación moral y confianza en dispositivos institucionales.`,
  `Comparar con Xunzi revela un punto de partida antropológico cercano pero soluciones diferentes.`,
  `Comparar con Weber permite discutir racionalización administrativa, preservando diferencias entre legitimidad legal-racional y poder soberano legalista.`
 ],['Burton Watson, Han Feizi: Basic Writings.','Paul R. Goldin, Dao Companion to the Philosophy of Han Fei.','A. C. Graham, Disputers of the Tao.','Yuri Pines, Envisioning Eternal Empire.','Mark Edward Lewis, The Early Chinese Empires: Qin and Han.'],['Distinguir fa, shu y shi.','Explicar el problema de control de ministros.','Analizar la paradoja entre reglas impersonales y soberanía concentrada.','Evitar identificar legalismo con Estado de derecho.','Comparar Han Fei con Confucio y Weber con cautela.']),
 shangyang:PD([
  `El Libro del Señor Shang representa una teoría de transformación estatal más que una simple colección de máximas punitivas. La pregunta decisiva es cómo convertir un territorio con aristocracias, costumbres y lealtades fragmentadas en una máquina política capaz de movilizar recursos, población y guerra. La respuesta legalista asocia uniformidad normativa, incentivos, registro, agricultura y mérito militar.`,
  `La ley funciona como tecnología de igualación relativa frente a privilegios aristocráticos y al mismo tiempo como instrumento de disciplina. Promover por desempeño militar y productivo puede debilitar linajes heredados, pero no persigue autonomía individual; busca hacer a la población legible y útil para el Estado. Esta combinación impide clasificar el proyecto con categorías políticas modernas simples.`,
  `El texto contiene una filosofía histórica de la reforma. Las instituciones adecuadas cambian con las circunstancias; imitar formas antiguas por veneración puede ser políticamente irracional. El argumento ofrece una crítica frontal del tradicionalismo: la legitimidad de una regla depende de su capacidad para fortalecer orden presente, no de su antigüedad. En ese sentido, Shang Yang articula innovación institucional y autoritarismo de una manera que resulta particularmente instructiva para teoría del Estado.`
 ],[
  `La crítica de tradición sostiene que normas deben responder a circunstancias actuales. La antigüedad no es criterio suficiente de validez política.`,
  `La uniformidad legal busca volver previsibles incentivos y reducir espacios autónomos de nobles y comunidades.`,
  `Agricultura y guerra concentran población en actividades consideradas productivas para riqueza y capacidad militar.`,
  `Mérito sustituye parcialmente herencia como principio de promoción, creando nuevas jerarquías dependientes del Estado.`,
  `Responsabilidad colectiva y registro poblacional incrementan capacidad de vigilancia y movilización.`
 ],{ley:`Estándar uniforme diseñado para transformar conducta y sustituir privilegios y costumbres particulares por reglas estatales.`,Estado:`Centro de movilización de población, recursos y guerra cuya fortaleza constituye criterio principal de reforma.`,mérito:`Desempeño mensurable, sobre todo militar y productivo, usado para redistribuir rangos y debilitar aristocracia hereditaria.`,guerra:`Actividad constitutiva de competencia interestatal que justifica movilización y reforma.`,agricultura:`Base fiscal y demográfica privilegiada para sostener capacidad militar y administrativa.`},[
  `La autoría del corpus y su relación exacta con el histórico Shang Yang requieren cautela. La obra transmite una tradición legalista y no debe leerse como un manuscrito unitario de un solo momento.`,
  `La aparente igualdad ante la ley puede inducir interpretaciones modernizantes. La uniformización destruye ciertos privilegios, pero lo hace para aumentar capacidad del centro, no para garantizar derechos individuales.`,
  `La evaluación del proyecto Qin ha estado marcada por relatos confucianos posteriores que asociaron legalismo con crueldad. La historiografía reciente reconstruye más cuidadosamente sus innovaciones administrativas.`
 ],[
  `Las reformas vinculadas a Shang Yang fueron fundamentales para el ascenso de Qin y la unificación imperial.`,
  `Muchos dispositivos de registro, mérito y administración sobrevivieron a la condena ideológica del legalismo.`,
  `En teoría del Estado, la obra se utiliza para pensar centralización, legibilidad y movilización, en diálogo comparativo con procesos de state-building.`
 ],[
  `Comparar con Han Fei permite distinguir reforma socioeconómica y militar de una teoría más centrada en control de ministros.`,
  `Comparar con Tocqueville puede servir para contrastar dos análisis de centralización con valoraciones opuestas.`,
  `Comparar con James C. Scott sobre legibilidad estatal es productivo como recepción analítica, no como identidad histórica.`
 ],['J. J. L. Duyvendak, The Book of Lord Shang.','Yuri Pines, The Book of Lord Shang: Apologetics of State Power in Early China.','Mark Edward Lewis, The Early Chinese Empires.','Yuri Pines, Envisioning Eternal Empire.','A. C. Graham, Disputers of the Tao.'],['Explicar por qué reforma no equivale a liberalización.','Relacionar ley uniforme y construcción estatal.','Analizar mérito como técnica antiaristocrática y disciplinaria.','Reconstruir la filosofía legalista del cambio histórico.','Comparar Shang Yang con Han Fei.']),
 kautilya:PD([
  `El Arthaśāstra es una obra compleja de composición estratificada que sistematiza conocimientos sobre administración, economía, justicia, espionaje, diplomacia y guerra. Su unidad conceptual reside en artha: la dimensión material de poder, seguridad y prosperidad necesaria para sostener un reino. El texto no separa una “política exterior” de una “política doméstica”; tesoro, población, información y ejército forman un mismo sistema de capacidad estatal.`,
  `La fama de Kautilya como “Maquiavelo indio” es útil sólo como punto de entrada y resulta insuficiente como interpretación. El Arthaśāstra combina estrategias duras —engaño, espionaje, coerción— con una preocupación sistemática por administración, prevención de corrupción, producción y bienestar. El soberano racional no destruye la base social de su propia fortaleza. La prosperidad de los súbditos es también recurso de seguridad.`,
  `La teoría del mandala modela el entorno internacional relacionalmente. La posición de un reino depende de proximidades, capacidades y alianzas; las seis medidas de política exterior ofrecen un repertorio flexible de paz, guerra, neutralidad, preparación y alianzas. Más que una regla de “el vecino es enemigo”, el mandala es una tecnología de análisis estratégico. Para teoría política global, la obra evidencia un saber estatal altamente desarrollado fuera de la genealogía grecorromana.`
 ],[
  `La disciplina del rey busca reducir peligros de arbitrariedad y negligencia personal. El soberano también es objeto de una tecnología de gobierno.`,
  `La administración del tesoro, recursos y funcionarios muestra una concepción materialista de capacidad política.`,
  `Auditoría y vigilancia responden al problema permanente de corrupción y desvío de agentes.`,
  `El espionaje produce información sobre enemigos, funcionarios y población; saber y poder se encuentran institucionalmente vinculados.`,
  `Mandala y seis medidas de política exterior convierten relaciones interestatales en un campo de cálculo dinámico.`,
  `La coerción debe ser eficaz y proporcionada a la preservación del reino; el exceso puede generar resistencia y pérdida de recursos.`
 ],{artha:`Prosperidad, capacidad material y éxito político que constituyen una dimensión autónoma aunque relacionada con dharma y otros fines.`,mandala:`Modelo relacional del entorno interestatal que organiza aliados, enemigos y posiciones estratégicas según circunstancias.`,danda:`Autoridad coercitiva y castigo necesarios para mantener orden, cuya mala administración puede destruir legitimidad y capacidad.`,administración:`Conjunto detallado de oficinas, controles, fiscalidad y procedimientos que hacen operativo al reino.`,espionaje:`Infraestructura de información concebida como condición permanente de gobierno y estrategia.`,tesoro:`Recurso estratégico sin el cual ejército, administración y diplomacia pierden eficacia.`},[
  `La datación del Arthaśāstra es objeto de debate y la atribución simple a Chanakya/Kautilya del siglo IV a. C. no refleja necesariamente todas las capas del texto.`,
  `El problema del “realismo” exige precisión. La obra reconoce coerción y engaño, pero no es una teoría de poder desnuda de fines; orden y prosperidad limitan lo estratégicamente racional.`,
  `Las comparaciones con Maquiavelo suelen invisibilizar géneros, instituciones y tradiciones sánscritas. Una historia global debe comparar problemas y mecanismos sin convertir Europa en patrón de medida.`
 ],[
  `El Arthaśāstra fue recuperado modernamente como prueba de una tradición india de ciencia política y administración altamente sistemática.`,
  `En relaciones internacionales aparece con frecuencia como antecedente de realismo y estrategia, aunque las mejores lecturas subrayan su teoría doméstica del Estado.`,
  `Su incorporación a teoría política comparada amplía la discusión sobre capacidad estatal, inteligencia y economía del gobierno.`
 ],[
  `Comparar con Han Fei muestra dos proyectos de administración fuerte, con diferencias importantes en estructura conceptual y economía política.`,
  `Comparar con Maquiavelo permite estudiar prudencia, contingencia y conservación del poder sin adoptar la fórmula simplista de equivalencia.`,
  `Comparar con Weber permite interrogar profesionalización administrativa y control de funcionarios en contextos históricos muy distintos.`
 ],['Patrick Olivelle, King, Governance, and Law in Ancient India.','L. N. Rangarajan, Kautilya: The Arthashastra.','Roger Boesche, The First Great Political Realist.','Mark McClish, The History of the Arthashastra.','Thomas Trautmann, Kautilya and the Arthashastra.'],['Explicar artha como dimensión política.','Reconstruir relación entre administración interna y estrategia externa.','Describir mandala sin convertirlo en regla mecánica.','Analizar bienestar como componente de capacidad estatal.','Criticar con precisión la etiqueta “Maquiavelo indio”.']),
 manu:PD([
  `El Manusmriti o Leyes de Manu pertenece al género dharmaśāstra y no puede ser tratado como constitución o código estatal moderno. Su objeto es más amplio: ordenar deberes, estatus, etapas de vida, ritual, familia, propiedad y autoridad dentro de una concepción normativa del cosmos social. La política aparece como una parte de dharma, no como esfera autónoma. El rey administra y protege un orden que normativamente lo precede.`,
  `Danda, el poder de castigar, es central. La norma moral no se sostiene automáticamente; necesita una autoridad capaz de sancionar. Pero el castigo también debe ser correcto: una aplicación desmedida destruye el dharma que pretende preservar. El texto ofrece por tanto una teoría del vínculo entre normatividad y coerción donde la fuerza es necesaria pero subordinada a un orden de deberes.`,
  `La jerarquía de varna y las desigualdades de género son constitutivas y deben ser analizadas críticamente sin falsear el texto. Una lectura rigurosa distingue comprensión histórica de aprobación normativa. También debe evitar convertir Manu en descripción transparente de la sociedad india efectiva: los textos normativos prescriben, idealizan y compiten con prácticas diversas. Su importancia política reside en mostrar una forma de autoridad donde realeza, derecho, religión y jerarquía están institucionalmente entrelazados.`
 ],[
  `Dharma organiza obligaciones diferenciadas según estatus y etapa de vida. La igualdad abstracta no es el principio de la arquitectura normativa.`,
  `La teoría de la realeza presenta al rey como garante coercitivo de ese orden, no como fuente soberana de toda norma.`,
  `Danda explica por qué una sociedad moralmente ordenada requiere instituciones de sanción.`,
  `Las reglas sobre propiedad, familia y herencia revelan dimensión política de relaciones domésticas.`,
  `La articulación entre brahmanes y rey distribuye autoridad normativa y coercitiva entre posiciones distintas.`
 ],{dharma:`Orden normativo de deberes y formas correctas de vida que estructura sociedad y limita conceptualmente la función regia.`,jerarquía:`Distribución desigual de deberes, honores y sanciones según estatus; elemento constitutivo, no desviación accidental, del texto.`,ley:`Normatividad dhármica que no se identifica con legislación producida por soberanía estatal.`,realeza:`Autoridad encargada de proteger dharma, administrar justicia y ejercer coerción dentro de un orden normativo superior.`,danda:`Poder punitivo que vuelve eficaz el orden, pero cuya aplicación incorrecta puede destruirlo.`},[
  `Existe un debate fundamental sobre relación entre texto normativo y práctica social. Manu no debe usarse como fotografía de la India histórica; expresa una pretensión brahmánica de ordenar.`,
  `La recepción colonial convirtió dharmaśāstra en una fuente privilegiada para construir “derecho hindú”, alterando su función y elevando ciertos textos por encima de pluralidades jurídicas existentes.`,
  `Las jerarquías de casta y género requieren análisis normativo contemporáneo, pero ese análisis debe distinguir crítica moral de reconstrucción histórica del argumento.`
 ],[
  `La obra tuvo enorme influencia en tradiciones jurídicas y religiosas, aunque nunca monopolizó la normatividad india.`,
  `Durante el colonialismo británico fue reinterpretada como equivalente de un código legal, proceso que modificó su autoridad y recepción.`,
  `En debates contemporáneos sobre casta, nacionalismo y reforma social, Manu funciona tanto como texto de tradición como objeto de crítica radical.`
 ],[
  `Comparar con Hammurabi permite estudiar dos colecciones normativas jerárquicas con relaciones distintas entre rey y orden superior.`,
  `Comparar con Tomás de Aquino permite observar autoridades políticas inscritas en órdenes normativos que las exceden, sin suponer equivalencia entre dharma y ley natural.`,
  `Comparar con Hobbes muestra un contraste estructural: Manu subordina rey a dharma; Hobbes concentra la determinación pública de normas en soberanía.`
 ],['Patrick Olivelle, Manu’s Code of Law.','Donald R. Davis Jr., The Spirit of Hindu Law.','Robert Lingat, The Classical Law of India.','J. Duncan M. Derrett, Religion, Law and the State in India.','Nicholas Dirks, Castes of Mind, para recepción colonial de casta.'],['Explicar por qué Manu no es un código moderno.','Relacionar dharma, realeza y danda.','Analizar jerarquía como principio estructural.','Distinguir prescripción textual de práctica social.','Explicar cómo la recepción colonial transformó el estatuto del texto.'])
});