Object.assign(POSTDOC_GUIDES,{
 herodotus:PD([
  `Las Historias de Heródoto constituyen una fuente decisiva para una genealogía de la reflexión política porque convierten la diversidad de pueblos, costumbres y regímenes en objeto de comparación explícita. La política no aparece todavía como una ciencia autónoma, pero la narración histórica obliga a confrontar instituciones y valores que cada comunidad tiende a experimentar como naturales. El principio herodoteo de que los seres humanos consideran mejores sus propias costumbres introduce una conciencia de la contingencia cultural que vuelve posible preguntar por diferencias de régimen sin asumir inmediatamente un patrón único.`,
  `El célebre debate constitucional persa —monarquía, gobierno de pocos y gobierno popular— condensa argumentos que luego serán sistematizados por la filosofía griega: corrupción del uno, rivalidad oligárquica, riesgo de desorden popular y posibles virtudes de igualdad política. Su historicidad factual es secundaria para el análisis intelectual: lo relevante es que Heródoto puede colocar ese vocabulario en boca de persas y, con ello, desplazar la discusión constitucional fuera de un marco exclusivamente ateniense.`,
  `La oposición entre libertad griega y dominio persa es importante pero ambivalente. Las Historias participan de una autocomprensión helénica construida frente al imperio, y al mismo tiempo describen con admiración prácticas y capacidades de pueblos no griegos. El texto es, por eso, especialmente fértil para estudiar la relación entre comparación y etnocentrismo. Su teoría política está dispersa en relatos, discursos y etnografías: el trabajo interpretativo consiste en reconstruir cómo nomos, imperio, libertad y régimen se iluminan mutuamente.`
 ],[
  `La apertura etnográfica establece que las costumbres humanas son diversas y que la comparación produce distancia respecto de lo propio. La narración política depende de esa antropología comparativa.`,
  `El relato del ascenso persa permite estudiar monarquía, corte, administración imperial y relación entre centro y pueblos subordinados.`,
  `El debate constitucional formula ventajas y corrupciones de tres principios de gobierno y anticipa problemas de clasificación de regímenes.`,
  `Las guerras médicas articulan libertad, obediencia, deliberación y mando militar. La libertad griega se construye narrativamente en relación con amenaza imperial.`,
  `Las digresiones sobre diferentes pueblos impiden reducir la obra a propaganda binaria y muestran que la valoración política herodotea es más comparativa que simplemente chauvinista.`
 ],{nomos:`Costumbre, norma o forma de vida cuya autoridad se experimenta desde dentro de una comunidad y se vuelve visible como contingente mediante comparación.`,régimen:`Forma de distribución del mando cuya evaluación aparece narrativamente en el debate constitucional y en historias de reyes y ciudades.`,imperio:`Estructura expansiva de dominio persa que combina capacidad organizativa, diversidad subordinada y obediencia al centro.`,libertad:`Valor político asociado a la autocomprensión griega, especialmente a la ausencia de sujeción a un monarca extranjero, sin equivaler a libertad liberal moderna.`,comparación:`Procedimiento intelectual por el que costumbres y gobiernos se vuelven objetos reflexivos al ser confrontados con alternativas.`},[
  `El debate persa plantea un problema metodológico clásico: hasta qué punto los discursos de Heródoto representan voces históricas o construcciones literarias del autor. Para historia del pensamiento interesa la disponibilidad conceptual de esos argumentos, no sólo su autenticidad documental.`,
  `La relación entre griegos y “bárbaros” ha dado lugar a lecturas contrapuestas. Heródoto contribuye a la construcción de diferencia cultural, pero también desestabiliza jerarquías simples mediante admiración y crítica cruzadas.`,
  `La categoría de libertad debe contextualizarse. No es un derecho individual generalizado, sino un vocabulario político que puede coexistir con esclavitud, exclusión cívica e imperialismo griego.`
 ],[
  `Heródoto se convirtió en referencia fundacional de historiografía y, para teoría política, en antecedente de comparación de regímenes y culturas.`,
  `Su debate constitucional fue leído retrospectivamente a la luz de Platón y Aristóteles, aunque conviene invertir esa secuencia y reconocer su especificidad narrativa.`,
  `La historia global del pensamiento ha recuperado las Historias como laboratorio para estudiar representación de Persia, imperialidad y producción de identidades políticas.`
 ],[
  `Comparar con Tucídides permite distinguir dos modos de historiografía política: diversidad cultural y larga narración imperial frente a concentración analítica en guerra, poder y crisis de la polis.`,
  `Comparar con Aristóteles muestra el pasaje desde repertorios narrativos de formas de gobierno hacia una clasificación sistemática de constituciones.`,
  `Comparar con Montesquieu permite estudiar la persistencia del método comparativo y la diferencia entre etnografía histórica antigua y ciencia ilustrada de las leyes.`
 ],['Rosalind Thomas, Herodotus in Context.','François Hartog, The Mirror of Herodotus.','John Gould, Herodotus.','Sara Forsdyke, Exile, Ostracism, and Democracy.','Christopher Pelling, trabajos sobre discurso y política en Heródoto.'],['Reconstruir el debate constitucional sin tratarlo como transcripción literal.','Explicar el papel político de nomos y comparación.','Analizar la construcción de libertad griega frente a Persia.','Mostrar ambivalencias de la oposición griego/bárbaro.','Comparar la forma narrativa de teoría política herodotea con la sistematización aristotélica.']),
 thucydides:PD([
  `La Historia de la guerra del Peloponeso convierte la crisis en un método de conocimiento político. Guerra, peste, stasis y expansión imperial someten instituciones y lenguajes a condiciones extremas, revelando disposiciones que permanecían ocultas en tiempos ordinarios. Tucídides no ofrece un sistema normativo cerrado; organiza episodios y discursos de modo que el lector confronte razones de justicia, necesidad, honor, miedo e interés. Su “realismo” no consiste en afirmar que la moral es irrelevante, sino en mostrar que las razones normativas operan dentro de estructuras de poder y vulnerabilidad.`,
  `La Atenas de Pericles ocupa un lugar central. El discurso fúnebre presenta una autointerpretación democrática basada en participación, apertura, mérito y libertad privada; la peste que sigue inmediatamente muestra la fragilidad de ese ideal cuando instituciones y expectativas se descomponen. La secuencia produce una crítica más sofisticada que una simple celebración o condena de democracia.`,
  `El diálogo de los melios radicaliza la tensión entre justicia y poder. Los atenienses sostienen que, entre partes desiguales, la discusión gira alrededor de lo posible; los melios mantienen esperanza, justicia y alianzas. La destrucción de Melos y el posterior desastre siciliano no permiten una moraleja mecánica, pero colocan el imperialismo ateniense bajo una estructura trágica de exceso, cálculo y error. Para teoría política, Tucídides permite estudiar poder sin moralismo y normatividad sin ingenuidad.`
 ],[
  `La arqueología inicial propone una explicación material del crecimiento de poder griego y ateniense, vinculando riqueza, flota y capacidad coercitiva.`,
  `El discurso fúnebre formula la identidad democrática de Atenas; la peste tensiona inmediatamente ese autorretrato.`,
  `La stasis de Corcira muestra cómo guerra civil altera normas, asociaciones y significados de palabras, convirtiendo lenguaje en campo de lucha política.`,
  `El diálogo de los melios lleva a un extremo la asimetría entre poder y justicia, y obliga a pensar qué pueden hacer las razones cuando falta capacidad.`,
  `La expedición a Sicilia estudia decisión colectiva, liderazgo, información y fracaso estratégico. La democracia puede producir energía extraordinaria y errores catastróficos.`
 ],{poder:`Capacidad material y relacional cuya distribución condiciona qué razones pueden convertirse en acción efectiva.`,necesidad:`Lenguaje mediante el cual actores presentan restricciones estratégicas como límites de elección; Tucídides permite interrogar cuánto de esa necesidad es objetiva y cuánto construida.`,democracia:`Régimen ateniense mostrado tanto en su autocomprensión igualitaria como en su vulnerabilidad a liderazgo, miedo, imperialismo y decisión colectiva.`,imperio:`Relación de dominación que transforma tanto a subordinados como al demos imperial y redefine el vocabulario de seguridad.`,stasis:`Conflicto civil que desorganiza lealtades, normas y lenguaje, haciendo visible la profundidad política de las divisiones internas.`},[
  `La etiqueta “realismo” ha dominado la recepción, especialmente en relaciones internacionales, pero corre el riesgo de convertir episodios dramáticos en axiomas. Tucídides no habla con una sola voz doctrinaria y sus discursos deben leerse como construcciones analíticas.`,
  `La relación entre Pericles y democracia es discutida: liderazgo racional dentro de un régimen popular o dependencia democrática respecto de una figura excepcional. El famoso contraste con sucesores plantea un problema de instituciones y liderazgo.`,
  `El lenguaje de necesidad ateniense puede leerse como descripción de estructura internacional o como racionalización imperial. Esta ambigüedad es central para interpretaciones normativas contemporáneas.`
 ],[
  `Tucídides se convirtió en un clásico de historia, teoría de guerra y relaciones internacionales, especialmente a partir de lecturas realistas del siglo XX.`,
  `La teoría democrática lo recupera para estudiar deliberación, demagogia, liderazgo y relación entre ciudadanía e imperio.`,
  `La teoría del lenguaje político encuentra en la stasis un antecedente poderoso para pensar cómo conflictos alteran semánticas de virtud, moderación y valentía.`
 ],[
  `Comparar con Heródoto permite observar un desplazamiento desde diversidad cultural hacia una analítica concentrada de poder y causalidad de guerra.`,
  `Comparar con Maquiavelo revela afinidades en contingencia, necesidad y conflicto, sin reducir a ambos a un mismo “realismo”.`,
  `Comparar con Weber ayuda a pensar responsabilidad política y consecuencias no intencionadas; comparar con Schmitt ilumina intensidad del conflicto, pero Tucídides no ofrece el criterio amigo/enemigo como esencia de lo político.`
 ],['Simon Hornblower, A Commentary on Thucydides.','Jacqueline de Romilly, Thucydides and Athenian Imperialism.','Clifford Orwin, The Humanity of Thucydides.','Steven Forde, The Ambition to Rule.','Josiah Ober, trabajos sobre democracia ateniense y conocimiento.'],['Explicar por qué “realismo” es una recepción y no una descripción suficiente.','Analizar discurso fúnebre y peste como secuencia.','Reconstruir la stasis como crisis de lenguaje.','Interpretar el diálogo de los melios sin convertirlo en máxima atemporal.','Relacionar imperialismo, deliberación y expedición a Sicilia.']),
 sophocles:PD([
  `Antígona es una tragedia, no un tratado jurídico, y precisamente por eso ofrece una estructura teórica difícil de reducir a doctrina única. Creonte y Antígona invocan obligaciones que poseen inteligibilidad política propia: seguridad y autoridad de la polis después de una guerra civil, por un lado; deberes funerarios, parentesco y normas no creadas por decreto, por otro. La tragedia no opone simplemente un Estado ilegítimo a una conciencia individual moderna. Construye un conflicto en el que dos parcialidades se absolutizan y destruyen condiciones de convivencia.`,
  `Creonte intenta afirmar autoridad en una ciudad recién salida de conflicto fratricida. Su decreto contra Polinices no es arbitrario en sentido de carecer de toda razón: busca distinguir lealtad y traición, premiar al defensor y castigar al enemigo. El problema aparece cuando convierte esa razón política en una pretensión ilimitada de definir qué obligaciones cuentan. Antígona, a su vez, invoca una normatividad familiar y divina que tampoco puede integrarse fácilmente en deliberación cívica.`,
  `La lectura política más rica se concentra en el carácter trágico del conflicto. No siempre existe una regla superior que armonice bienes; una comunidad necesita instituciones y disposiciones capaces de reconocer límites de sus propias razones. Hegel convirtió esa estructura en paradigma de conflicto entre eticidades; feminismos posteriores releyeron género, parentesco y ciudadanía. El texto es así un laboratorio para pensar pluralidad normativa, desobediencia y violencia de la unilateralidad.`
 ],[
  `La guerra civil y el decreto establecen una situación de fundación frágil: Creonte necesita hacer visible autoridad del nuevo orden.`,
  `Antígona desobedece públicamente y se niega a traducir su obligación a cálculo de supervivencia. La acción desafía el monopolio político de definición normativa.`,
  `Ismene, Hemón y el coro presentan posiciones intermedias que muestran que el conflicto no está limitado a dos absolutos.`,
  `Tiresias introduce un límite religioso y epistémico al gobernante: la obstinación política se vuelve incapacidad de escuchar.`,
  `La catástrofe final produce conocimiento demasiado tarde. La tragedia convierte aprendizaje político en reconocimiento de irreversibilidad.`
 ],{ley:`Conjunto plural de mandatos políticos, religiosos y consuetudinarios cuya colisión desestabiliza cualquier definición unitaria del deber.`,autoridad:`Pretensión de Creonte de hacer vinculante una decisión de la polis, cuya legitimidad se erosiona al desconocer límites y otras obligaciones.`,familia:`Orden de parentesco y deber funerario que no es exterior a la política, porque organiza pertenencias y límites de ciudadanía.`,conflicto:`Choque entre razones parcialmente justificadas que no pueden ser reducidas sin resto a una regla superior.`,desobediencia:`Acción consciente que rechaza un mandato político en nombre de una obligación considerada superior, sin equivaler todavía a desobediencia civil liberal.`},[
  `La lectura hegeliana de Antígona como conflicto entre familia y Estado fue extraordinariamente influyente, pero la filología y teoría feminista han mostrado que ambos polos son más inestables de lo que esa simetría sugiere.`,
  `Interpretar a Antígona como heroína de derechos individuales proyecta categorías modernas. Su acción está anclada en parentesco, religión y honor, no en autonomía liberal.`,
  `La valoración de Creonte también divide lecturas. Convertirlo desde el inicio en tirano irracional impide comprender por qué la tragedia necesita mostrar una razón de Estado reconocible que luego se absolutiza.`
 ],[
  `Hegel hizo de Antígona una escena canónica de la eticidad en la Fenomenología del espíritu y la Filosofía del derecho.`,
  `Judith Butler y otras teóricas feministas reabrieron la cuestión del parentesco, género y límites de reconocimiento político.`,
  `La obra aparece recurrentemente en debates sobre desobediencia, memoria de muertos, violencia estatal y conflictos entre derecho positivo y obligaciones superiores.`
 ],[
  `Comparar con el Campesino elocuente permite distinguir petición inmanente dentro de jerarquía de desobediencia que rechaza la suficiencia del mandato estatal.`,
  `Comparar con Hegel muestra cómo una tragedia se transforma en modelo filosófico de conflicto ético.`,
  `Comparar con Arendt permite pensar aparición pública y responsabilidad, aunque Antígona no participa en un espacio político igualitario.`
 ],['George Steiner, Antigones.','Martha Nussbaum, The Fragility of Goodness.','Judith Butler, Antigone’s Claim.','Bonnie Honig, Antigone, Interrupted.','Jean-Pierre Vernant y Pierre Vidal-Naquet, Myth and Tragedy in Ancient Greece.'],['Explicar por qué el conflicto es trágico y no simple oposición bien/mal.','Reconstruir la razón política de Creonte y su absolutización.','Contextualizar la obligación de Antígona.','Conocer la recepción hegeliana y feminista.','Evitar equiparar el texto sin mediaciones con ley natural o desobediencia civil moderna.']),
 republic:PD([
  `La República es simultáneamente investigación sobre justicia, psicología moral, educación, conocimiento y régimen. Su arquitectura impide aislar la ciudad ideal como un programa constitucional independiente del problema inicial: Sócrates debe responder al desafío de Trasímaco y demostrar que la justicia es buena para quien la practica, no sólo una convención impuesta por los fuertes. La construcción de la ciudad en discurso amplía el alma para volver visible un orden difícil de observar en el individuo.`,
  `El argumento político depende de una tesis epistémica. Si gobernar implica orientar la comunidad hacia un bien y no simplemente agregar deseos existentes, entonces conocimiento y educación se vuelven condiciones de autoridad. El filósofo-rey no es sólo un gobernante inteligente: representa la unión problemática entre saber del bien y poder político. La alegoría de la caverna completa esa estructura al mostrar que educación no es transmisión de información, sino reorientación del deseo y de la mirada.`,
  `Los libros VIII y IX son tan importantes como la ciudad ideal. La degeneración de regímenes —timocracia, oligarquía, democracia y tiranía— vincula instituciones con tipos de carácter y con dinámicas de deseo. La democracia recibe una crítica severa por su pluralidad desordenada y por generar condiciones de ascenso del tirano, pero también es descrita como un régimen colorido, amplio y atractivo. Esa ambivalencia explica gran parte de la discusión moderna sobre Platón, desde acusaciones de totalitarismo hasta lecturas irónicas o pedagógicas.`
 ],[
  `Libro I: Céfalo, Polemarco y Trasímaco ofrecen definiciones de justicia. El fracaso de cada una prepara la necesidad de una investigación más amplia.`,
  `Libros II–IV: Glaucón radicaliza el desafío con el anillo de Giges; la ciudad surge para investigar justicia. División del trabajo, guardianes y tripartición del alma permiten definir justicia como orden.`,
  `Libro V: comunidad de mujeres y niños guardianes, igualdad educativa de mujeres guardianas y paradoja del filósofo gobernante.`,
  `Libros VI–VII: distinción entre conocimiento y opinión, idea del Bien, analogía del sol, línea dividida, caverna y currículum filosófico. La epistemología se vuelve teoría de gobierno.`,
  `Libros VIII–IX: constituciones y almas degeneran conjuntamente. La tiranía surge del extremo de libertad democrática transformada en apetito sin medida.`,
  `Libro X: crítica a imitación poética y mito de Er reinscriben justicia en una teoría de formación del alma y responsabilidad.`
 ],{justicia:`Orden funcional del alma y de la ciudad en el que cada parte realiza su tarea bajo una jerarquía adecuada; no se reduce a distribución externa.`,filósofo_rey:`Figura que combina capacidad de conocer el Bien con obligación de gobernar, condensando el problema platónico de autoridad epistémica.`,alma:`Estructura tripartita —racional, irascible y apetitiva— cuya organización es análoga, aunque no idéntica, a la constitución de la ciudad.`,educación:`Proceso de formación del deseo y reorientación cognitiva que produce guardianes y filósofos capaces de juzgar.`,régimen:`Orden político asociado a una forma de carácter y a una jerarquía de deseos; la constitución es también una psicología colectiva.`,bien:`Principio epistémico y normativo superior que hace inteligibles los objetos de conocimiento y orienta juicio político.`},[
  `La cuestión de si la Kallipolis debe leerse literalmente, como paradigma regulativo, experimento de pensamiento o construcción irónica divide la bibliografía. Una interpretación responsable debe explicar qué partes del argumento dependen de su realizabilidad.`,
  `Karl Popper convirtió a Platón en enemigo de la sociedad abierta; Strauss y otras lecturas subrayaron ironía, escritura dialógica y distancia entre Sócrates y propuestas políticas. Entre ambos extremos, la investigación contemporánea reconstruye la lógica filosófica de la ciudad sin negar sus rasgos autoritarios.`,
  `El estatuto de las mujeres guardianas es ambivalente: Platón cuestiona una división sexual de funciones políticas dentro de la clase guardiana, pero conserva una arquitectura jerárquica y eugenésica. La obra puede ser simultáneamente disruptiva en género y profundamente antiigualitaria en otros ejes.`,
  `La crítica de democracia exige contextualización ateniense. Democracia en Platón no significa constitucionalismo liberal contemporáneo; implica una estructura de libertad e igualdad que, a su juicio, debilita jerarquía del conocimiento.`
 ],[
  `La República se convirtió en uno de los centros del canon de filosofía política occidental y fue reinterpretada por neoplatónicos, cristianos, filósofos islámicos y teorías modernas de educación y Estado.`,
  `Averroes produjo una recepción política particularmente importante al comentar la República en ausencia de acceso a la Política de Aristóteles.`,
  `En el siglo XX la discusión sobre totalitarismo, utopía y epistocracia volvió a situarla en el centro de controversias sobre autoridad del conocimiento.`,
  `La teoría política contemporánea la utiliza para discutir expertocracia, formación cívica, relación entre justicia y psicología y límites de la democracia.`
 ],[
  `Comparar con Político y Leyes muestra una evolución desde el gobierno del conocimiento hacia mayor atención a medida, reglas e instituciones de segunda mejor.`,
  `Comparar con Aristóteles permite observar el desplazamiento desde unidad funcional ideal hacia pluralidad sociológica y clasificación empírica de constituciones.`,
  `Comparar con Rawls resulta útil porque ambos construyen dispositivos de abstracción para investigar justicia, aunque Rawls rechaza perfeccionismo y jerarquía epistémica platónica.`
 ],['Julia Annas, An Introduction to Plato’s Republic.','G. R. F. Ferrari, City and Soul in Plato’s Republic.','C. D. C. Reeve, Philosopher-Kings.','Melissa Lane, Plato’s Progeny.','Malcolm Schofield, Plato: Political Philosophy.','Karl Popper, The Open Society and Its Enemies, vol. I, como recepción crítica.'],['Reconstruir la respuesta a Trasímaco y Glaucón.','Explicar la analogía ciudad/alma sin identificarla mecánicamente.','Relacionar idea del Bien, caverna y autoridad política.','Dominar la secuencia de regímenes de libros VIII–IX.','Conocer las principales controversias sobre realizabilidad, democracia, género y totalitarismo.']),
 statesman:PD([
  `El Político pertenece a la fase tardía de Platón y complica la imagen de que la política correcta consiste simplemente en poner filósofos al mando. El diálogo busca definir al verdadero político mediante divisiones conceptuales, pero encuentra reiteradamente que el gobierno no puede comprenderse por una sola clasificación técnica. El mito del reinado de Cronos y la figura del tejedor introducen temporalidad, cuidado y articulación como dimensiones centrales.`,
  `La metáfora del tejido redefine la unidad política. El gobernante no elimina diferencias; entrelaza caracteres y funciones distintos, combinando firmeza y moderación. La medida adquiere un sentido normativo: existe un “justo medio” relativo a oportunidad y proporción que no puede derivarse mecánicamente de una regla fija. En este punto, el texto anticipa el problema de discreción política.`,
  `La discusión sobre ley es fundamental. El conocimiento político perfecto sería superior a reglas generales incapaces de anticipar todos los casos, pero ese conocimiento es excepcional. En su ausencia, obedecer leyes relativamente buenas resulta preferible a una discreción incompetente. El diálogo ofrece, por tanto, una teoría de segundo mejor que prepara el terreno para Leyes: la autoridad epistémica permanece como ideal, pero la institucionalización legal se vuelve imprescindible bajo condiciones humanas ordinarias.`
 ],[
  `Las divisiones iniciales intentan aislar al político de pastores, comerciantes y otras técnicas de dirección. Su dificultad revela que gobernar no es una actividad productiva simple.`,
  `El mito de Cronos distingue un mundo gobernado directamente por una divinidad de la época humana en la que los seres deben organizarse políticamente por sí mismos.`,
  `La ciencia de la medida introduce diferencia entre más/menos y medida adecuada; la política exige oportunidad cualitativa.`,
  `El tejedor combina disposiciones contrapuestas y convierte diversidad en una unidad que no elimina componentes.`,
  `La discusión sobre gobierno sin leyes y gobierno legal formula una jerarquía: saber verdadero sería superior, pero reglas se vuelven protección frente a falsos expertos.`
 ],{político:`Poseedor ideal de una ciencia práctica capaz de ordenar y articular la comunidad, distinto de quien ocupa simplemente un cargo.`,medida:`Criterio de proporción y oportunidad que impide reducir acción política a maximización o cumplimiento mecánico de reglas.`,tejido:`Metáfora de composición de caracteres y funciones heterogéneas en una unidad política.`,ley:`Regla general necesariamente imperfecta frente a casos particulares, pero indispensable cuando falta conocimiento político genuino.`,conocimiento:`Competencia práctica y normativa cuya rareza fundamenta la tensión entre gobierno experto e institucionalización.`},[
  `El diálogo plantea un problema clásico de epistocracia: si existe conocimiento político, ¿por qué debería estar limitado por reglas hechas para personas menos competentes? La respuesta platónica es menos simple de lo que sugiere República.`,
  `La interpretación del mito de Cronos divide lecturas sobre naturaleza, técnica y autonomía humana. No funciona sólo como relato cosmológico; reorganiza la cuestión del cuidado político.`,
  `La relación entre Político y Leyes es discutida: transición doctrinal, experimentación dialógica o coexistencia de niveles de análisis.`
 ],[
  `La metáfora del tejido tuvo menos recepción canónica que el filósofo-rey, pero ha sido recuperada por lecturas contemporáneas interesadas en pluralidad y articulación.`,
  `El problema ley/discreción conecta el diálogo con debates posteriores sobre prudencia, rule of law y administración experta.`,
  `Su lugar en la trilogía Teeteto–Sofista–Político lo vincula con una investigación más amplia sobre conocimiento, apariencia y clasificación.`
 ],[
  `Comparar con República permite observar continuidad del ideal epistémico y mayor reconocimiento del problema institucional.`,
  `Comparar con Leyes muestra cómo la segunda mejor solución legal se vuelve objeto central de diseño.`,
  `Comparar con Aristóteles ilumina dos concepciones de prudencia y regla: ciencia política platónica y phronesis aristotélica.`
 ],['Christopher Rowe, Plato: Statesman.','Melissa Lane, Method and Politics in Plato’s Statesman.','Malcolm Schofield, Plato: Political Philosophy.','Stanley Rosen, Plato’s Statesman.','Verity Harte y Melissa Lane, estudios sobre medida y política platónica.'],['Explicar por qué la definición del político es difícil.','Interpretar mito de Cronos y metáfora del tejido.','Dominar la relación entre medida, conocimiento y ley.','Mostrar por qué la obra complica la imagen del filósofo-rey.','Comparar Político con República y Leyes.']),
 laws:PD([
  `Leyes es la obra política más extensa de Platón y desplaza el foco hacia instituciones viables para una comunidad que no puede depender de filósofos perfectos. La conversación entre el Ateniense, Clinias y Megilo diseña Magnesia, una colonia hipotética en la que leyes, educación, religión y distribución de propiedad deben producir estabilidad y virtud. La pregunta ya no es únicamente quién sabe gobernar, sino cómo inscribir racionalidad en un orden durable.`,
  `La innovación más característica es el uso de preámbulos legales. La ley no debe limitarse a ordenar y sancionar; debe persuadir, explicar y formar. Platón combina coerción con pedagogía jurídica. Esta teoría resulta especialmente relevante porque convierte el derecho en instrumento de educación moral sin abandonar el reconocimiento de que los ciudadanos son agentes que pueden comprender razones.`,
  `La constitución de Magnesia mezcla elementos y establece controles, magistraturas, propiedad relativamente regulada y un complejo aparato educativo-religioso. El Consejo Nocturno introduce una tensión final: una instancia de conocimiento superior parece reaparecer dentro del régimen legal. Leyes no es un giro liberal; sigue siendo perfeccionista y fuertemente regulatoria. Pero ofrece una teoría institucional más fina sobre cómo una comunidad imperfecta puede aproximarse a un orden racional.`
 ],[
  `Los libros iniciales redefinen finalidad de legislación: no victoria militar, sino totalidad de virtud y paz interna.`,
  `La colonización permite diseñar instituciones desde un punto de partida relativamente nuevo, incluida distribución de lotes y límites a desigualdad.`,
  `Los preámbulos legales combinan persuasión y mandato, creando una pedagogía jurídica.`,
  `Educación musical, gimnasia, comidas comunes, religión y familia se integran en un programa de formación cívica.`,
  `La mezcla de principios constitucionales busca evitar extremos de monarquía y democracia.`,
  `El Consejo Nocturno plantea el problema de cómo conservar inteligencia filosófica dentro de un régimen gobernado por leyes.`
 ],{ley:`Institución coercitiva y pedagógica que busca ordenar conducta formando razones y hábitos, no sólo amenazando con sanción.`,preámbulo:`Discurso persuasivo que acompaña la norma y convierte legislación en educación política.`,educación:`Sistema integral mediante el cual el régimen reproduce disposiciones compatibles con virtud y estabilidad.`,moderación:`Principio de medida institucional y moral que limita extremos de riqueza, poder y deseo.`,régimen_mixto:`Combinación de elementos monárquicos y democráticos diseñada para evitar degeneración de principios puros.`,Consejo_Nocturno:`Instancia superior de reflexión que introduce nuevamente el problema de la relación entre saber filosófico y legalidad.`},[
  `La relación con República es el debate dominante: ¿Leyes representa renuncia al ideal o formulación de la “segunda mejor” ciudad? La respuesta depende de cómo se interprete continuidad del perfeccionismo platónico.`,
  `Los preámbulos han sido leídos como antecedente de legislación deliberativa y también como técnica paternalista de persuasión estatal. Su ambivalencia debe mantenerse visible.`,
  `La severidad de regulación religiosa y privada plantea problemas sobre intolerancia y control. No hay que confundir mayor institucionalismo con liberalización.`
 ],[
  `Leyes influyó en tradiciones antiguas de legislación y fue una fuente relevante para reflexiones posteriores sobre constitución mixta y educación cívica.`,
  `La teoría contemporánea del derecho ha recuperado sus preámbulos para estudiar relación entre razones públicas, pedagogía y autoridad legal.`,
  `Comparaciones con República y Político permiten reconstruir una evolución interna de la filosofía política platónica sin reducirla a una cronología lineal simple.`
 ],[
  `Comparar con República permite distinguir ciudad ideal gobernada por conocimiento y régimen legal de segunda mejor.`,
  `Comparar con Político muestra el pasaje de crítica a rigidez de la regla hacia necesidad institucional de ley bajo condiciones ordinarias.`,
  `Comparar con Montesquieu puede iluminar la atención a mezcla y condiciones sociales, aunque Platón conserva un perfeccionismo mucho más fuerte.`
 ],['Trevor Saunders, Plato: The Laws.','Malcolm Schofield, Plato: Political Philosophy.','Christopher Bobonich, Plato’s Utopia Recast.','André Laks, trabajos sobre Leyes y legislación.','Melissa Lane, trabajos sobre Platón político.'],['Explicar la idea de segunda mejor ciudad.','Analizar función de preámbulos legales.','Describir la constitución mixta de Magnesia.','Mostrar continuidad y diferencias con República y Político.','Discutir paternalismo, tolerancia y Consejo Nocturno.']),
 politics:PD([
  `La Política de Aristóteles combina filosofía normativa, sociología de regímenes e investigación comparada. Su objeto no es una constitución ideal aislada, sino la pluralidad de formas en que comunidades organizan cargos, ciudadanía y fines. La afirmación de que la polis existe “por naturaleza” debe leerse junto con una teoría teleológica: asociaciones más simples alcanzan su término en una comunidad autosuficiente orientada no sólo a vivir, sino a vivir bien.`,
  `La definición de ciudadano es deliberadamente institucional. Ciudadano en sentido pleno es quien participa en funciones deliberativas y judiciales, pero la extensión de esa condición depende del régimen. Esto permite una idea decisiva: constitución no es simplemente un documento, sino organización de cargos y definición de quién cuenta políticamente. Cambiar la constitución significa cambiar la identidad de la ciudad.`,
  `La clasificación de regímenes combina número de gobernantes y finalidad. Monarquía, aristocracia y politeia gobiernan para el bien común; tiranía, oligarquía y democracia desviada lo hacen para interés particular. Pero Aristóteles complica de inmediato la clasificación: la diferencia real entre oligarquía y democracia es riqueza/pobreza, no meramente pocos/muchos. Sus libros medios analizan mezclas, clase media, causas de revolución y soluciones institucionales, convirtiendo la obra en una teoría sorprendentemente empírica de estabilidad.`
 ],[
  `Libro I sitúa polis respecto de oikos, esclavitud y adquisición. La defensa de esclavitud natural revela límites normativos constitutivos del proyecto.`,
  `Libro II critica constituciones teóricas y reales, incluida la República platónica, defendiendo una pluralidad mayor de propiedad, familia y funciones.`,
  `Libro III define ciudadano y constitución, distingue regímenes rectos/desviados y discute soberanía de la multitud y virtud del buen hombre.`,
  `Libros IV–VI desplazan el análisis al régimen posible: mezclas, instituciones democráticas y oligárquicas, clase media y causas de estabilidad.`,
  `Libro V ofrece una teoría de revolución basada en percepciones de igualdad/desigualdad, ambición, miedo y cambios incrementales.`,
  `Libros VII–VIII regresan a la mejor vida y educación, mostrando que la ciencia política no abandona el horizonte normativo.`
 ],{polis:`Comunidad política relativamente autosuficiente orientada a una concepción sustantiva de vida buena.`,ciudadanía:`Participación en funciones deliberativas y judiciales, cuyo alcance depende de la constitución.`,constitución:`Orden de cargos y criterio de autoridad que define quién gobierna y, en sentido fuerte, qué ciudad existe.`,politeia:`Término general para constitución y, específicamente, régimen mixto que combina principios democráticos y oligárquicos.`,bien_común:`Criterio teleológico que distingue regímenes rectos de desviados.`,clase_media:`Estrato cuya posición intermedia puede reducir polarización y sostener estabilidad constitucional.`},[
  `La tesis de naturalidad de la polis se discute en relación con convencionalismo, teleología biológica y carácter histórico de instituciones.`,
  `La esclavitud natural constituye una objeción normativa y filológica central. Aristóteles intenta distinguir dominación legítima e ilegítima, pero su argumento reproduce exclusiones que deben integrarse al análisis, no relegarse a una nota.`,
  `La valoración de democracia es ambigua. Aristóteles critica gobierno de pobres para interés propio y, al mismo tiempo, reconoce capacidad agregada de una multitud y diseña mecanismos de mezcla.`,
  `El lugar de las mujeres y trabajadores en ciudadanía revela que la vida buena del ciudadano depende de una división social de trabajo que excluye a muchos de participación plena.`
 ],[
  `La Política fue decisiva para escolástica medieval, republicanismo renacentista y tradiciones de constitución mixta.`,
  `Su distinción entre ciudadanía y residencia, así como la noción de régimen, continúa informando teoría constitucional.`,
  `La teoría contemporánea recupera a Aristóteles en virtud cívica, comunitarismo, republicanismo, capacidades y análisis institucional comparado.`
 ],[
  `Comparar con Platón muestra el pasaje desde unidad ideal hacia pluralidad empírica y defensa de propiedad/familia diferenciadas.`,
  `Comparar con Polibio permite estudiar dos teorías de mezcla constitucional, una ligada a clasificación normativa y otra a ciclos históricos.`,
  `Comparar con Tocqueville revela afinidad metodológica en atender a estructura social además de instituciones formales.`
 ],['Carnes Lord, Aristotle: Politics.','Fred D. Miller Jr., Nature, Justice, and Rights in Aristotle’s Politics.','Richard Kraut, Aristotle: Political Philosophy.','C. D. C. Reeve, Aristotle on the Human Good.','Marguerite Deslauriers y Pierre Destrée, The Cambridge Companion to Aristotle’s Politics.','Josiah Ober, Political Dissent in Democratic Athens, para contexto democrático.'],['Definir polis, ciudadano y constitución con precisión.','Explicar rectos/desviados por finalidad, no sólo número.','Distinguir democracia y oligarquía por condición social.','Analizar clase media y causas de revolución.','Integrar críticamente esclavitud y exclusiones al argumento general.']),
 nicomachean:PD([
  `La Ética a Nicómaco es indispensable para teoría política porque Aristóteles concibe ética y política como partes de una misma investigación práctica sobre el bien humano. La pregunta por eudaimonia no es individualista: la vida lograda requiere hábitos, instituciones, educación y una comunidad donde ciertas actividades sean posibles. La política es “arquitectónica” porque organiza condiciones en las que los fines humanos pueden perseguirse.`,
  `La virtud moral se adquiere por habituación. Esto rompe con una concepción de moralidad como mero conocimiento de reglas: llegamos a ser justos haciendo acciones justas bajo instituciones y educadores que forman disposiciones. El régimen tiene, por tanto, una función ética profunda. La prudencia —phronesis— permite deliberar correctamente sobre medios y circunstancias cuando no existe algoritmo suficiente.`,
  `Los libros V, VIII y IX poseen especial relevancia política. La justicia distingue dimensiones distributivas y correctivas, mientras amistad —philia— aparece como vínculo que sostiene comunidades incluso más allá de la justicia formal. Aristóteles no propone reemplazar instituciones por amistad; muestra que orden normativo depende también de disposiciones relacionales. La obra aporta así una teoría de agencia política, juicio práctico y formación que complementa la arquitectura constitucional de Política.`
 ],[
  `Libro I establece eudaimonia como actividad conforme a virtud a lo largo de una vida completa y sitúa política como ciencia práctica superior.`,
  `Libros II–IV explican formación de virtudes mediante hábito y doctrina del término medio, entendida como adecuación racional a circunstancias.`,
  `Libro V analiza justicia general y particular, incluyendo distribución proporcional y corrección de transacciones.`,
  `Libro VI distingue saberes y desarrolla phronesis como virtud intelectual práctica inseparable de experiencia.`,
  `Libros VIII–IX examinan amistad, reciprocidad y comunidad.`,
  `Libro X vuelve sobre placer, contemplación y necesidad de legislación educativa, enlazando explícitamente con Política.`
 ],{virtud:`Disposición estable adquirida mediante práctica que permite sentir y actuar de manera adecuada, no simple obediencia a reglas.`,prudencia:`Capacidad racional práctica de deliberar correctamente sobre bienes humanos en situaciones contingentes.`,justicia:`Virtud completa respecto de otros y, en sentido particular, conjunto de criterios distributivos y correctivos.`,bien_común:`Horizonte político en el que las condiciones de florecimiento no pueden reducirse a bienes privados aislados.`,amistad:`Relación de reciprocidad y reconocimiento cuya dimensión cívica contribuye a cohesión de comunidades.`,eudaimonia:`Florecimiento o vida lograda entendida como actividad excelente, no como estado subjetivo de satisfacción.`},[
  `El llamado “término medio” suele trivializarse como moderación aritmética. Aristóteles insiste en que es relativo a nosotros y determinado por razón prudente.`,
  `La relación entre vida política y contemplativa genera una tensión clásica: si la contemplación es el bien más alto, ¿qué estatuto tiene la vida cívica?`,
  `La justicia distributiva aristotélica presupone criterios de mérito discutibles y no equivale a igualdad distributiva contemporánea.`,
  `La dependencia de virtud respecto de condiciones externas plantea preguntas sobre suerte, desigualdad y acceso a vida buena.`
 ],[
  `La obra estructuró buena parte de ética de virtud antigua, medieval y contemporánea.`,
  `Tomás de Aquino integró su teoría de virtud y prudencia en una arquitectura cristiana de ley y bien común.`,
  `El resurgimiento contemporáneo de ética de virtud y capacidades volvió a colocar a Aristóteles en debates de justicia, ciudadanía y educación.`
 ],[
  `Comparar con Política muestra que formación moral y constitución son inseparables.`,
  `Comparar con Kant o Rawls permite contrastar perfeccionismo de la vida buena con teorías centradas en autonomía o justicia procedimental.`,
  `Comparar con Confucio es productivo para estudiar habituación, ritual y formación del carácter en dos tradiciones diferentes.`
 ],['Terence Irwin, Aristotle: Nicomachean Ethics.','Sarah Broadie, Ethics with Aristotle.','Richard Kraut, Aristotle on the Human Good.','Martha Nussbaum, The Fragility of Goodness.','John Cooper, Reason and Human Good in Aristotle.'],['Definir eudaimonia como actividad, no emoción.','Explicar habituación y término medio.','Distinguir justicia general, distributiva y correctiva.','Definir phronesis y su relación con política.','Relacionar amistad y comunidad sin reducir instituciones a vínculos personales.']),
 xenophon:PD([
  `La Ciropedia de Jenofonte es un texto híbrido: biografía idealizada, reflexión socrática, tratado sobre liderazgo y narración imperial. Su Ciro no debe confundirse con una reconstrucción histórica transparente del fundador aqueménida. Jenofonte utiliza Persia para pensar cómo un gobernante puede obtener obediencia voluntaria de poblaciones diversas y cómo educación, ejemplo, recompensa y organización producen autoridad.`,
  `La cuestión del liderazgo atraviesa toda la obra. Ciro combina autocontrol, capacidad militar, generosidad calculada y atención a motivaciones de subordinados. La obediencia no surge sólo del miedo; el gobernante diseña incentivos y relaciones de confianza. Esto convierte la Ciropedia en una teoría temprana de conducción y administración de imperio.`,
  `Pero el final introduce una ambigüedad decisiva. Después de la muerte de Ciro, el orden persa se deteriora. ¿La grandeza dependía demasiado de una persona excepcional? Si es así, el éxito del líder revela la debilidad institucional del sistema. Esta tensión entre liderazgo personal e instituciones convierte a Jenofonte en un interlocutor más complejo que el simple elogio monárquico.`
 ],[
  `La educación persa inicial presenta disciplina, justicia y competencia como bases de formación política.`,
  `El ascenso de Ciro muestra cómo liderazgo militar se convierte en capacidad de coalición y mando sobre diversos pueblos.`,
  `La distribución de honores y recompensas revela una psicología política de incentivos.`,
  `Banquetes, corte y ceremonial institucionalizan distancias y proximidades alrededor del soberano.`,
  `El epílogo contrasta virtud de Ciro con decadencia posterior y abre el problema de sucesión e institucionalización.`
 ],{liderazgo:`Capacidad de producir obediencia combinando ejemplo, juicio, incentivos, afectos y organización.`,imperio:`Gobierno de poblaciones heterogéneas cuya estabilidad depende de articulación entre fuerza, prestigio y administración.`,educación:`Formación disciplinaria que produce hábitos de mando y obediencia antes de asumir cargos.`,obediencia:`Resultado político que puede provenir de coerción, admiración, reciprocidad e incentivos.`,sucesión:`Problema implícito del texto: un orden dependiente de un individuo excepcional enfrenta fragilidad cuando esa persona desaparece.`},[
  `La ironía de Jenofonte divide interpretaciones. El epílogo puede leerse como refutación parcial del éxito aparente de Ciro o como simple contraste histórico.`,
  `La relación con el Sócrates jenofóntico permite leer liderazgo como extensión de autocontrol y conocimiento práctico.`,
  `El uso de Persia plantea un problema de alteridad comparable al de Heródoto: el imperio extranjero funciona como espejo para debates griegos, pero no es pura ficción sin referente.`
 ],[
  `La Ciropedia influyó en teorías antiguas y renacentistas de educación principesca y liderazgo.`,
  `Maquiavelo conoció a Jenofonte y su figura de Ciro aparece en El príncipe como ejemplo de fundador.`,
  `La obra continúa siendo estudiada en teoría del liderazgo, imperio y tradición socrática.`
 ],[
  `Comparar con Platón permite estudiar dos respuestas socráticas al problema de educación política.`,
  `Comparar con Maquiavelo ilumina el uso posterior de Ciro como fundador dotado de virtù.`,
  `Comparar con Weber permite contrastar liderazgo personal y rutinización institucional.`
 ],['Wayne Ambler, Xenophon: The Education of Cyrus.','Christopher Nadon, Xenophon’s Prince.','Vivienne Gray, Xenophon’s Mirror of Princes.','John Dillery, Xenophon and the History of His Times.','Paul Rahe, Republics Ancient and Modern, para recepción republicana.'],['Explicar el carácter híbrido de la Ciropedia.','Analizar mecanismos de obediencia más allá del miedo.','Reconstruir el problema de sucesión.','Discutir la posibilidad de ironía en el epílogo.','Comparar Ciro con el fundador maquiaveliano.'])
});