Object.assign(POSTDOC_GUIDES,{
 garcia:PD([
  `Forma valor y forma comunidad es una investigación marxista escrita en condiciones de encarcelamiento y atravesada por el problema de cómo pensar las comunidades andinas sin reducirlas a residuos precapitalistas destinados a desaparecer. García Linera vuelve a la arquitectura lógica de El capital y a los manuscritos de Marx para distinguir formas de sociabilidad organizadas por el valor de aquellas donde el vínculo comunitario conserva principios de reproducción no subsumidos plenamente por la abstracción mercantil. La pregunta no es etnográfica en sentido estrecho: concierne a las posibilidades políticas contenidas en formas sociales coexistentes con el capitalismo.`,
  `La forma valor expresa una socialidad en la que trabajos privados se relacionan mediante intercambio y adquieren equivalencia abstracta. El valor no es una cosa adherida a mercancías, sino una forma social históricamente específica. La expansión capitalista tiende a reorganizar trabajo, propiedad y cooperación bajo esa lógica. García Linera insiste en reconstruir el concepto con rigor para evitar un marxismo que convierta “capitalismo” en simple presencia de empresarios o dinero.`,
  `La forma comunidad designa una lógica de reproducción colectiva donde acceso a recursos, trabajo y pertenencia se organizan mediante relaciones comunitarias no reducibles al intercambio mercantil individual. No se trata de una comunidad pura, inmóvil o exterior al mercado. Las comunidades reales están atravesadas por Estado, mercancía, desigualdad y colonialismo. La categoría busca identificar una forma de socialidad que persiste, se transforma y puede entrar en contradicción con la valorización.`,
  `El problema político surge de esa coexistencia. Si la comunidad fuera sólo pasado, el socialismo tendría que esperar su completa destrucción y reconstruir cooperación desde cero. García Linera recupera, en diálogo con los escritos tardíos de Marx sobre la comuna rural rusa, la posibilidad de que formas comunitarias constituyan puntos de apoyo para una transformación no lineal. Esto cuestiona versiones evolucionistas del marxismo que exigen repetir una secuencia europea completa.`,
  `La obra debe distinguirse de los desarrollos posteriores de García Linera sobre movimientos indígenas, multitud y Estado. En los años dos mil, su teoría se orientará hacia crisis estatal, bloques de poder, Estado plurinacional y tensiones entre lógica estatal y movimientos. Forma valor y forma comunidad proporciona una base ontológica y económica para esa trayectoria, pero no contiene de antemano todas sus conclusiones políticas.`,
  `El concepto de comunidad posee también riesgos. Puede romantizar solidaridades internas e invisibilizar jerarquías de género, edad o autoridad. El mérito del texto está en intentar una reconstrucción formal y no costumbrista: comunidad no vale por ser ancestral, sino porque organiza de otro modo la relación entre productores, condiciones de producción y colectividad. Su importancia para teoría política reside en pensar pluralidad de formas sociales dentro de una misma formación histórica.`
 ],[
  `La obra retorna a la teoría marxiana de valor para definir el tipo de relación social específico de la mercancía.`,
  `La abstracción del trabajo se explica como proceso social y no sólo operación mental del economista.`,
  `La comunidad se reconstruye desde relaciones de producción y reproducción, evitando reducirla a identidad cultural.`,
  `Las formas comunitarias andinas aparecen históricamente atravesadas por colonialismo, Estado y mercado, no como exterior puro.`,
  `Los escritos tardíos de Marx sobre comunidades rurales permiten cuestionar una filosofía unilineal de historia.`,
  `La coexistencia forma valor/forma comunidad abre la posibilidad de transiciones multilineales y de potencias no capitalistas presentes.`,
  `El problema de articulación entre comunidad y proyecto socialista reemplaza la expectativa de una proletarización total previa.`,
  `La trayectoria posterior hacia teoría del Estado debe comprenderse como nueva fase y no como contenido ya acabado en 1995.`
 ],{forma_valor:`Modo específicamente capitalista de socialidad en el que trabajos privados se relacionan mediante equivalencia mercantil y abstracción de valor.`,forma_comunidad:`Principio de organización colectiva de producción y reproducción donde pertenencia y cooperación no se reducen a intercambio individual de mercancías.`,comunidad:`Relación social histórica y transformable, no identidad cultural pura ni supervivencia congelada del pasado.`,trabajo_abstracto:`Forma social por la que trabajos cualitativamente distintos cuentan como magnitudes comparables dentro del intercambio.`,Marx_tardío:`Conjunto de escritos sobre Rusia y formas comunales utilizado para cuestionar lecturas unilineales del desarrollo histórico.`,multilinealidad:`Posibilidad de trayectorias históricas distintas que no requieren reproducir secuencias europeas de disolución comunitaria.`,socialismo:`Transformación que puede articular capacidades colectivas existentes en vez de presuponer que toda comunidad debe ser destruida por capitalismo.`},[
  `La distinción forma valor/forma comunidad puede parecer demasiado binaria si se aplica empíricamente sin mediaciones. El propio problema histórico es su articulación e hibridación.`,
  `La recuperación de comunidad fue criticada por riesgo de romanticismo. Una lectura rigurosa debe examinar desigualdades internas y no convertir propiedad comunal en armonía social.`,
  `El uso de Marx tardío forma parte de un debate internacional sobre multilinealidad. No prueba que Marx abandonara toda teoría de capitalismo, sino que su reflexión sobre trayectorias no occidentales fue más abierta que el marxismo evolutivo posterior.`,
  `La relación entre teoría temprana y función posterior de García Linera como vicepresidente genera recepciones fuertemente politizadas. Conviene separar reconstrucción conceptual del libro y evaluación de políticas gubernamentales.`,
  `La categoría de comunidad andina puede adquirir sentidos diferentes en sindicatos campesinos, ayllus y movimientos indígenas; no debe tratarse como una unidad sociológica.`
 ],[
  `La obra se convirtió en referencia del marxismo boliviano y de debates sobre comunidad, valor y movimientos indígenas.`,
  `García Linera desarrolló posteriormente conceptos de multitud, empate catastrófico, crisis estatal y Estado plurinacional en diálogo con la experiencia boliviana.`,
  `El retorno latinoamericano a los escritos tardíos de Marx alimentó críticas del marxismo unilineal.`,
  `Debates sobre comunes y formas comunitarias contemporáneas encuentran afinidades, aunque no deben borrar la especificidad andina.`,
  `La teoría política regional lo lee en diálogo con Mariátegui y Zavaleta como una genealogía andina de heterogeneidad y transformación.`
 ],[
  `Comparar con Marx permite reconstruir el fundamento de forma valor y el debate sobre comunidades rurales.`,
  `Comparar con Mariátegui muestra dos apropiaciones marxistas de potencialidades comunitarias andinas.`,
  `Comparar con Zavaleta permite conectar coexistencia de formas y sociedad abigarrada.`,
  `Comparar con Quijano introduce raza y colonialidad como dimensiones no agotadas por la forma valor.`,
  `Comparar con Dussel permite distinguir comunidad como forma social y comunidad como fuente normativa de potentia política.`
 ],['Álvaro García Linera, Forma valor y forma comunidad.','Álvaro García Linera, La potencia plebeya.','Karl Marx, borradores y cartas sobre Vera Zasulich.','Luis Tapia, trabajos sobre García Linera, Zavaleta y política boliviana.','Raquel Gutiérrez Aguilar, Los ritmos del Pachakuti.','Massimo Modonesi, trabajos sobre movimientos y autonomía en América Latina.'],['Definir forma valor desde relaciones sociales y no como “precio”.','Definir forma comunidad sin esencialismo.','Explicar el papel de Marx tardío.','Analizar multilinealidad histórica.','Discutir el riesgo de romanticizar comunidad.','Distinguir esta obra de la teoría estatal posterior.','Comparar con Mariátegui y Zavaleta.']),
 quijano:PD([
  `“Colonialidad del poder, eurocentrismo y América Latina” formula una de las categorías más influyentes del pensamiento social contemporáneo: colonialidad no es sinónimo de colonialismo. El colonialismo refiere a una estructura explícita de dominación político-territorial; la colonialidad nombra patrones de clasificación, trabajo, autoridad y conocimiento que se forman con la conquista de América y continúan después de las independencias. La modernidad mundial y la colonialidad son, en esta tesis, procesos co-constitutivos.`,
  `La raza ocupa un lugar estructural. Quijano sostiene que la conquista produjo y globalizó una clasificación social que vinculó identidades racializadas con posiciones de trabajo y autoridad. Raza no es un prejuicio cultural añadido posteriormente al capitalismo: participa de la organización histórica de trabajo asalariado, esclavitud, servidumbre y producción mercantil dentro de un sistema mundial.`,
  `El eurocentrismo es una perspectiva de conocimiento que presenta una trayectoria europea particular como secuencia universal de humanidad. Categorías duales —tradicional/moderno, primitivo/civilizado, Oriente/Occidente— organizan temporalmente diferencias espaciales, colocando a otros pueblos en un pasado de Europa. La crítica epistemológica no rechaza conocimiento europeo por su lugar de origen; cuestiona su elevación acrítica a patrón único.`,
  `Quijano discute también la nación y el Estado latinoamericanos. Las independencias fueron procesos de descolonización política incompleta porque élites criollas mantuvieron clasificaciones raciales y excluyeron mayorías indígenas y afrodescendientes de una ciudadanía materialmente igual. La nación aparece así como proyecto conflictivo bloqueado por colonialidad interna.`,
  `Su relación con Marx es crítica y productiva. Quijano conserva capitalismo y explotación, pero rechaza la idea de que todas las formas de control del trabajo sean etapas sucesivas. En el sistema-mundo colonial-moderno pueden articularse simultáneamente salario, esclavitud, reciprocidad y servidumbre. Esta heterogeneidad histórico-estructural aproxima su análisis a debates latinoamericanos previos sin identificarse con ellos.`,
  `La colonialidad fue ampliada hacia saber, ser, género y naturaleza por otros autores. Es importante distinguir la formulación quijaniana de ese campo posterior. Críticas feministas, especialmente María Lugones, argumentaron que el patrón colonial también reconfigura género de formas que la formulación original no capta suficientemente. El concepto sigue siendo potente si mantiene especificidad histórica y no se convierte en etiqueta para toda desigualdad.`
 ],[
  `La conquista de América se presenta como momento constitutivo de un patrón mundial de poder.`,
  `La idea de raza organiza clasificación de población y se articula con división del trabajo.`,
  `Capitalismo mundial combina múltiples formas de control laboral en una misma estructura, no una secuencia pura.`,
  `Europa se constituye como identidad geocultural y centro de control del nuevo patrón.`,
  `El eurocentrismo reorganiza tiempo histórico de otros pueblos como atraso respecto de Europa.`,
  `Las independencias latinoamericanas no desmantelan la clasificación colonial y producen Estados nacionales limitados.`,
  `La democratización exige descolonización de relaciones de poder y de producción de conocimiento.`,
  `La crítica del dualismo abre una epistemología atenta a heterogeneidad histórico-estructural.`
 ],{colonialidad_del_poder:`Patrón duradero de clasificación racial, control del trabajo, autoridad y conocimiento nacido con colonialismo y persistente tras su final formal.`,raza:`Clasificación social moderna producida en la conquista y articulada materialmente con trabajo, ciudadanía y poder.`,eurocentrismo:`Perspectiva que convierte la experiencia histórica europea en patrón universal y ubica otras trayectorias en una temporalidad de atraso.`,modernidad:`Proceso mundial constituido conjuntamente con conquista y colonialidad, no desarrollo interno autónomo de Europa.`,heterogeneidad_histórico_estructural:`Articulación simultánea de formas sociales y laborales distintas dentro de un mismo patrón de poder.`,Estado_nación:`Forma cuya democratización latinoamericana queda limitada cuando ciudadanía convive con jerarquías raciales coloniales.`,descolonización:`Transformación de patrones de poder y conocimiento que excede independencia política formal.`},[
  `El origen y uso histórico de “raza” es más complejo que una fecha única de invención. La tesis quijaniana debe entenderse como análisis de sistematización colonial de clasificación, no como afirmación filológica simplista.`,
  `La co-constitución modernidad/colonialidad ha sido criticada cuando parece atribuir toda modernidad a 1492 o borrar procesos previos. Su función teórica es descentralizar narrativas internas de Europa.`,
  `María Lugones sostiene que Quijano trata género como dimensión insuficientemente transformada por colonialidad y propone “colonialidad de género”.`,
  `El giro decolonial posterior amplió colonialidad hacia múltiples campos y puede alejarse de la economía política originalmente importante para Quijano.`,
  `Existe afinidad con teoría de sistema-mundo, pero Quijano enfatiza clasificación racial y heterogeneidad más allá de una división centro/periferia económica.`
 ],[
  `La colonialidad del poder se convirtió en uno de los conceptos latinoamericanos de mayor circulación global.`,
  `Walter Mignolo, Nelson Maldonado-Torres y otros desarrollaron un “giro decolonial” con categorías propias.`,
  `María Lugones reformuló el campo desde feminismo decolonial.`,
  `Debates sobre universidad, conocimiento y currículum utilizan la crítica del eurocentrismo.`,
  `La teoría de raza global dialoga crecientemente con Quijano, Du Bois y Mills en estudios comparativos.`
 ],[
  `Comparar con Prebisch permite ver qué añade raza y conocimiento al eje centro-periferia.`,
  `Comparar con Cardoso-Faletto muestra el paso de dependencia socioeconómica a un patrón más amplio de poder.`,
  `Comparar con Mariátegui revela antecedentes peruanos de tierra, indígena y colonialidad.`,
  `Comparar con Mills racial permite contrastar contrato racial y colonialidad como teorías globales de supremacía.`,
  `Comparar con Roig y Dussel sitúa tres estrategias diferentes de crítica al eurocentrismo.`
 ],['Aníbal Quijano, “Colonialidad del poder, eurocentrismo y América Latina”.','Aníbal Quijano, Cuestiones y horizontes.','Edgardo Lander, ed., La colonialidad del saber.','Walter Mignolo, Local Histories/Global Designs.','María Lugones, “Heterosexualism and the Colonial/Modern Gender System”.','César Germaná, trabajos sobre Aníbal Quijano.'],['Distinguir colonialidad de colonialismo.','Explicar raza-trabajo como articulación material.','Definir eurocentrismo como perspectiva histórica.','Analizar heterogeneidad de formas de trabajo.','Explicar límites del Estado-nación latinoamericano.','Conocer críticas feministas y expansión del giro decolonial.','Comparar Quijano con Prebisch, Mills y Dussel.']),
 laclau:PD([
  `La razón populista intenta construir una teoría formal de cómo se constituye un “pueblo”. Laclau rechaza definiciones de populismo basadas en una ideología, una clase social o un conjunto fijo de políticas. El populismo es una lógica de articulación política: aparece cuando demandas heterogéneas que no son absorbidas diferencialmente por instituciones comienzan a reconocerse como equivalentes frente a un límite común y construyen una frontera entre “pueblo” y poder.`,
  `La unidad mínima es la demanda social. Una demanda satisfecha puede permanecer particular; múltiples demandas insatisfechas pueden formar una cadena de equivalencias. La equivalencia no elimina sus diferencias: las conecta porque comparten una relación negativa con un orden que no responde. Esa cadena necesita una representación común, y una demanda o significante particular puede asumir la función de representar la totalidad. Allí aparece el “significante vacío”.`,
  `Vacío no significa sin significado. Un término como “pueblo”, “justicia” u “orden” se vacía parcialmente de su particularidad para condensar demandas diversas. Ningún significante puede representar perfectamente una totalidad heterogénea; la representación es constitutivamente inadecuada y por eso política. La hegemonía consiste precisamente en que una particularidad asuma una función universal contingente.`,
  `El afecto y el liderazgo ocupan un lugar que teorías puramente racionalistas tienden a excluir. La identificación con un nombre o líder contribuye a estabilizar la cadena. Laclau no sostiene que populismo requiera necesariamente un líder carismático individual, pero reconoce que la investidura afectiva es indispensable para la construcción de identidades colectivas.`,
  `La teoría deriva de una trayectoria postmarxista iniciada con Hegemonía y estrategia socialista. Laclau abandona la idea de que una clase posea por posición económica una misión política necesaria. Las identidades se construyen discursivamente mediante articulación. “Discurso” no significa sólo lenguaje: refiere a una totalidad relacional de prácticas y significados.`,
  `La razón populista generó un campo global de estudios del populismo, pero también objeciones. Si populismo es una lógica tan general de construcción de pueblo, puede volverse difícil distinguir populismo de política tout court. Además, la teoría es formalmente neutral respecto del contenido: un pueblo puede construirse en direcciones democráticas o excluyentes. Por eso una teoría de populismo no sustituye una teoría normativa de democracia.`
 ],[
  `Laclau comienza criticando la literatura que trata populismo como vaguedad, patología o fenómeno social residual.`,
  `La demanda democrática es inicialmente particular y dirigida al sistema institucional.`,
  `La acumulación de demandas insatisfechas puede producir una cadena equivalencial.`,
  `La frontera antagónica divide un campo entre pueblo emergente y poder identificado como responsable.`,
  `Un significante particular asume representación de la cadena y se vuelve tendencialmente vacío.`,
  `La hegemonía nombra esa universalización contingente de una particularidad.`,
  `El afecto y la nominación estabilizan identidad popular.`,
  `La tensión entre lógica equivalencial y diferencial explica grados de populización o institucionalización de un orden.`
 ],{demanda:`Unidad de articulación que puede ser absorbida institucionalmente o entrar en relación equivalencial con otras demandas insatisfechas.`,cadena_de_equivalencias:`Relación que conecta demandas distintas mediante una oposición compartida sin eliminar completamente sus particularidades.`,significante_vacío:`Nombre particular parcialmente vaciado de contenido propio para representar una totalidad heterogénea imposible de cerrar.`,hegemonía:`Operación por la que una particularidad asume contingentemente una función universal de representación.`,pueblo:`Sujeto político construido mediante articulación y frontera, no grupo sociológico preexistente.`,populismo:`Lógica de construcción de un pueblo mediante equivalencias, frontera y representación, sin contenido ideológico fijo.`,antagonismo:`Límite relacional que impide una identidad social plenamente cerrada y divide el espacio político.`,afecto:`Investidura libidinal necesaria para que nombres e identidades políticas adquieran fuerza colectiva.`},[
  `La amplitud de la definición hace difícil distinguir populismo de otras construcciones hegemónicas. Laclau responde hablando de grados, pero la frontera conceptual permanece discutida.`,
  `La neutralidad formal permite analizar populismos de izquierda y derecha, pero obliga a buscar criterios normativos fuera del concepto de populismo.`,
  `Críticos marxistas sostienen que el abandono de determinación de clase debilita explicación material. Laclau responde que ninguna posición social produce automáticamente una identidad política.`,
  `La centralidad del líder ha sido discutida por casos de populismo más organizacional o descentralizado. La teoría permite nombres colectivos, aunque muchos ejemplos privilegian liderazgo.`,
  `El término “discurso” es frecuentemente banalizado como retórica; en Laclau posee un sentido ontológico-relacional más amplio.`
 ],[
  `La razón populista se convirtió en referencia central de estudios globales sobre populismo.`,
  `Mouffe desarrolló una estrategia de populismo de izquierda apoyada en la lógica hegemónica.`,
  `Debates latinoamericanos utilizaron la teoría para reinterpretar peronismo, chavismo y otros movimientos, con resultados polémicos.`,
  `Críticos como Panizza, Arditi y enfoques ideacionales dialogaron con Laclau desde definiciones alternativas.`,
  `La teoría de hegemonía influyó más allá del populismo en análisis de identidades y discurso político.`
 ],[
  `Comparar con Gramsci muestra el origen y la transformación postmarxista de hegemonía.`,
  `Comparar con Perón permite distinguir un objeto histórico/doctrinario de la teoría formal que lo toma como caso.`,
  `Comparar con Mouffe muestra cómo una ontología hegemónica se convierte en una teoría normativa agonista.`,
  `Comparar con Rancière permite contrastar pueblo como cadena equivalencial y parte sin parte.`,
  `Comparar con Schmitt ilumina la frontera nosotros/ellos, pero Laclau no reduce política a enemigo existencial.`
 ],['Ernesto Laclau, La razón populista.','Ernesto Laclau y Chantal Mouffe, Hegemonía y estrategia socialista.','David Howarth, Discourse.','Simon Critchley y Oliver Marchart, eds., Laclau: A Critical Reader.','Francisco Panizza, ed., Populism and the Mirror of Democracy.','Benjamín Arditi, Politics on the Edges of Liberalism.'],['Explicar demanda y cadena de equivalencias.','Definir significante vacío sin decir “palabra sin contenido”.','Explicar hegemonía como universalización contingente.','Analizar papel de afecto y liderazgo.','Distinguir discurso de mera retórica.','Discutir la amplitud y neutralidad normativa del populismo.','Comparar con Gramsci, Perón y Mouffe.']),
 dussel:PD([
  `20 tesis de política ofrece una reconstrucción normativa de poder desde la comunidad política. Dussel intenta invertir la imagen según la cual el poder pertenece originariamente a gobernantes. La potentia es la capacidad política de una comunidad de reproducir y desarrollar su vida mediante acción común; la potestas es la institucionalización necesaria de esa capacidad en funciones, cargos y sistemas. Las instituciones no crean ex nihilo el poder: lo ejercen de manera delegada.`,
  `Esta distinción permite una teoría de “fetichización”. La potestas se fetichiza cuando autoridades olvidan su carácter delegado y se presentan como fuente autónoma, utilizando instituciones para su propia reproducción. El poder obediencial es la figura normativa opuesta: quien manda debe mandar obedeciendo al poder originario de la comunidad. La fórmula dialoga con experiencias indígenas y movimientos latinoamericanos sin reducirse a ellas.`,
  `Dussel rechaza una concepción puramente negativa del poder. La potentia es afirmativa y productiva: antes que dominación, existe capacidad colectiva de crear instituciones. El problema aparece cuando esa capacidad se escinde de sus mediaciones. Esta tesis permite criticar tanto anarquismo que desconfía de toda institución como estatismo que identifica comunidad con aparato.`,
  `Las tesis distinguen principios material, democrático y de factibilidad. Una política legítima debe reproducir la vida, incorporar participación de afectados y actuar dentro de posibilidades institucionales reales. Ningún principio aislado basta: una decisión materialmente beneficiosa sin participación puede ser autoritaria; una decisión procedimental sin condiciones de vida puede ser vacía; una norma imposible carece de mediación práctica.`,
  `El “pueblo” emerge especialmente cuando una parte de la comunidad sufre exclusión y articula demandas frente a un bloque de poder. Dussel dialoga con Laclau, pero intenta conservar un criterio material de víctimas y necesidades que impida que cualquier articulación hegemónica sea normativamente equivalente. Pueblo no es toda comunidad política ni una esencia nacional.`,
  `La filosofía de la liberación aporta el trasfondo ético: la exterioridad de víctimas revela límites del sistema vigente. Sin embargo, traducir “víctima” a categorías políticas puede generar paternalismo si se habla por quienes padecen exclusión. El poder obediencial exige precisamente que organización y representación permanezcan vinculadas a participación.`,
  `20 tesis es deliberadamente sintético y programático. Para profundizarlo hay que leer Ética de la liberación y Política de la liberación. Su importancia en el Atlas reside en formular una teoría normativa sistemática desde América Latina que aspira a universalidad y discute de igual a igual con el canon de soberanía, democracia e instituciones.`
 ],[
  `La potentia define el poder originario de la comunidad política como capacidad colectiva.`,
  `La potestas institucionaliza esa capacidad porque una comunidad compleja no puede actuar permanentemente sin mediaciones.`,
  `La fetichización ocurre cuando la institución se autonomiza y trata al pueblo como objeto.`,
  `El poder obediencial redefine autoridad como servicio delegado.`,
  `El principio material exige producir y reproducir vida humana en comunidad.`,
  `El principio democrático exige participación simétrica de afectados en formación de legitimidad.`,
  `El principio de factibilidad introduce límites estratégicos e institucionales a la acción.`,
  `El pueblo se constituye como actor crítico desde sectores excluidos frente a un orden fetichizado.`,
  `La transformación institucional debe evitar tanto conservación absoluta como negación anarquista de toda mediación.`
 ],{potentia:`Capacidad política originaria de la comunidad para querer, decidir y reproducir colectivamente su vida.`,potestas:`Poder institucional delegado que organiza funciones y decisiones y cuya legitimidad depende de permanecer conectado con potentia.`,fetichización:`Inversión por la cual instituciones o gobernantes se presentan como fuente autónoma del poder que en realidad reciben de comunidad.`,poder_obediencial:`Ejercicio de autoridad como servicio responsable ante la comunidad y no como apropiación del mando.`,pueblo:`Bloque político crítico que puede emerger desde sectores excluidos; no idéntico a toda población ni esencia nacional.`,principio_material:`Exigencia de que política haga posible producción y reproducción de vida.`,principio_democrático:`Exigencia de participación y legitimidad de afectados.`,factibilidad:`Condición estratégica que exige que normas y proyectos puedan realizarse mediante medios e instituciones posibles.`},[
  `La relación entre potentia y potestas puede idealizar una “comunidad” unificada. Las comunidades reales contienen conflictos, minorías y desigualdades; el concepto necesita una teoría de pluralismo interno.`,
  `“Mandar obedeciendo” puede convertirse en fórmula retórica si no se especifican mecanismos de rendición de cuentas, revocación y participación.`,
  `El principio material introduce un criterio normativo fuerte, pero surge el problema de quién interpreta qué requiere la reproducción de vida.`,
  `Dussel dialoga con Laclau sobre pueblo y hegemonía, pero rechaza una formalización que no distinga materialmente proyectos. Esta diferencia es clave.`,
  `La filosofía de liberación utiliza “exterioridad” en un sentido levinasiano y material que no debe confundirse con exterior geográfico al sistema.`
 ],[
  `20 tesis difundió un vocabulario de potentia/potestas y poder obediencial en debates latinoamericanos.`,
  `La obra se integra en un proyecto mayor de Política de la liberación que reconstruye historia mundial de categorías políticas.`,
  `Movimientos latinoamericanos utilizaron “mandar obedeciendo” en lenguajes propios, especialmente experiencias indígenas, aunque no derivan de Dussel.`,
  `Debates decoloniales incluyen a Dussel como figura clave pero su filosofía de la liberación posee una genealogía previa y diferenciada.`,
  `La teoría política contemporánea puede leerlo como interlocutor de republicanismo, democracia participativa y teoría crítica.`
 ],[
  `Comparar con Hobbes invierte la dirección de soberanía: representante soberano y comunidad como fuente de potentia.`,
  `Comparar con Rousseau muestra afinidad en soberanía popular y diferencias en principios materiales.`,
  `Comparar con Laclau distingue pueblo formalmente articulado y pueblo normativamente vinculado a víctimas.`,
  `Comparar con Quijano conecta liberación política y colonialidad.`,
  `Comparar con Pettit permite preguntar si poder obediencial puede institucionalizarse como control anti-dominación.`
 ],['Enrique Dussel, 20 tesis de política.','Enrique Dussel, Política de la liberación, volúmenes I–III.','Enrique Dussel, Ética de la liberación en la edad de la globalización y la exclusión.','Eduardo Mendieta, ed., The Underside of Modernity.','Linda Alcoff y Eduardo Mendieta, eds., Thinking from the Underside of History.','George Ciccariello-Maher, trabajos sobre poder popular y Dussel.'],['Definir potentia y potestas.','Explicar fetichización y poder obediencial.','Dominar los tres principios: material, democrático y factibilidad.','Distinguir comunidad y pueblo.','Comparar con Laclau.','Discutir riesgos de unidad comunitaria y paternalismo.','Situar 20 tesis dentro de Política de la liberación.']),
 odonnell:PD([
  `“Delegative Democracy” de Guillermo O’Donnell surge del esfuerzo por comprender regímenes latinoamericanos que atravesaron elecciones competitivas y reemplazaron dictaduras sin consolidar el conjunto de instituciones que las teorías de transición esperaban. O’Donnell rechaza clasificarlos simplemente como democracias “incompletas” camino a un modelo final. Propone una subespecie con lógica propia: la democracia delegativa, donde un presidente electo interpreta su victoria como autorización para gobernar en nombre de la nación con controles horizontales débiles.`,
  `La delegación se diferencia de la representación. En una democracia representativa institucionalizada, gobernantes aceptan que su mandato está limitado por Congreso, justicia, agencias de control, partidos y reglas. En la democracia delegativa, el presidente se presenta como encarnación directa del interés nacional y considera esos controles obstáculos particularistas. La elección legitima el origen, pero no produce por sí sola una práctica constitucional de rendición de cuentas.`,
  `La categoría se vincula con situaciones de crisis económica y social. Un Ejecutivo que promete soluciones extraordinarias puede concentrar decisiones, gobernar de manera plebiscitaria y oscilar entre apoyo masivo y rápida frustración. O’Donnell no define la democracia delegativa por una ideología económica o por populismo: puede acompañar programas distintos. El rasgo analítico es la relación entre mandato electoral y debilidad de controles institucionales.`,
  `El concepto de accountability horizontal, desarrollado en trabajos posteriores, amplía el diagnóstico. Una democracia necesita agencias estatales legalmente autorizadas y efectivamente dispuestas a controlar y sancionar acciones ilícitas de otras agencias. Elecciones ofrecen accountability vertical periódica; prensa, sociedad y organizaciones producen controles sociales; pero sin instituciones horizontales, el Estado puede operar como una colección de poderes poco controlados.`,
  `La teoría del Estado y la ciudadanía completa el proyecto. O’Donnell describe “zonas marrones” donde la legalidad estatal tiene presencia desigual y una “ciudadanía de baja intensidad” cuando derechos formalmente universales no son efectivamente garantizados. El régimen democrático puede coexistir con un Estado que distribuye legalidad de modo territorial y socialmente desigual. Esta intuición rompe con una teoría de democracia centrada sólo en elecciones.`,
  `La originalidad metodológica es importante: categorías producidas desde transiciones latinoamericanas no se presentan como particularidades incomparables. O’Donnell utiliza la región para revisar conceptos generales de democracia, Estado y rendición de cuentas. La periferia se convierte en lugar de producción de teoría comparativa.`,
  `La aplicación contemporánea del término “delegativa” suele ser demasiado laxa. Un presidente fuerte, popular o confrontativo no es automáticamente delegativo. El concepto exige elecciones democráticas combinadas con una concepción plebiscitaria del mandato y debilidad/hostilidad hacia accountability horizontal. Mantener esa precisión es indispensable.`
 ],[
  `O’Donnell parte de nuevas democracias que no siguen una transición lineal hacia consolidación institucional esperada.`,
  `La elección presidencial produce un mandato interpretado como delegación amplia de autoridad personal.`,
  `El presidente se presenta como síntesis de la nación por encima de intereses parciales.`,
  `Congreso, partidos y tribunales son tratados como impedimentos más que como componentes legítimos de representación.`,
  `Las crisis favorecen estilos decisorios rápidos y políticas tecnocráticas o plebiscitarias.`,
  `La accountability horizontal introduce agencias estatales de control recíproco.`,
  `La efectividad desigual de rule of law crea territorios y poblaciones con ciudadanía de diferente intensidad.`,
  `Democracia debe analizarse conjuntamente como régimen, Estado y ciudadanía, sin colapsar los tres niveles.`
 ],{democracia_delegativa:`Tipo democrático donde un Ejecutivo electo interpreta el mandato como autorización amplia para encarnar a la nación y resiste controles horizontales.`,representación:`Relación institucional donde gobernantes actúan bajo controles, mediaciones y responsabilidades que la delegación plebiscitaria tiende a minimizar.`,accountability_horizontal:`Control legal ejercido por agencias estatales sobre otras agencias mediante investigación, prevención y sanción.`,accountability_vertical:`Capacidad ciudadana de premiar o castigar gobernantes principalmente mediante elecciones.`,ciudadanía_de_baja_intensidad:`Situación en que derechos formalmente universales poseen efectividad desigual según territorio, clase o posición social.`,zonas_marrones:`Ámbitos donde presencia efectiva de legalidad estatal es débil, irregular o capturada por poderes particulares.`,Estado:`Sistema legal e institucional cuya capacidad territorial y garantía de derechos es una dimensión distinta del régimen electoral.`},[
  `La democracia delegativa no debe confundirse con autoritarismo competitivo: mantiene elecciones libres y una arena democrática significativa, aunque con institucionalización débil.`,
  `Tampoco es sinónimo de populismo. La teoría de Laclau analiza construcción de pueblo; O’Donnell analiza relaciones institucionales y controles de un régimen.`,
  `El concepto nació en el contexto de los años noventa y debe aplicarse a otros períodos mediante indicadores claros, no analogías de estilo presidencial.`,
  `La noción de “consolidación democrática” fue posteriormente abandonada o criticada por teleológica; O’Donnell contribuyó precisamente a desplazarla.`,
  `Las zonas marrones fueron criticadas por sugerir que legalidad plena existe de manera uniforme en democracias centrales. Una lectura comparativa debe reconocer gradaciones en todos los Estados.`,
  `La accountability horizontal requiere capacidad y autonomía institucional; su existencia formal en una Constitución no garantiza efectividad.`
 ],[
  `La democracia delegativa se convirtió en una de las categorías latinoamericanas más citadas en teoría democrática comparada.`,
  `Accountability horizontal generó una extensa literatura sobre agencias de control, corrupción y checks and balances.`,
  `La agenda sobre Estado de derecho y ciudadanía llevó a O’Donnell más allá del paradigma transitológico.`,
  `La calidad de la democracia y estudios de regímenes híbridos dialogaron con su preocupación por dimensiones no electorales.`,
  `La comparación contemporánea utiliza sus conceptos fuera de América Latina, evidencia de una producción teórica regional con alcance general.`
 ],[
  `Comparar con Federalista muestra una teoría clásica de controles frente a una categoría que diagnostica su debilidad práctica.`,
  `Comparar con Weber permite distinguir capacidad estatal, legalidad y legitimidad.`,
  `Comparar con Laclau evita confundir régimen delegativo y lógica populista.`,
  `Comparar con Cardoso-Faletto conecta Estado y régimen con estructuras socioeconómicas latinoamericanas.`,
  `Comparar con Pettit permite releer accountability horizontal como control frente a dominación pública.`,
  `Comparar con Tocqueville muestra cómo elección mayoritaria puede coexistir con amenazas no captadas por el acto electoral.`
 ],['Guillermo O’Donnell, “Delegative Democracy”.','Guillermo O’Donnell, “Horizontal Accountability in New Democracies”.','Guillermo O’Donnell, Counterpoints.','Guillermo O’Donnell, Democracy, Agency, and the State.','Scott Mainwaring y Christopher Welna, eds., Democratic Accountability in Latin America.','Gerardo Munck, trabajos sobre democracia y conceptos comparados.'],['Definir democracia delegativa con criterios estrictos.','Distinguir delegación y representación.','Explicar accountability horizontal y vertical.','Integrar Estado, régimen y ciudadanía.','Definir ciudadanía de baja intensidad y zonas marrones.','Evitar confundir con populismo o autoritarismo.','Explicar por qué O’Donnell produce teoría general desde América Latina.'])
});