(function(){
 const esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 const byId=id=>(window.WORLD_CONTEXTS||[]).find(c=>c.id===id);
 const getWork=id=>(window.WORKS||[]).find(w=>w.id===id);
 function ensureStyle(){if(document.querySelector('link[href="world-context.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='world-context.css';document.head.appendChild(l)}
 function ensureDOM(){
  const nav=document.querySelector('.nav');
  if(nav&&!nav.querySelector('[data-v="world"]')){const b=document.createElement('button');b.dataset.v='world';b.textContent='Mundo y contextos';const before=nav.querySelector('[data-v="concepts"]');nav.insertBefore(b,before||null);b.addEventListener('click',()=>{if(typeof show==='function')show('world');renderWorld();});}
  const main=document.querySelector('main.wrap');
  if(main&&!document.getElementById('world')){const s=document.createElement('section');s.id='world';s.className='view';s.innerHTML='<div class="section-head"><div><div class="eyebrow">CARTOGRAFÍA HISTÓRICA</div><h1>Mundo y contextos de la teoría política</h1><p>Un atlas para ver cómo cambian los problemas políticos cuando cambian las formas de Estado, sociedad, guerra, legitimidad y circulación intelectual.</p></div></div><div id="worldApp"></div>';const concepts=document.getElementById('concepts');main.insertBefore(s,concepts||null);}
 }
 function baseMap(ctx){
  const pts=(ctx.places||[]).map((p,i)=>`<g class="world-place" data-place="${i}" transform="translate(${p.x*10},${p.y*5})"><circle r="6"></circle><text x="10" y="4">${esc(p.name)}</text></g>`).join('');
  return `<svg class="world-svg" viewBox="0 0 1000 500" role="img" aria-label="Mapa mundial esquemático de focos de teoría política"><rect class="wm-ocean" width="1000" height="500"/><g class="wm-grid">${[100,200,300,400,500,600,700,800,900].map(x=>`<line x1="${x}" y1="0" x2="${x}" y2="500"/>`).join('')}${[100,200,300,400].map(y=>`<line x1="0" y1="${y}" x2="1000" y2="${y}"/>`).join('')}</g><g class="wm-continents"><path class="wm-land" d="M90 95 L155 60 L230 75 L275 120 L250 165 L215 175 L190 220 L145 210 L115 165 Z"/><path class="wm-land" d="M250 230 L290 245 L320 295 L312 350 L280 430 L245 385 L230 300 Z"/><path class="wm-land" d="M405 92 L460 70 L540 82 L590 112 L650 105 L715 88 L805 105 L860 145 L820 185 L760 178 L720 210 L665 198 L625 220 L570 200 L525 178 L470 190 L430 160 Z"/><path class="wm-land" d="M470 205 L535 205 L570 255 L555 315 L520 380 L475 350 L455 285 Z"/><path class="wm-land" d="M705 285 L760 275 L820 300 L835 350 L785 375 L730 350 Z"/><path class="wm-land" d="M870 120 L900 115 L915 135 L895 150 Z"/></g><g style="--wa:${ctx.accent}">${pts}</g></svg>`;
 }
 function contextChain(ctx){
  const response=(ctx.works||[]).slice(0,6).map(id=>getWork(id)).filter(Boolean).map(w=>w.author).filter((x,i,a)=>a.indexOf(x)===i).join(' · ');
  return `<div class="world-chain"><div class="world-chain-row"><b>Estructura histórica</b><span class="arrow">→</span><p>${esc(ctx.order)}</p></div><div class="world-chain-row"><b>Conflicto</b><span class="arrow">→</span><p>${esc(ctx.conflicts)}</p></div><div class="world-chain-row"><b>Pregunta teórica</b><span class="arrow">→</span><p><strong>${esc(ctx.question)}</strong></p></div><div class="world-chain-row"><b>Autores / respuestas</b><span class="arrow">→</span><p>${esc(response||'Ver obras vinculadas.')}</p></div></div>`;
 }
 function workCards(ctx){return (ctx.works||[]).map(id=>getWork(id)).filter(Boolean).map(w=>`<button class="world-work" data-world-work="${w.id}" style="--wa:${ctx.accent}"><small>${esc(w.date)} · ${esc(w.trad)}</small><strong>${esc(w.author)}</strong><span>${esc(w.title)}</span><em>Abrir dossier →</em></button>`).join('')}
 function render(ctxId){
  const app=document.getElementById('worldApp'),ctx=byId(ctxId)||WORLD_CONTEXTS[0];if(!app||!ctx)return;
  app.innerHTML=`<div class="world-shell" style="--wa:${ctx.accent}"><div class="world-toolbar panel"><div class="world-era-tabs">${WORLD_CONTEXTS.map(c=>`<button data-world-era="${c.id}" class="${c.id===ctx.id?'on':''}">${esc(c.label)}</button>`).join('')}</div><select id="worldSelect">${WORLD_CONTEXTS.map(c=>`<option value="${c.id}" ${c.id===ctx.id?'selected':''}>${esc(c.dates)} · ${esc(c.label)}</option>`).join('')}</select></div><div class="world-grid"><article class="world-map-card"><div class="world-map-head"><div class="eyebrow">MAPA HISTÓRICO</div><h2>${esc(ctx.label)}</h2><p>${esc(ctx.dates)} · Los puntos indican focos de producción, traducción o recepción relevantes para las obras del Atlas.</p></div><div class="world-map-wrap">${baseMap(ctx)}<div id="worldLegend" class="world-map-legend"><b>${esc(ctx.label)}</b>${esc(ctx.summary)}<div class="world-note">Mapa esquemático: representa focos intelectuales y políticos, no fronteras históricas precisas.</div></div></div></article><article class="world-context-card"><div class="world-context-head"><div class="eyebrow">CONTEXTO DE ÉPOCA</div><h2>Qué mundo hace posible estas preguntas</h2><p>${esc(ctx.summary)}</p></div><div class="world-context-body"><article><h3>Orden político</h3><p>${esc(ctx.order)}</p></article><article><h3>Estructura social</h3><p>${esc(ctx.society)}</p></article><article><h3>Legitimidad</h3><p>${esc(ctx.legitimacy)}</p></article><article><h3>Conflictos</h3><p>${esc(ctx.conflicts)}</p></article></div><div class="world-question"><small>PROBLEMA TEÓRICO DOMINANTE</small><strong>${esc(ctx.question)}</strong></div></article></div><div class="world-lower"><article class="world-timeline-card"><div class="eyebrow">CRONOLOGÍA SINCRONIZADA</div><h2 class="world-section-title">Acontecimientos y transformaciones</h2><div class="world-timeline">${ctx.events.map(e=>`<div class="world-event"><time>${esc(e[0])}</time><div class="dotcol"></div><p>${esc(e[1])}</p></div>`).join('')}</div></article><article class="world-theory-card"><div class="eyebrow">TEORÍA Y CONTEXTO</div><h2 class="world-section-title">Del mundo histórico al problema político</h2><div class="world-centers">${ctx.centers.map(x=>`<span>${esc(x)}</span>`).join('')}</div>${contextChain(ctx)}</article><article class="world-works-card"><div class="eyebrow">OBRAS VINCULADAS</div><h2 class="world-section-title">Qué leer para estudiar este contexto</h2><p class="world-note">La vinculación no afirma que el texto sea mero reflejo de su época: muestra el campo de problemas dentro del cual interviene y las traducciones posteriores que lo vuelven parte del canon.</p><div class="world-work-grid">${workCards(ctx)}</div></article></div></div>`;
  document.getElementById('worldSelect').onchange=e=>render(e.target.value);
  document.querySelectorAll('[data-world-era]').forEach(b=>b.onclick=()=>render(b.dataset.worldEra));
  document.querySelectorAll('[data-world-work]').forEach(b=>b.onclick=()=>{if(typeof openWork==='function')openWork(b.dataset.worldWork)});
  document.querySelectorAll('.world-place').forEach(g=>g.onclick=()=>selectPlace(ctx,Number(g.dataset.place),g));
 }
 function selectPlace(ctx,i,node){
  const p=ctx.places?.[i];if(!p)return;document.querySelectorAll('.world-place').forEach(x=>x.classList.remove('active'));node.classList.add('active');
  const ws=(p.works||[]).map(getWork).filter(Boolean);const legend=document.getElementById('worldLegend');if(!legend)return;
  legend.innerHTML=`<b>${esc(p.name)}</b>${esc(p.note)}${ws.length?`<div class="world-place-detail"><h4>${ws.length} obra${ws.length>1?'s':''} vinculada${ws.length>1?'s':''}</h4><p>${ws.slice(0,4).map(w=>esc(w.author+' · '+w.title)).join('<br>')}</p>${ws[0]?`<button data-place-open="${ws[0].id}">Abrir ${esc(ws[0].title)} →</button>`:''}</div>`:''}<div class="world-note">La ubicación representa un foco intelectual o político aproximado.</div>`;
  legend.querySelector('[data-place-open]')?.addEventListener('click',e=>{if(typeof openWork==='function')openWork(e.currentTarget.dataset.placeOpen)});
 }
 function renderWorld(){ensureStyle();ensureDOM();render(document.getElementById('worldSelect')?.value||WORLD_CONTEXTS[0]?.id)}
 window.renderWorld=renderWorld;
 function boot(){ensureStyle();ensureDOM();const b=document.querySelector('[data-v="world"]');if(b&&!b.dataset.worldBound){b.dataset.worldBound='1';b.addEventListener('click',()=>setTimeout(renderWorld,0));}renderWorld();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();