const C=window.POLIS_CURRICULUM;
const screen=document.querySelector('#screen'),modal=document.querySelector('#modal');
const streakEl=document.querySelector('#streak'),xpEl=document.querySelector('#xp'),heartsEl=document.querySelector('#hearts');
const state=JSON.parse(localStorage.getItem('polis-western-v1')||'{}');
state.xp??=0;state.hearts??=5;state.streak??=0;state.lastStudy??=null;state.done??={};state.passed??={};state.benchmarks??={};state.memory??={};state.events??=[];state.filters??={q:'',era:'all'};
const DAY=86400000,MIN=60000;
const W=id=>WORKS.find(w=>w.id===id), essential=C.essential.map(W).filter(Boolean), western=WORKS.filter(w=>C.eras.includes(w.era)), prelude=C.prelude.map(W).filter(Boolean);
const pd=w=>window.getPostdocGuide?getPostdocGuide(w):null;
const deep=w=>(typeof DEEP_GUIDES!=='undefined'&&DEEP_GUIDES[w.id])||null;
const ctx=w=>(window.WORLD_CONTEXTS||[]).find(c=>(c.works||[]).includes(w.id));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function save(){localStorage.setItem('polis-western-v1',JSON.stringify(state));stats()}
function stats(){streakEl.textContent=state.streak;xpEl.textContent=state.xp;heartsEl.textContent=state.hearts}
function touchStudy(){const today=new Date().toISOString().slice(0,10);if(state.lastStudy===today)return;if(state.lastStudy){const d=Math.round((new Date(today+'T12:00')-new Date(state.lastStudy+'T12:00'))/DAY);state.streak=d===1?state.streak+1:1}else state.streak=1;state.lastStudy=today}
function stepKey(id,s){return `${id}:${s}`}
function mark(id,s,xp=8){const k=stepKey(id,s);if(!state.done[k]){state.done[k]=true;state.xp+=xp;touchStudy();save()}}
const STEPS=['context','thesis','argument','concepts','debate','compare','checkpoint'];
function doneCount(id){return STEPS.filter(s=>s==='checkpoint'?state.passed[id]:state.done[stepKey(id,s)]).length}
function closeModal(){modal.classList.add('hidden');modal.innerHTML=''}
function shell(title,body){modal.classList.remove('hidden');modal.innerHTML=`<div class="shell"><div class="modal-top"><button class="close-btn" id="closeM">×</button><div><div class="eyebrow" style="color:var(--navy)">POLIS · curso interactivo</div><b>${esc(title)}</b></div></div>${body}</div>`;document.querySelector('#closeM').onclick=closeModal}
let AC=null;function tone(freq,dur,type='sine',gain=.035,delay=0){try{AC??=new(window.AudioContext||window.webkitAudioContext)();const o=AC.createOscillator(),g=AC.createGain(),t=AC.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(gain,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g);g.connect(AC.destination);o.start(t);o.stop(t+dur+.02)}catch(e){}}
function good(){tone(510,.11);tone(680,.16,'sine',.035,.08)}function bad(){tone(180,.15,'triangle',.045);tone(130,.19,'triangle',.04,.1)}
function mem(id){return state.memory[id]||(state.memory[id]={seen:0,correct:0,wrong:0,streak:0,stability:.55,last:null,due:Date.now(),introduced:false})}
function strength(id){const r=state.memory[id];if(!r||!r.introduced)return null;if(!r.last)return 35;const d=Math.max(0,(Date.now()-r.last)/DAY);return Math.round(Math.max(2,Math.min(100,100*Math.exp(-d/Math.max(.35,r.stability||.55)))))}
function record(id,ok,source='practice'){const r=mem(id),now=Date.now();r.seen++;r.last=now;r.introduced=true;if(ok){r.correct++;r.streak++;r.stability=Math.min(120,Math.max(.5,r.stability)*(1.25+Math.min(.3,r.streak*.05)));const ladder=[1,3,7,14,30,60,90];r.due=now+ladder[Math.min(r.streak-1,ladder.length-1)]*DAY}else{r.wrong++;r.streak=0;r.stability=Math.max(.25,r.stability*.52);r.due=now+10*MIN;state.hearts=Math.max(0,state.hearts-1)}state.events.push({t:now,id,ok,source});state.events=state.events.slice(-600);touchStudy();save()}
function introWork(w){const r=mem('work:'+w.id);r.introduced=true;(w.concepts||[]).forEach(c=>mem('concept:'+c).introduced=true);save()}
function eraWorks(era){return essential.filter(w=>w.era===era)}
function eraMeta(era){return C.eraMeta[era]||{name:era,icon:'•',color:'#555'}}
function pct(id){return Math.round(doneCount(id)/STEPS.length*100)}
function worldContext(w){const c=ctx(w);if(!c)return'';return `<section class="lesson-card"><h3>🌍 El mundo del texto</h3><p>${esc(c.summary)}</p><div class="thesis-box"><b>Pregunta de época:</b> ${esc(c.question)}</div><p><b>Orden político:</b> ${esc(c.order)}</p><p><b>Conflictos:</b> ${esc(c.conflicts)}</p></section>`}
function guideText(w){return pd(w)||deep(w)||{} }
function introPrelude(){shell('Preludio · antes de Grecia',`<section class="lesson-card"><h3>¿Por qué un preludio pregriego?</h3><p>La ruta principal estudia la tradición occidental desde la polis griega, pero el propio Atlas muestra que realeza, justicia, ley y buen gobierno fueron problematizados antes del tratado filosófico griego.</p></section>${prelude.map(w=>`<button class="work-card full" data-pre="${w.id}"><b>${esc(w.title)}</b><small>${esc(w.author)} · ${esc(w.date)}</small><em>${esc(w.problem)}</em></button>`).join('')}<button id="preClose" class="primary full" style="margin-top:10px">Volver a la ruta</button>`);document.querySelectorAll('[data-pre]').forEach(b=>b.onclick=()=>openDossier(W(b.dataset.pre)));document.querySelector('#preClose').onclick=closeModal}
function renderRoute(){const passed=essential.filter(w=>state.passed[w.id]).length;screen.innerHTML=`<div class="page"><section class="hero"><div class="eyebrow">Aprender teoría política por problemas</div><h1>POLIS · de la polis a la democracia contemporánea</h1><p>Contexto, conceptos, argumentos, debates y genealogías derivados del Atlas de Teoría Política. No memorizás autores: aprendés a reconstruir problemas y tradiciones.</p><div class="badges"><span class="badge">${essential.length} obras núcleo</span><span class="badge">${western.length} obras occidentales disponibles</span><span class="badge">${passed}/${essential.length} aprobadas</span></div></section><section class="card benchmark"><strong>Preludio opcional · antes de Grecia</strong><p class="note">Mesopotamia y Egipto: realeza, justicia y límites del poder antes del canon filosófico griego.</p><button id="openPrelude" class="secondary">Abrir preludio</button></section>${C.eras.map(era=>renderEra(era)).join('')}</div>`;document.querySelector('#openPrelude').onclick=introPrelude;document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>openStep(b.dataset.work,b.dataset.step));document.querySelectorAll('[data-bench]').forEach(b=>b.onclick=()=>runBenchmark(b.dataset.bench))}
function renderEra(era){const m=eraMeta(era),arr=eraWorks(era);if(!arr.length)return'';const milestone=C.milestones.find(x=>x.eras.includes(era)&&x.eras[x.eras.length-1]===era);return `<div class="era-head"><div class="era-icon" style="background:${m.color}">${m.icon}</div><div><h2>${esc(m.name)}</h2><p>${arr.filter(w=>state.passed[w.id]).length}/${arr.length} obras aprobadas</p></div></div>${arr.map((w,i)=>moduleCard(w,i+1)).join('')}${milestone?benchmarkCard(milestone):''}`}
function moduleCard(w,n){const d=doneCount(w.id),pass=!!state.passed[w.id];return `<section class="module"><div class="module-head"><div class="module-num">${n}</div><div><h3>${esc(w.title)}</h3><div class="author">${esc(w.author)} · ${esc(w.date)}</div></div><span class="state-pill ${pass?'done':''}">${pass?'✓ aprobada':`${d}/7`}</span></div><div class="problem">${esc(w.problem)}</div><div class="progress"><i style="width:${pct(w.id)}%"></i></div><div class="steps">${[['context','🌍','Contexto'],['thesis','❓','Problema'],['argument','🧱','Argumento'],['concepts','🧬','Conceptos'],['debate','⚡','Debates'],['compare','↔','Genealogía'],['checkpoint','✓','Control']].map(([s,ico,l])=>`<button class="${(s==='checkpoint'?pass:state.done[stepKey(w.id,s)])?'done':''}" data-work="${w.id}" data-step="${s}">${ico}<br>${l}</button>`).join('')}</div></section>`}
function benchmarkCard(m){const eligible=essential.filter(w=>m.eras.includes(w.era)),passed=eligible.filter(w=>state.passed[w.id]).length,unlock=passed>=Math.min(m.min,eligible.length),best=state.benchmarks[m.id];return `<section class="card benchmark"><strong>🎓 ${esc(m.label)}</strong><p class="note">${passed}/${eligible.length} obras del bloque aprobadas${best!=null?` · mejor resultado ${best}%`:''}</p><button data-bench="${m.id}" class="${unlock?'primary':'ghost'} full" ${unlock?'':'disabled'}>${unlock?'Hacer benchmark':'Completá más módulos para desbloquear'}</button></section>`}
function openStep(id,step){const w=W(id);if(!w)return;if(step==='checkpoint'){runCheckpoint(w);return}introWork(w);const g=guideText(w);let body='';if(step==='context')body=`<section class="lesson-hero"><div class="eyebrow">Contexto histórico</div><h1>${esc(w.title)}</h1><p>${esc(w.author)} · ${esc(w.date)} · ${esc(w.trad)}</p></section>${worldContext(w)}<section class="lesson-card"><h3>Contexto específico</h3><p>${esc(w.context)}</p></section>`;
if(step==='thesis')body=`<section class="lesson-hero"><div class="eyebrow">El problema antes que la respuesta</div><h1>${esc(w.title)}</h1></section><section class="lesson-card"><h3>❓ Problema político</h3><div class="thesis-box">${esc(w.problem)}</div><h3>💡 Tesis de lectura</h3><p>${esc(w.thesis)}</p></section>${(g.overview||g.summary)?`<section class="lesson-card"><h3>Mini-clase</h3>${(g.overview||g.summary||[]).slice(0,3).map(x=>`<p>${esc(x)}</p>`).join('')}</section>`:''}`;
if(step==='argument'){const arr=g.argument||g.architecture||[];body=`<section class="lesson-hero"><div class="eyebrow">Arquitectura argumental</div><h1>${esc(w.title)}</h1></section><section class="lesson-card"><h3>🧱 Cómo avanza el argumento</h3><ol>${arr.length?arr.map(x=>`<li>${esc(x)}</li>`).join(''):`<li>${esc(w.thesis)}</li>`}</ol></section>`}
if(step==='concepts'){const defs=g.concepts||g.keys||{};const keys=Object.keys(defs);body=`<section class="lesson-hero"><div class="eyebrow">Vocabulario conceptual</div><h1>${esc(w.title)}</h1></section><section class="lesson-card"><h3>Conceptos clave</h3>${keys.length?keys.map(k=>`<div class="concept-def"><b>${esc(k)}</b><p>${esc(defs[k])}</p></div>`).join(''):(w.concepts||[]).map(c=>`<div class="concept-def"><b>${esc(c)}</b><p>Concepto central de esta obra. Comparalo con sus usos en otras épocas desde la pestaña Conceptos.</p></div>`).join('')}</section>`}
if(step==='debate'){body=`<section class="lesson-hero"><div class="eyebrow">Controversias y recepción</div><h1>${esc(w.title)}</h1></section><section class="lesson-card"><h3>⚡ Debates interpretativos</h3><ul>${(g.debates||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Reconstruí qué presupuestos de la obra son discutibles desde otras tradiciones.</li>'}</ul></section><section class="lesson-card"><h3>↗ Recepción</h3><ul>${(g.reception||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Observá cómo cambia el sentido de la obra cuando es incorporada a genealogías posteriores.</li>'}</ul></section>`}
if(step==='compare'){const gens=(typeof CLASSIC_GENEALOGIES!=='undefined'?CLASSIC_GENEALOGIES:[]).filter(g=>(g.works||[]).includes(w.id));body=`<section class="lesson-hero"><div class="eyebrow">Comparar y genealogizar</div><h1>${esc(w.title)}</h1></section><section class="lesson-card"><h3>Comparaciones sugeridas por el Atlas</h3><ul>${(g.comparisons||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Usá la pestaña Comparar para enfrentar esta obra con otra del canon.</li>'}</ul></section>${gens.map(x=>`<section class="genealogy"><h3>${esc(x.name)}</h3><p class="note">${esc(x.desc)}</p><div class="genealogy-chain">${x.works.filter(id=>W(id)&&C.eras.includes(W(id).era)).map(id=>`<span>${esc(W(id).author)}</span>`).join('')}</div></section>`).join('')}`}
body+=`<button id="finishStep" class="primary full">Completar · +8 XP</button>`;shell(`${w.author} · ${w.title}`,body);document.querySelector('#finishStep').onclick=()=>{mark(w.id,step,8);closeModal();renderRoute()}}
function conceptDefs(w){const g=guideText(w);return g.concepts||g.keys||{}}
function quizForWork(w){const same=western.filter(x=>x.id!==w.id),defs=conceptDefs(w),ck=Object.keys(defs);const qs=[];let opts=shuffle([w.thesis,...shuffle(same.map(x=>x.thesis)).slice(0,3)]);qs.push({q:`¿Qué tesis corresponde a ${w.author}?`,opts,a:opts.indexOf(w.thesis),id:'work:'+w.id});opts=shuffle([w.problem,...shuffle(same.map(x=>x.problem)).slice(0,3)]);qs.push({q:`¿Cuál es el problema central de ${w.title}?`,opts,a:opts.indexOf(w.problem),id:'work:'+w.id});if(w.concepts?.length){const c=w.concepts[0],d=shuffle(western.flatMap(x=>x.concepts||[]).filter(x=>x!==c));opts=shuffle([c,...d.slice(0,3)]);qs.push({q:`¿Qué concepto pertenece al núcleo de ${w.title}?`,opts,a:opts.indexOf(c),id:'concept:'+c})}opts=shuffle([w.context,...shuffle(same.map(x=>x.context)).slice(0,3)]);qs.push({q:`Elegí el contexto histórico de ${w.title}.`,opts,a:opts.indexOf(w.context),id:'work:'+w.id});if(ck.length){const c=ck[0],def=defs[c],other=shuffle(western.flatMap(x=>Object.entries(conceptDefs(x))).filter(([k,v])=>k!==c&&v!==def));opts=shuffle([def,...other.slice(0,3).map(x=>x[1])]);qs.push({q:`En esta obra, ¿qué definición corresponde a «${c}»?`,opts,a:opts.indexOf(def),id:'concept:'+c})}while(qs.length<5){const c=shuffle(w.concepts||[])[0]||w.author;opts=shuffle([w.author,...shuffle(same.map(x=>x.author)).slice(0,3)]);qs.push({q:`¿Quién es autor/a de ${w.title}?`,opts,a:opts.indexOf(w.author),id:'work:'+w.id})}return qs.slice(0,5)}
function runCheckpoint(w){introWork(w);runQuestions(quizForWork(w),{title:`Control · ${w.author}`,source:'checkpoint',onFinish:score=>{const pass=score>=4;if(pass&&!state.passed[w.id]){state.passed[w.id]=true;state.xp+=25;record('work:'+w.id,true,'checkpoint-pass');touchStudy();save()}modal.innerHTML=`<div class="shell"><div style="font-size:60px;text-align:center">${pass?'🏆':'🧠'}</div><h2>${score}/5</h2><p>${pass?'Obra aprobada. +25 XP':'Necesitás 4/5. Los errores quedan priorizados para repaso.'}</p><button id="endCp" class="primary full">Volver a la ruta</button></div>`;document.querySelector('#endCp').onclick=()=>{closeModal();renderRoute()}}})}
function runQuestions(qs,{title='Práctica',source='practice',onFinish}){let qi=0,score=0,correcting=false;modal.classList.remove('hidden');function paint(){const q=qs[qi];modal.innerHTML=`<div class="shell"><div class="modal-top"><button class="close-btn" id="closeM">×</button><div class="progress" style="flex:1"><i style="width:${qi/qs.length*100}%"></i></div><b>${qi+1}/${qs.length}</b></div><section class="question-card"><div class="eyebrow" style="color:var(--navy)">${esc(title)}</div><h3>${esc(q.q)}</h3><div class="opts">${q.opts.map((o,i)=>`<button class="opt" data-o="${i}">${esc(o)}</button>`).join('')}</div><div id="fb"></div><button id="nextQ" class="primary full" disabled>Comprobar</button></section></div>`;document.querySelector('#closeM').onclick=closeModal;let sel=null;correcting=false;const next=document.querySelector('#nextQ'),fb=document.querySelector('#fb');document.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>{sel=+b.dataset.o;document.querySelectorAll('.opt').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');next.disabled=false});next.onclick=()=>{const ok=sel===q.a;if(ok){if(!correcting){score++;record(q.id||`q:${qi}`,true,source)}good();fb.className='feedback ok';fb.textContent=correcting?'✓ Ahora sí. Corregiste el error.':'✓ Correcto.';next.textContent=qi===qs.length-1?'Ver resultado':'Continuar';next.onclick=()=>{if(qi<qs.length-1){qi++;paint()}else onFinish(score)};return}if(!correcting)record(q.id||`q:${qi}`,false,source);bad();correcting=true;fb.className='correction';fb.innerHTML=`<b>Respuesta correcta:</b> ${esc(q.opts[q.a])}<p class="note">Elegila ahora. No podés avanzar hasta corregir.</p>`;next.disabled=true;document.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>{sel=+b.dataset.o;document.querySelectorAll('.opt').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');next.disabled=false})}}}paint()}
function runBenchmark(id){const m=C.milestones.find(x=>x.id===id);if(!m)return;const pool=essential.filter(w=>m.eras.includes(w.era)&&state.passed[w.id]);const chosen=shuffle(pool).slice(0,8),qs=chosen.map(w=>{const others=shuffle(pool.filter(x=>x.id!==w.id).map(x=>x.thesis)).slice(0,3),opts=shuffle([w.thesis,...others]);return{q:`¿Qué tesis corresponde a «${w.title}»?`,opts,a:opts.indexOf(w.thesis),id:'work:'+w.id}});runQuestions(qs,{title:m.label,source:'benchmark',onFinish:score=>{const pc=Math.round(score/qs.length*100);state.benchmarks[id]=Math.max(state.benchmarks[id]||0,pc);state.xp+=score*3;save();modal.innerHTML=`<div class="shell"><div style="font-size:60px;text-align:center">🎓</div><h2>${pc}%</h2><p>${pc>=70?'Benchmark aprobado.':'Conviene repasar las obras débiles del bloque.'}</p><button id="bend" class="primary full">Volver</button></div>`;document.querySelector('#bend').onclick=()=>{closeModal();renderRoute()}}})}
function renderWorks(){const q=(state.filters.q||'').toLowerCase(),era=state.filters.era;let rows=western.filter(w=>era==='all'||w.era===era).filter(w=>!q||[w.title,w.author,w.problem,w.thesis,w.trad,...(w.concepts||[])].join(' ').toLowerCase().includes(q));screen.innerHTML=`<div class="page"><section class="hero"><div class="eyebrow">Biblioteca ampliada</div><h1>Obras del Atlas convertidas en material de estudio</h1><p>${western.length} obras occidentales. La ruta esencial selecciona un hilo histórico; acá podés abrir cualquier dossier.</p></section><div class="library-tools"><input id="workQ" class="search" value="${esc(state.filters.q||'')}" placeholder="Autor, obra, problema o concepto"><select id="workEra" class="select"><option value="all">Todas las épocas</option>${C.eras.map(e=>`<option value="${e}" ${era===e?'selected':''}>${esc(eraMeta(e).name)}</option>`).join('')}</select></div><div class="works-grid">${rows.map(w=>`<button class="work-card" data-dossier="${w.id}"><b>${esc(w.title)}</b><small>${esc(w.author)} · ${esc(w.date)}</small><em>${esc(w.problem)}</em><div class="chips">${(w.concepts||[]).slice(0,4).map(c=>`<span class="chip">${esc(c)}</span>`).join('')}${C.essential.includes(w.id)?'<span class="chip">ruta núcleo</span>':''}</div></button>`).join('')}</div></div>`;document.querySelector('#workQ').oninput=e=>{state.filters.q=e.target.value;save();renderWorks();const x=document.querySelector('#workQ');x.focus();x.setSelectionRange(x.value.length,x.value.length)};document.querySelector('#workEra').onchange=e=>{state.filters.era=e.target.value;save();renderWorks()};document.querySelectorAll('[data-dossier]').forEach(b=>b.onclick=()=>openDossier(W(b.dataset.dossier)))}
function openDossier(w){if(!w)return;const g=guideText(w),defs=g.concepts||g.keys||{};shell(`${w.author} · ${w.title}`,`<section class="lesson-hero"><div class="eyebrow">Dossier del Atlas</div><h1>${esc(w.title)}</h1><p>${esc(w.author)} · ${esc(w.date)} · ${esc(w.trad)}</p></section><section class="lesson-card"><h3>Problema</h3><div class="thesis-box">${esc(w.problem)}</div><h3>Tesis</h3><p>${esc(w.thesis)}</p><h3>Contexto</h3><p>${esc(w.context)}</p></section>${Object.keys(defs).length?`<section class="lesson-card"><h3>Conceptos</h3>${Object.entries(defs).slice(0,8).map(([k,v])=>`<div class="concept-def"><b>${esc(k)}</b><p>${esc(v)}</p></div>`).join('')}</section>`:''}${(g.bibliography||g.secondary||[]).length?`<section class="lesson-card"><h3>Bibliografía secundaria</h3><ul>${(g.bibliography||g.secondary||[]).slice(0,8).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}<div style="display:grid;grid-template-columns:1fr 1fr;gap:7px"><button id="toModule" class="primary">Ir al módulo</button><button id="atlasLink" class="secondary">Abrir Atlas</button></div>`);document.querySelector('#toModule').onclick=()=>{closeModal();if(C.essential.includes(w.id))openStep(w.id,'context');else openStep(w.id,'thesis')};document.querySelector('#atlasLink').onclick=()=>window.open('../','_blank')}
function conceptMap(){const map=new Map();western.forEach(w=>(w.concepts||[]).forEach(c=>{if(!map.has(c))map.set(c,[]);map.get(c).push(w)}));return map}
function renderConcepts(){const map=conceptMap(),top=[...map.entries()].sort((a,b)=>b[1].length-a[1].length);screen.innerHTML=`<div class="page"><section class="hero"><div class="eyebrow">Historia conceptual</div><h1>Los mismos términos cambian de problema</h1><p>Seguí justicia, libertad, soberanía, democracia, propiedad, poder o igualdad a través de épocas distintas.</p></section><h2 class="section-title">Lentes de lectura</h2><div class="concept-grid">${C.lenses.map(l=>`<button class="concept-card" data-lens="${l.id}"><b>${esc(l.label)}</b><small>${l.terms.join(' · ')}</small></button>`).join('')}</div><h2 class="section-title">Conceptos del Atlas</h2><div class="concept-grid">${top.slice(0,60).map(([c,ws])=>`<button class="concept-card" data-concept="${esc(c)}"><b>${esc(c)}</b><small>${ws.length} obras</small></button>`).join('')}</div><h2 class="section-title">Genealogías del Atlas</h2>${(typeof CLASSIC_GENEALOGIES!=='undefined'?CLASSIC_GENEALOGIES:[]).filter(g=>g.id!=='emancipacion'&&g.id!=='antiguos').map(g=>`<section class="genealogy"><h3>${esc(g.name)}</h3><p class="note">${esc(g.desc)}</p><div class="genealogy-chain">${g.works.filter(id=>W(id)&&C.eras.includes(W(id).era)).map(id=>`<span>${esc(W(id).author)}</span>`).join('')}</div></section>`).join('')}</div>`;document.querySelectorAll('[data-concept]').forEach(b=>b.onclick=()=>openConcept(b.dataset.concept));document.querySelectorAll('[data-lens]').forEach(b=>b.onclick=()=>openLens(C.lenses.find(x=>x.id===b.dataset.lens)))}
function openConcept(c){const ws=western.filter(w=>(w.concepts||[]).includes(c));shell(`Concepto · ${c}`,`<section class="lesson-card"><h3>${esc(c)}</h3><p class="note">No presupongas que el término conserva el mismo significado. Compará problema, contexto y definición en cada obra.</p></section><div class="timeline">${ws.map(w=>`<div class="timeline-row"><time>${esc(w.date)}</time><div><b>${esc(w.author)} · ${esc(w.title)}</b><small>${esc(conceptDefs(w)[c]||w.thesis)}</small></div></div>`).join('')}</div>`)}
function openLens(l){const ws=western.filter(w=>l.terms.some(t=>(w.concepts||[]).some(c=>c.toLowerCase().includes(t.toLowerCase()))||w.problem.toLowerCase().includes(t.toLowerCase())||w.thesis.toLowerCase().includes(t.toLowerCase())));shell(l.label,`<section class="lesson-card"><h3>${esc(l.label)}</h3><p class="note">Una lente transversal generada desde problemas y conceptos del Atlas.</p></section><div class="timeline">${ws.map(w=>`<div class="timeline-row"><time>${esc(w.date)}</time><div><b>${esc(w.author)} · ${esc(w.title)}</b><small>${esc(w.problem)}</small></div></div>`).join('')}</div>`)}
function renderCompare(){const a=state.compareA||'republic',b=state.compareB||'leviathan';screen.innerHTML=`<div class="page"><section class="hero"><div class="eyebrow">Comparación disciplinada</div><h1>Comparar no es decir “ambos hablan de poder”</h1><p>Contrastá problemas, conceptos, contextos y tesis antes de afirmar semejanzas.</p></section><div class="compare-controls"><select id="cmpA" class="select">${western.map(w=>`<option value="${w.id}" ${a===w.id?'selected':''}>${esc(w.author)} · ${esc(w.title)}</option>`).join('')}</select><select id="cmpB" class="select">${western.map(w=>`<option value="${w.id}" ${b===w.id?'selected':''}>${esc(w.author)} · ${esc(w.title)}</option>`).join('')}</select></div><div id="cmpBody"></div></div>`;const draw=()=>{state.compareA=document.querySelector('#cmpA').value;state.compareB=document.querySelector('#cmpB').value;save();drawCompare(W(state.compareA),W(state.compareB))};document.querySelector('#cmpA').onchange=draw;document.querySelector('#cmpB').onchange=draw;drawCompare(W(a),W(b))}
function drawCompare(a,b){if(!a||!b)return;const shared=(a.concepts||[]).filter(c=>(b.concepts||[]).includes(c)),ga=guideText(a),gb=guideText(b);document.querySelector('#cmpBody').innerHTML=`<section class="compare-card"><div class="compare-table"><div class="label"></div><div><b>${esc(a.author)}</b><br>${esc(a.title)}</div><div><b>${esc(b.author)}</b><br>${esc(b.title)}</div><div class="label">Contexto</div><div>${esc(a.context)}</div><div>${esc(b.context)}</div><div class="label">Problema</div><div>${esc(a.problem)}</div><div>${esc(b.problem)}</div><div class="label">Tesis</div><div>${esc(a.thesis)}</div><div>${esc(b.thesis)}</div><div class="label">Conceptos</div><div>${(a.concepts||[]).map(esc).join(' · ')}</div><div>${(b.concepts||[]).map(esc).join(' · ')}</div></div>${shared.length?`<div class="shared"><b>Conceptos compartidos:</b> ${shared.map(esc).join(' · ')}. Compartir vocabulario no implica compartir definición.</div>`:''}<h3>Comparaciones internas del Atlas</h3><ul>${[...(ga.comparisons||[]),...(gb.comparisons||[])].slice(0,8).map(x=>`<li class="note">${esc(x)}</li>`).join('')}</ul></section>`}
function practiceBank(){const out=[];essential.filter(w=>mem('work:'+w.id).introduced||state.passed[w.id]).forEach(w=>{out.push({id:'work:'+w.id,type:'work',w});(w.concepts||[]).forEach(c=>out.push({id:'concept:'+c,type:'concept',c,w}))});return [...new Map(out.map(x=>[x.id,x])).values()]}
function priority(x,mode){const r=mem(x.id),s=strength(x.id)??30,err=r.seen?r.wrong/r.seen:0,due=r.due<=Date.now()?1:0;if(mode==='errors')return err*4+r.wrong*.2;if(mode==='weak')return (100-s)/25+err;if(mode==='due')return due*4+(100-s)/100;return due*3+(100-s)/40+err*1.5+Math.random()*.2}
function renderPractice(){const bank=practiceBank(),due=bank.filter(x=>mem(x.id).due<=Date.now()),weak=bank.filter(x=>(strength(x.id)??100)<55),errs=bank.filter(x=>mem(x.id).wrong>0),avg=bank.length?Math.round(bank.reduce((a,x)=>a+(strength(x.id)??35),0)/bank.length):0;screen.innerHTML=`<div class="page"><section class="hero"><div class="eyebrow">SRS conceptual</div><h1>🎯 Repaso inteligente</h1><p>Prioriza obras, problemas y conceptos que se están debilitando. Corregir un error no borra el error del modelo.</p><div class="badges"><span class="badge">${due.length} vencidos</span><span class="badge">${weak.length} débiles</span><span class="badge">memoria ${avg}%</span></div></section><section class="card"><button id="smart" class="primary full">Sesión inteligente · 10 ejercicios</button></section><div class="concept-grid"><button class="concept-card" data-pmode="due"><b>⏰ Vencidos</b><small>${due.length}</small></button><button class="concept-card" data-pmode="errors"><b>🩹 Errores</b><small>${errs.length}</small></button><button class="concept-card" data-pmode="weak"><b>🧱 Débiles</b><small>${weak.length}</small></button></div><section class="card"><h3>Ítems más débiles</h3>${[...bank].sort((a,b)=>(strength(a.id)??0)-(strength(b.id)??0)).slice(0,8).map(x=>`<div class="timeline-row"><time>${strength(x.id)??35}%</time><div><b>${esc(x.type==='work'?x.w.author:x.c)}</b><small>${esc(x.type==='work'?x.w.title:x.w.author+' · '+x.w.title)}</small></div></div>`).join('')||'<p class="note">Empezá la ruta para generar práctica adaptativa.</p>'}</section></div>`;document.querySelector('#smart').onclick=()=>runPractice('smart');document.querySelectorAll('[data-pmode]').forEach(b=>b.onclick=()=>runPractice(b.dataset.pmode))}
function runPractice(mode){let pool=practiceBank();if(mode==='due')pool=pool.filter(x=>mem(x.id).due<=Date.now());if(mode==='errors')pool=pool.filter(x=>mem(x.id).wrong>0);if(mode==='weak')pool=pool.filter(x=>(strength(x.id)??100)<55);pool.sort((a,b)=>priority(b,mode)-priority(a,mode));const sel=pool.slice(0,10);if(!sel.length){alert('Todavía no hay material suficiente en este modo. Completá módulos de la ruta.');return}const qs=sel.map(x=>x.type==='work'?(()=>{const ds=shuffle(essential.filter(w=>w.id!==x.w.id).map(w=>w.problem)).slice(0,3),opts=shuffle([x.w.problem,...ds]);return{q:`¿Qué problema pertenece a ${x.w.author}?`,opts,a:opts.indexOf(x.w.problem),id:x.id}})():(()=>{const owners=essential.filter(w=>(w.concepts||[]).includes(x.c)),correct=owners[0]||x.w,ds=shuffle(essential.filter(w=>!(w.concepts||[]).includes(x.c)).map(w=>w.author+' · '+w.title)).slice(0,3),ans=correct.author+' · '+correct.title,opts=shuffle([ans,...ds]);return{q:`¿En qué obra aparece «${x.c}» como concepto central?`,opts,a:opts.indexOf(ans),id:x.id}})());runQuestions(qs,{title:'Práctica adaptativa',source:'practice-'+mode,onFinish:score=>{modal.innerHTML=`<div class="shell"><div style="font-size:60px;text-align:center">🎯</div><h2>${score}/${qs.length}</h2><p>Los intervalos de memoria fueron actualizados.</p><button id="pend" class="primary full">Volver</button></div>`;document.querySelector('#pend').onclick=()=>{closeModal();renderPractice()}}})}
function renderProfile(){const passed=essential.filter(w=>state.passed[w.id]).length,bank=practiceBank(),avg=bank.length?Math.round(bank.reduce((a,x)=>a+(strength(x.id)??35),0)/bank.length):0;screen.innerHTML=`<div class="page"><section class="hero"><div class="eyebrow">Progreso intelectual</div><h1>👤 Perfil POLIS</h1><p>${state.xp} XP · ${state.streak} días de racha.</p></section><div class="skill-grid"><div class="skill"><b>${passed}/${essential.length}</b><small>obras núcleo aprobadas</small></div><div class="skill"><b>${western.length}</b><small>obras occidentales disponibles</small></div><div class="skill"><b>${Object.keys(state.benchmarks).length}/${C.milestones.length}</b><small>benchmarks realizados</small></div><div class="skill"><b>${avg}%</b><small>memoria media</small></div></div><section class="card"><h3>Por época</h3>${C.eras.map(e=>{const a=eraWorks(e),p=a.filter(w=>state.passed[w.id]).length;return`<div class="timeline-row"><time>${p}/${a.length}</time><div><b>${esc(eraMeta(e).name)}</b><div class="progress"><i style="width:${a.length?p/a.length*100:0}%"></i></div></div></div>`}).join('')}</section><section class="card"><h3>Arquitectura del curso</h3><p class="note">POLIS no copia el Atlas: lo usa como base de conocimiento. Las fichas del Atlas aportan problema, tesis, contexto y conceptos; las guías avanzadas aportan arquitectura, debates, recepción, comparaciones, bibliografía y objetivos de examen.</p><button id="openAtlas" class="secondary full">Abrir Atlas de Teoría Política</button></section></div>`;document.querySelector('#openAtlas').onclick=()=>window.open('../','_blank')}
function render(tab='route'){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));({route:renderRoute,works:renderWorks,concepts:renderConcepts,compare:renderCompare,practice:renderPractice,profile:renderProfile}[tab]||renderRoute)()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>render(b.dataset.tab));stats();render('route');