(()=>{
const DATA=window.POLIS_SYSTEMS;
if(!DATA)return;
const screen=document.querySelector('#screen');
const modal=document.querySelector('#modal');
const systemsBtn=document.querySelector('#systemsBtn');
if(!screen||!modal||!systemsBtn)return;
const STORE='polis-systems-v1';
const S=JSON.parse(localStorage.getItem(STORE)||'{}');
S.progress??={};S.xp??=0;S.duel??={best:0,done:false};S.current??=null;
const SKILLS={concepts:'Conceptos',argument:'Argumento',relations:'Relaciones',application:'Aplicación'};
const TYPE_ICON={choice:'❓',case:'🎭',order:'🔗',match:'🧩'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
let AC=null;
function tone(freq,dur,type='sine',gain=.04,delay=0){try{AC??=new(window.AudioContext||window.webkitAudioContext)();const o=AC.createOscillator(),g=AC.createGain(),t=AC.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(gain,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g);g.connect(AC.destination);o.start(t);o.stop(t+dur+.02)}catch(e){}}
function soundOK(){tone(520,.1);tone(700,.16,'sine',.035,.08)}
function soundBad(){tone(180,.14,'triangle',.045);tone(130,.18,'triangle',.04,.1)}
function globalState(){const g=JSON.parse(localStorage.getItem('polis-western-v1')||'{}');g.xp??=0;g.hearts??=5;g.streak??=0;return g}
function addGlobalXP(n){const g=globalState();g.xp+=n;localStorage.setItem('polis-western-v1',JSON.stringify(g));const el=document.querySelector('#xp');if(el)el.textContent=g.xp}
function loseHeart(){const g=globalState();g.hearts=Math.max(0,g.hearts-1);localStorage.setItem('polis-western-v1',JSON.stringify(g));const el=document.querySelector('#hearts');if(el)el.textContent=g.hearts}
function save(){localStorage.setItem(STORE,JSON.stringify(S))}
function sysProgress(id){return S.progress[id]||(S.progress[id]={})}
function activityRecord(sys,id){const p=sysProgress(sys);return p[id]||(p[id]={done:false,wrong:0,attempts:0})}
function completed(sys){const s=DATA.systems.find(x=>x.id===sys);return s?s.activities.filter(a=>activityRecord(sys,a.id).done).length:0}
function systemPct(sys){const s=DATA.systems.find(x=>x.id===sys);return s?Math.round(completed(sys)/s.activities.length*100):0}
function skillScore(sys,skill){const s=DATA.systems.find(x=>x.id===sys);if(!s)return 0;const aa=s.activities.filter(a=>a.skill===skill);if(!aa.length)return 0;return Math.round(aa.reduce((sum,a)=>{const r=activityRecord(sys,a.id);return sum+(r.done?Math.max(55,100-r.wrong*12):0)},0)/aa.length)}
function systemMastery(sys){return Math.round(Object.keys(SKILLS).reduce((n,k)=>n+skillScore(sys,k),0)/4)}
function setActive(){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));systemsBtn.classList.add('active')}
function restoreBaseNav(){systemsBtn.classList.remove('active')}
document.querySelectorAll('.nav-btn[data-tab]').forEach(b=>b.addEventListener('click',restoreBaseNav));
systemsBtn.addEventListener('click',()=>{setActive();renderHome()});
function progressBars(id){return `<div class="sys-skills">${Object.entries(SKILLS).map(([k,l])=>`<div><span>${l}</span><b>${skillScore(id,k)}%</b><i><em style="width:${skillScore(id,k)}%"></em></i></div>`).join('')}</div>`}
function renderHome(){
 setActive();
 screen.innerHTML=`<div class="page systems-page"><section class="systems-hero"><div class="eyebrow">POLIS V2 · prototipo</div><h1>🧠 Construí sistemas, no fichas</h1><p>Aprendé teoría política resolviendo relaciones, argumentos y casos. El texto largo queda detrás del botón “Profundizar”.</p><div class="systems-stats"><span>⚡ ${S.xp} XP de sistemas</span><span>🎯 ${DATA.systems.reduce((n,x)=>n+completed(x.id),0)}/${DATA.systems.reduce((n,x)=>n+x.activities.length,0)} microactividades</span></div></section><section class="tiny-rule"><b>Regla del prototipo</b><span>una pantalla = una decisión conceptual</span></section><div class="systems-worlds">${DATA.systems.map((s,i)=>worldCard(s,i)).join('')}</div><section class="duel-card"><div><span class="world-icon">⚔️</span><div><b>Duelo de sistemas</b><small>Platón vs Hobbes vs Marx · 9 desafíos</small></div></div><button id="startDuel" class="sys-primary">${S.duel.done?`Repetir · mejor ${S.duel.best}/9`:'Jugar duelo'}</button></section></div>`;
 document.querySelectorAll('[data-system]').forEach(b=>b.onclick=()=>openSystem(b.dataset.system));
 document.querySelector('#startDuel').onclick=startDuel;
}
function worldCard(s,i){const done=completed(s.id),master=systemMastery(s.id);return `<section class="world-card world-${i}"><div class="world-head"><span class="world-icon">${s.icon}</span><div><div class="eyebrow">Sistema ${i+1}</div><h2>${esc(s.author)}</h2><p>${esc(s.tagline)}</p></div><div class="master-ring"><b>${master}%</b><small>dominio</small></div></div><div class="world-progress"><i style="width:${systemPct(s.id)}%"></i></div><div class="world-meta"><span>${done}/${s.activities.length} actividades</span><span>${esc(s.work)}</span></div>${progressBars(s.id)}<button class="sys-primary full" data-system="${s.id}">${done? 'Continuar sistema':'Empezar sistema'}</button></section>`}
function openSystem(id){const s=DATA.systems.find(x=>x.id===id);if(!s)return;S.current=id;save();setActive();const done=completed(id),unlock=Math.min(s.activities.length,done+1),mapUnlock=Math.min(s.nodes.length,Math.max(1,Math.floor(done/3)+1));screen.innerHTML=`<div class="page systems-page"><button id="backSystems" class="sys-back">← Sistemas</button><section class="system-banner"><div class="world-icon big">${s.icon}</div><div><div class="eyebrow">${esc(s.work)}</div><h1>${esc(s.author)}</h1><p>${esc(s.tagline)}</p></div><div class="master-ring"><b>${systemMastery(id)}%</b><small>dominio</small></div></section><section class="system-map"><div class="map-title"><b>Mapa conceptual</b><span>${mapUnlock}/${s.nodes.length} nodos revelados</span></div><div class="map-chain">${s.nodes.map((n,i)=>`<div class="map-node ${i<mapUnlock?'revealed':'locked'}"><span>${i<mapUnlock?i+1:'🔒'}</span><b>${i<mapUnlock?esc(n):'por descubrir'}</b>${i<s.nodes.length-1?'<i>↓</i>':''}</div>`).join('')}</div></section>${progressBars(id)}<h2 class="section-title">Camino de práctica</h2><div class="lesson-path">${s.activities.map((a,i)=>activityNode(s,a,i,unlock)).join('')}</div><button id="deepAtlas" class="sys-secondary full">📖 Profundizar en el Atlas</button></div>`;
 document.querySelector('#backSystems').onclick=renderHome;
 document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>startActivity(id,+b.dataset.act));
 document.querySelector('#deepAtlas').onclick=()=>window.open('../','_blank');
}
function activityNode(s,a,i,unlock){const r=activityRecord(s.id,a.id),isUnlocked=i<unlock,side=i%3===0?'left':i%3===1?'center':'right',boss=(i+1)%5===0;return `<div class="path-row ${side}"><button class="path-node ${r.done?'done':''} ${!isUnlocked?'locked':''} ${boss?'boss':''}" data-act="${i}" ${isUnlocked?'':'disabled'}><span>${r.done?'✓':isUnlocked?(boss?'👑':TYPE_ICON[a.type]||'●'):'🔒'}</span></button><div class="path-label"><b>${esc(a.title)}</b><small>${SKILLS[a.skill]} · ${i+1}/${s.activities.length}</small></div></div>`}
function openModal(content){modal.classList.remove('hidden');modal.innerHTML=`<div class="sys-shell">${content}</div>`}
function closeModal(){modal.classList.add('hidden');modal.innerHTML=''}
function header(s,a,index){return `<div class="sys-qtop"><button id="closeSysQ">×</button><div class="sys-qprogress"><i style="width:${index/s.activities.length*100}%"></i></div><b>${index+1}/${s.activities.length}</b></div><div class="q-kicker">${s.icon} ${esc(s.author)} · ${SKILLS[a.skill]}</div>`}
function startActivity(sysId,index){const s=DATA.systems.find(x=>x.id===sysId),a=s?.activities[index];if(!a)return;const r=activityRecord(sysId,a.id);r.attempts++;save();if(a.type==='order')return renderOrder(s,a,index);if(a.type==='match')return renderMatch(s,a,index);return renderChoice(s,a,index)}
function successActivity(s,a,index,corrected=false){const r=activityRecord(s.id,a.id);if(!r.done){r.done=true;S.xp+=corrected?6:10;addGlobalXP(corrected?6:10)}save();soundOK();const next=index<s.activities.length-1?`<button id="nextAct" class="sys-primary full">Continuar</button>`:`<button id="nextAct" class="sys-primary full">Ver sistema completado</button>`;openModal(`<div class="success-pop"><span>✓</span><h2>${corrected?'Error corregido':'¡Conexión dominada!'}</h2><p>${esc(a.explain||'La relación quedó incorporada al mapa conceptual.')}</p><div class="xp-pop">+${corrected?6:10} XP</div>${next}</div>`);document.querySelector('#nextAct').onclick=()=>{closeModal();openSystem(s.id)}}
function renderChoice(s,a,index){let selected=null,correcting=false;openModal(`${header(s,a,index)}<section class="micro-card">${a.scenario?`<div class="scenario"><span>🎭 Caso</span><p>${esc(a.scenario)}</p></div>`:''}<h2>${esc(a.title)}</h2><p class="micro-prompt">${esc(a.prompt)}</p><div class="micro-options">${a.options.map((o,i)=>`<button data-opt="${i}">${esc(o)}</button>`).join('')}</div><div id="microFb"></div><button id="checkMicro" class="sys-primary full" disabled>Comprobar</button></section>`);document.querySelector('#closeSysQ').onclick=closeModal;const check=document.querySelector('#checkMicro'),fb=document.querySelector('#microFb');function wire(){document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{selected=+b.dataset.opt;document.querySelectorAll('[data-opt]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');check.disabled=false})}wire();check.onclick=()=>{if(selected===a.answer)return successActivity(s,a,index,correcting);if(!correcting){activityRecord(s.id,a.id).wrong++;loseHeart();save()}soundBad();correcting=true;fb.innerHTML=`<div class="micro-correction"><b>Respuesta correcta</b><p>${esc(a.options[a.answer])}</p><small>${esc(a.explain||'Revisá la relación conceptual.')}</small></div><div class="retry-note">Ahora elegí la respuesta correcta para continuar.</div>`;check.disabled=true;wire()}}
function renderOrder(s,a,index){let chosen=[],correcting=false;const bank=shuffle(a.items.map((t,i)=>({t,id:'i'+i})));openModal(`${header(s,a,index)}<section class="micro-card"><h2>${esc(a.title)}</h2><p class="micro-prompt">${esc(a.prompt)}</p><div id="orderAnswer" class="order-answer"><span>Construí la cadena…</span></div><div id="orderBank" class="order-bank">${bank.map(x=>`<button data-chip="${x.id}" data-text="${esc(x.t)}">${esc(x.t)}</button>`).join('')}</div><div id="microFb"></div><button id="checkOrder" class="sys-primary full" disabled>Comprobar cadena</button></section>`);document.querySelector('#closeSysQ').onclick=closeModal;const ans=document.querySelector('#orderAnswer'),check=document.querySelector('#checkOrder'),fb=document.querySelector('#microFb');function paint(){ans.innerHTML=chosen.length?chosen.map(x=>`<button class="chosen-chip" data-back="${x.id}">${esc(x.t)}</button>`).join('<i>→</i>'):'<span>Construí la cadena…</span>';check.disabled=!chosen.length;ans.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{const idx=chosen.findIndex(x=>x.id===b.dataset.back);const [x]=chosen.splice(idx,1);document.querySelector(`[data-chip="${x.id}"]`).disabled=false;paint()})}document.querySelectorAll('[data-chip]').forEach(b=>b.onclick=()=>{chosen.push({id:b.dataset.chip,t:b.dataset.text});b.disabled=true;paint()});check.onclick=()=>{const ok=chosen.map(x=>x.t).join('|')===a.items.join('|');if(ok)return successActivity(s,a,index,correcting);if(!correcting){activityRecord(s.id,a.id).wrong++;loseHeart();save()}soundBad();correcting=true;fb.innerHTML=`<div class="micro-correction"><b>Orden correcto</b><p>${a.items.map(esc).join(' → ')}</p></div><div class="retry-note">Reconstruilo correctamente antes de continuar.</div>`;chosen=[];document.querySelectorAll('[data-chip]').forEach(x=>x.disabled=false);paint()}}
function renderMatch(s,a,index){let left=null,right=null,matched=new Set(),correcting=false;const lefts=shuffle(a.pairs.map((p,i)=>({t:p[0],i}))),rights=shuffle(a.pairs.map((p,i)=>({t:p[1],i})));openModal(`${header(s,a,index)}<section class="micro-card"><h2>${esc(a.title)}</h2><p class="micro-prompt">${esc(a.prompt)}</p><div class="match-board"><div>${lefts.map(x=>`<button data-left="${x.i}">${esc(x.t)}</button>`).join('')}</div><div>${rights.map(x=>`<button data-right="${x.i}">${esc(x.t)}</button>`).join('')}</div></div><div id="microFb"></div></section>`);document.querySelector('#closeSysQ').onclick=closeModal;const fb=document.querySelector('#microFb');function test(){if(left===null||right===null)return;if(left===right){matched.add(left);soundOK();document.querySelector(`[data-left="${left}"]`).classList.add('matched');document.querySelector(`[data-right="${right}"]`).classList.add('matched');document.querySelector(`[data-left="${left}"]`).disabled=true;document.querySelector(`[data-right="${right}"]`).disabled=true;left=right=null;if(matched.size===a.pairs.length)setTimeout(()=>successActivity(s,a,index,correcting),250)}else{if(!correcting){activityRecord(s.id,a.id).wrong++;loseHeart();save()}correcting=true;soundBad();const pair=a.pairs[left];fb.innerHTML=`<div class="micro-correction"><b>Conexión correcta</b><p>${esc(pair[0])} → ${esc(pair[1])}</p></div>`;document.querySelectorAll('.match-board button').forEach(x=>x.classList.remove('selected'));left=right=null}}document.querySelectorAll('[data-left]').forEach(b=>b.onclick=()=>{left=+b.dataset.left;document.querySelectorAll('[data-left]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');test()});document.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{right=+b.dataset.right;document.querySelectorAll('[data-right]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');test()})}
function startDuel(){let i=0,score=0,correcting=false;const qs=DATA.duels;function paint(){const q=qs[i];openModal(`<div class="sys-qtop"><button id="closeSysQ">×</button><div class="sys-qprogress"><i style="width:${i/qs.length*100}%"></i></div><b>${i+1}/${qs.length}</b></div><div class="q-kicker">⚔️ Duelo de sistemas</div><section class="micro-card"><h2>${esc(q.prompt)}</h2><div class="micro-options">${q.options.map((o,n)=>`<button data-opt="${n}">${esc(o)}</button>`).join('')}</div><div id="microFb"></div><button id="checkMicro" class="sys-primary full" disabled>Comprobar</button></section>`);document.querySelector('#closeSysQ').onclick=closeModal;let sel=null;correcting=false;const check=document.querySelector('#checkMicro'),fb=document.querySelector('#microFb');document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{sel=+b.dataset.opt;document.querySelectorAll('[data-opt]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');check.disabled=false});check.onclick=()=>{if(sel===q.answer){if(!correcting)score++;soundOK();fb.innerHTML='<div class="micro-good">✓ Correcto</div>';check.textContent=i===qs.length-1?'Ver resultado':'Continuar';check.onclick=()=>{if(i<qs.length-1){i++;paint()}else finish()};return}soundBad();correcting=true;fb.innerHTML=`<div class="micro-correction"><b>Respuesta correcta</b><p>${esc(q.options[q.answer])}</p><small>${esc(q.explain)}</small></div>`;check.disabled=true}}function finish(){S.duel.done=true;S.duel.best=Math.max(S.duel.best,score);S.xp+=score*2;addGlobalXP(score*2);save();openModal(`<div class="success-pop"><span>⚔️</span><h2>${score}/${qs.length}</h2><p>${score>=7?'Ya distinguís las arquitecturas básicas de los tres sistemas.':'El duelo detectó mezclas conceptuales. Conviene volver a los sistemas más débiles.'}</p><div class="xp-pop">+${score*2} XP</div><button id="duelEnd" class="sys-primary full">Volver a Sistemas</button></div>`);document.querySelector('#duelEnd').onclick=()=>{closeModal();renderHome()}}paint()}
window.POLIS_SYSTEMS_UI={renderHome,openSystem};
})();