/* Raíces · Fase 2B refinada: conocimiento por conceptos */
(function(){
 if(!window.RaicesAdaptive||!window.QA1)return;
 const DAY=86400000, CM=state.conceptModel??={version:2,events:[]}; CM.version=2; CM.events??=[];
 const C={
  greetings:["Saludos y cortesía","Funciones",[0]], vowels3:["Sistema a–i–u","Pronunciación",[0]], q_uvular:["q posterior / uvular","Pronunciación",[0,1,3,4,6]], asp_ejective:["Aspiradas y eyectivas","Pronunciación",[0,3,5,6,7],["q_uvular"]],
  pronouns:["ñuqa · qam · pay","Morfología",[0,1]], kay_person:["kani · kanki · kan","Morfología",[1],["pronouns"]], topic_qa:["Tópico -qa","Discurso",[1,2,3,6]], evidential_mi:["-mi/-m afirmativo/evidencial","Discurso",[0,1,2,3,4,5,6]],
  case_manta:["-manta · desde/de","Casos",[1,6]], case_pi:["-pi · en","Casos",[1,3,6,7]], yuq:["-yuq · que tiene","Morfología",[1,4]], possessive:["Posesión -y/-yki/-n","Morfología",[2,6],["pronouns"]], genitive_pa:["Genitivo -pa","Casos",[2],["possessive"]], plural_kuna:["Plural -kuna","Morfología",[2,4]], kinship:["Parentesco perspectival","Léxico y cultura",[2]],
  demonstratives:["kay · chay · haqay","Sintaxis",[2,3]], adjective_order:["Adjetivo + nombre","Sintaxis",[3]], existence_kan:["Existencia con kan","Sintaxis",[3],["case_pi"]], numerals:["Numerales 1–20","Léxico y estructura",[4]], quantity:["hayk'a · cantidad","Funciones",[4],["numerals"]], object_ta:["Objeto directo -ta","Casos",[4,5,7]],
  present_person:["Presente -ni/-nki/-n","Morfología verbal",[5,7],["pronouns"]], infinitive_munay:["Acción + -ta + munay","Morfología verbal",[5],["object_ta","present_person"]], negation_chu:["mana(m)…-chu","Sintaxis",[5],["present_person"]], imperative:["Imperativo en -y","Morfología verbal",[5,6]], case_man:["-man · hacia/a","Casos",[6,7]], case_wan:["-wan · con","Casos",[6,7],["possessive"]], locative_question:["maypi / maymanta","Funciones",[1,6],["case_pi","case_manta"]], directions:["Dar direcciones","Funciones",[6],["case_man","imperative"]], sequence:["ñawpaqta · chaymanta · hinaspa","Discurso",[7],["present_person"]], additive_pas:["-pas · también","Discurso",[7]], suffix_stacking:["Apilamiento de sufijos","Morfología",[6,7],["possessive","case_wan","object_ta"]], routine:["Rutina cotidiana","Funciones",[7],["present_person","sequence"]]
 };
 const QT=[
  [["greetings"],["vowels3"],["pronouns"],["asp_ejective"],["greetings"],["greetings"]],
  [["case_manta","locative_question"],["kay_person"],["case_pi","locative_question"],["case_manta"],["case_pi"],["pronouns"]],
  [["possessive"],["possessive"],["genitive_pa"],["plural_kuna","numerals"],["kinship"],["kinship"]],
  [["adjective_order"],["demonstratives"],["adjective_order"],["existence_kan","case_pi"],["asp_ejective"],["demonstratives"]],
  [["numerals"],["numerals"],["numerals","yuq"],["numerals","plural_kuna"],["quantity"],["object_ta"]],
  [["present_person"],["present_person"],["infinitive_munay"],["negation_chu"],["imperative"],["object_ta"]],
  [["case_man"],["case_manta"],["case_wan"],["locative_question","case_pi"],["directions","case_man","imperative"],["suffix_stacking","possessive","case_wan"]],
  [["sequence"],["routine"],["case_man","present_person"],["additive_pas"],["sequence"],["suffix_stacking","possessive","case_wan"]]
 ];
 const CT=[["greetings"],["case_manta","case_pi","locative_question"],["kinship","possessive"],["demonstratives","adjective_order","existence_kan"],["numerals","quantity","object_ta"],["present_person","object_ta","negation_chu"],["locative_question","directions","case_man"],["routine","sequence","present_person"]];
 const kin=new Set(["ayllu","mama","tayta","wawa","wawqi","pana","turi","ñaña","masi"]), demos=new Set(["kay","chay","haqay"]), nums=new Set(["huk","iskay","kimsa","tawa","pichqa","suqta","qanchis","pusaq","isqun","chunka","chunka hukniyuq","chunka iskayniyuq","chunka kimsayuq","chunka tawayuq","chunka pichqayuq","chunka suqtayuq","chunka qanchisniyuq","chunka pusaqniyuq","chunka isqunniyuq","iskay chunka"]), seq=new Set(["ñawpaqta","chaymanta","hinaspa"]);
 const bank=()=>RaicesAdaptive.bank(), uniq=a=>[...new Set(a)], low=s=>String(s||"").toLowerCase();
 function tags(i){let t=[];if(i.kind==="quiz")t=QT[i.ui]?.[i.qi]||[];if(i.kind==="comp")t=CT[i.ui]||[];if(i.kind==="vocab"){let w=low(i.front);if(i.ui===0&&["rimaykullayki","imaynallan","kashanki","allillanmi","añay","allin p'unchaw","allin tuta","paqarinkama","tupananchikkama"].includes(w))t.push("greetings");if(/q'|k'|p'|t'|ch'|qh|kh|ph|th|chh/.test(w))t.push("asp_ejective");if(w.includes("q"))t.push("q_uvular");if(["ñuqa","qam","pay"].includes(w))t.push("pronouns");if(kin.has(w))t.push("kinship");if(demos.has(w))t.push("demonstratives");if(nums.has(w))t.push("numerals");if(["hayk'a","achka","pisi","chanin"].includes(w))t.push("quantity");if(seq.has(w))t.push("sequence");if(w.includes("-pi"))t.push("case_pi");if(w.includes("-man"))t.push("case_man");if(w.includes("-manta"))t.push("case_manta");if(w.includes("-wan"))t.push("case_wan");if(w.includes("-kuna"))t.push("plural_kuna");if(w.includes("-pas"))t.push("additive_pas")}return uniq(t)}
 function eligible(i){let r=state.adaptive?.cards?.[i.id];if(i.kind==="vocab"){let u=QA.units[i.ui],m=Math.ceil(u.vocab.length/2);return !!state.qdone[qkey(i.ui,i.wi<m?"vocab1":"vocab2")]||!!state.unitPass[i.ui]||(r?.seen||0)>0}if(i.kind==="quiz")return !!state.qdone[qkey(i.ui,"check")]||!!state.unitPass[i.ui]||(r?.seen||0)>0;if(i.kind==="comp")return !!state.qdone[qkey(i.ui,"listen")]||!!state.unitPass[i.ui]||(r?.seen||0)>0;return false}
 function items(cid){return bank().filter(i=>eligible(i)&&tags(i).includes(cid))}
 function introduced(cid){if(items(cid).length)return true;return C[cid][2].some(ui=>state.qdone[qkey(ui,"grammar")]||state.unitPass[ui])}
 function mappedEvents(){let map=new Map(bank().map(i=>[i.id,i]));return (state.adaptive?.events||[]).flatMap(e=>{let i=map.get(e.id);return i?tags(i).map(cid=>({t:e.t,ok:e.ok,cid,source:e.source,itemId:e.id})):[]})}
 function events(cid){return [...mappedEvents(),...CM.events].filter(e=>e.cid===cid).sort((a,b)=>a.t-b.t)}
 function est(cid){let es=events(cid),intro=introduced(cid);if(!es.length)return {cid,m:intro?35:null,conf:0,n:0,wrong:0,status:intro?"sin diagnóstico":"no introducido"};let p=.25,g=.25,s=.10,l=.08;for(let e of es){if(e.ok){let d=p*(1-s)+(1-p)*g;p=d?p*(1-s)/d:p}else{let d=p*s+(1-p)*(1-g);p=d?p*s/d:p}p+= (1-p)*l}let days=Math.max(0,(Date.now()-es.at(-1).t)/DAY);p=.20+(p-.20)*Math.exp(-days/45);let n=es.length,m=Math.min(Math.round(p*100),Math.min(96,42+n*7)),conf=Math.round(100*(1-Math.exp(-n/6))),wrong=es.filter(e=>!e.ok).length;return {cid,m,conf,n,wrong,status:m>=80?"fuerte":m>=60?"en desarrollo":m>=45?"frágil":"débil"}}
 function blockers(cid){return (C[cid][3]||[]).filter(p=>{let x=est(p);return x.m!=null&&x.m<55})}
 function priority(x){return x.m==null?-999:(100-x.m)*.65+(100-x.conf)*.18+x.wrong*3+blockers(x.cid).length*4}
 function recommendation(){return Object.keys(C).map(est).filter(x=>introduced(x.cid)).sort((a,b)=>priority(b)-priority(a))[0]||null}
 function recordGenerated(cid,ok,source){CM.events.push({t:Date.now(),cid,ok,source});CM.events=CM.events.slice(-700);touchStudy();save()}
 const D={
  vowels3:["¿Qué vocales usa la escritura estándar enseñada?",["a, i, u","a, e, i, o, u","a, e, u","i, o, u"],0],q_uvular:["¿Qué afirmación describe q?",["Se articula más atrás que k","Es una vocal","Indica plural","Siempre suena como k castellana"],0],asp_ejective:["¿Qué signo representa una eyectiva?",["apóstrofo ' ","tilde ´","diéresis ¨","guion -"],0],topic_qa:["En Ñuqaqa, ¿qué pieza marca tópico?",["-qa","-ta","-pi","-wan"],0],evidential_mi:["En Punomantam kani, ¿qué pieza corresponde al patrón -mi/-m?",["-m","-qa","-pi","-ta"],0],
  case_pi:["Elegí «en la casa».",["wasi-pi","wasi-man","wasi-manta","wasi-wan"],0],case_man:["Elegí «hacia la casa».",["wasi-man","wasi-pi","wasi-manta","wasi-wan"],0],case_manta:["Elegí «desde la casa».",["wasi-manta","wasi-man","wasi-pi","wasi-wan"],0],case_wan:["Elegí «con mi madre».",["mama-y-wan","mama-y-man","mama-y-pi","mama-y-manta"],0],object_ta:["¿Cuál expresa «como papa» marcando el objeto?",["papa-ta mikhu-ni","papa-pi mikhu-ni","papa-man mikhu-ni","papa-wan mikhu-ni"],0],
  possessive:["¿Cuál es «mi casa / tu casa / su casa»?",["wasi-y / wasi-yki / wasi-n","wasi-ni / wasi-nki / wasi-n","wasi-pa / wasi-pi / wasi-man","wasi-kuna / wasi-ta / wasi-wan"],0],genitive_pa:["¿Cuál es «la casa de María»?",["Maria-pa wasi-n","Maria-man wasi","Maria-ta wasi-y","Maria-pi wasi-kuna"],0],kay_person:["Completá ñuqa / qam / pay.",["kani / kanki / kan","kanki / kani / kan","kan / kanki / kani","kani / kan / kanki"],0],present_person:["Completá mikhu- para yo / vos / él-ella.",["-ni / -nki / -n","-nki / -ni / -n","-n / -nki / -ni","-ni / -n / -nki"],0],negation_chu:["Elegí «no como pan».",["Manam t'antata mikhunichu.","Mana t'antata mikhuni.","T'antata manam mikhuni.","Mikhunichu t'antata."],0],
  demonstratives:["De cercano a lejano:",["kay → chay → haqay","haqay → kay → chay","chay → haqay → kay","kay → haqay → chay"],0],numerals:["¿Cómo se forma 12?",["chunka iskayniyuq","iskay chunka","chunka iskaykuna","iskayniyuq chunka"],0],sequence:["¿Cuál es «primero… después…»?",["ñawpaqta … chaymanta …","chaymanta … ñawpaqta …","maypi … hinaspa …","mana … -chu"],0],additive_pas:["En ñuqapas, -pas significa…",["también","negación","dirección","posesión"],0],suffix_stacking:["Segmentá mamaywan.",["mama + -y + -wan","mama + -ta + -man","mama + -pa + -pi","mama + -kuna"],0],adjective_order:["¿Cuál es «casa grande»?",["hatun wasi","wasi hatun","wasita hatun","hatun wasipi"],0]
 };
 function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
 function qFromItem(i){if(i.kind!=="vocab")return {q:i.q.q,opts:i.q.opts,a:i.q.a,item:i};let pool=bank().filter(x=>x.kind==="vocab"&&x.id!==i.id&&eligible(x)),wrong=shuffle(pool).map(x=>x.back).filter((v,j,a)=>v!==i.back&&a.indexOf(v)===j).slice(0,3),opts=shuffle([i.back,...wrong]);return {q:`¿Qué significa «${i.front}»?`,opts,a:opts.indexOf(i.back),item:i}}
 function makeQs(cid,size=8){let its=shuffle(items(cid)),out=[];for(let i of its){if(out.length>=Math.max(3,size-2))break;out.push(qFromItem(i))}while(out.length<size&&D[cid]){let d=D[cid];out.push({q:d[0],opts:d[1],a:d[2],generated:true})}return shuffle(out).slice(0,size)}
 function runQuestions(qs,title,cid=null,onDone=null){if(!qs.length){alert("Todavía no hay suficiente material introducido.");return}let k=0,score=0,ans=false;modal.classList.remove("hidden");function paint(){let x=qs[k],focus=x.cid||cid;modal.innerHTML=`<div class="shell"><div class="modal-top"><button class="close-btn" id="closeM">×</button><div class="progress"><i style="width:${k/qs.length*100}%"></i></div><b>${k+1}/${qs.length}</b></div><section class="question-card"><div class="kicker" style="color:var(--brand)">${esc(title)} · ${focus?esc(C[focus][0]):""}</div><h3>${esc(x.q)}</h3><div class="opts">${x.opts.map((o,j)=>`<button class="opt" data-o="${j}">${esc(o)}</button>`).join("")}</div><div id="cfb"></div><button id="cnext" class="primary full" disabled>Comprobar</button></section></div>`;document.querySelector("#closeM").onclick=closeModal;let sel=null;ans=false,cnext=document.querySelector("#cnext"),fb=document.querySelector("#cfb");document.querySelectorAll("[data-o]").forEach(b=>b.onclick=()=>{if(ans)return;sel=+b.dataset.o;document.querySelectorAll(".opt").forEach(z=>z.classList.remove("selected"));b.classList.add("selected");cnext.disabled=false});cnext.onclick=()=>{if(!ans){ans=true;let ok=sel===x.a;if(ok)score++;if(x.item)RaicesAdaptive.record(x.item.id,ok,"concepto-"+focus,[]);else recordGenerated(focus,ok,"drill-conceptual");fb.className=`feedback ${ok?"ok":"bad"}`;fb.textContent=ok?"✓ Correcto":"✕ "+x.opts[x.a];cnext.textContent=k===qs.length-1?"Ver resultado":"Continuar";return}if(++k<qs.length)paint();else finish()}}function finish(){if(onDone){onDone(score,qs.length);return}let e=est(cid);modal.innerHTML=`<div class="shell"><div class="trophy">🧬</div><h2>${score}/${qs.length}</h2><p><b>${esc(C[cid][0])}:</b> dominio estimado ${e.m??"—"}% · confianza ${e.conf}%.</p><div class="concept-meter"><i style="width:${e.m||0}%"></i></div><p class="note">Es una estimación dinámica, no una nota; cambia con nueva evidencia y con el paso del tiempo.</p><button id="cb" class="primary full">Volver</button></div>`;document.querySelector("#cb").onclick=()=>{closeModal();render("practice")}}paint()}
 function runConcept(cid){runQuestions(makeQs(cid),"Práctica dirigida",cid)}
 function diagnostic(){let cs=Object.keys(C).map(est).filter(x=>introduced(x.cid)).sort((a,b)=>a.conf-b.conf||priority(b)-priority(a)).slice(0,6);if(!cs.length){alert("Completá una microlección primero.");return}let qs=[];for(let x of cs){let part=makeQs(x.cid,2);part.slice(0,2).forEach(q=>qs.push({...q,cid:x.cid}))}runQuestions(qs,"Diagnóstico",null,(score,total)=>{let rows=cs.map(x=>est(x.cid));modal.innerHTML=`<div class="shell"><div class="trophy">🧬</div><h2>Diagnóstico ${score}/${total}</h2><p class="note">Muestreo de reglas con poca evidencia. El motor usa este resultado para decidir qué practicar.</p>${rows.map(x=>`<div class="mini-concept"><b>${esc(C[x.cid][0])}</b><span>${x.m??"—"}% · conf. ${x.conf}%</span></div>`).join("")}<button id="db" class="primary full">Ver mapa</button></div>`;document.querySelector("#db").onclick=()=>{closeModal();render("practice")}})}
 function reason(x){let a=[];if(x.conf<45)a.push("poca evidencia");if(x.wrong)a.push(`${x.wrong} errores`);if(x.m<50)a.push("dominio bajo");let b=blockers(x.cid);if(b.length)a.push("prerrequisito débil: "+b.map(z=>C[z][0]).join(", "));return a.join(" · ")||"conviene consolidarlo"}
 function dashboard(){let xs=Object.keys(C).map(est).filter(x=>introduced(x.cid)),r=recommendation(),groups={};xs.forEach(x=>(groups[C[x.cid][1]]??=[]).push(x));return `<section class="concept-hero"><div><div class="kicker" style="color:var(--brand)">Fase 2 refinada</div><h2>🧬 Mapa de conceptos</h2><p>Los errores se agrupan por la regla que comparten. El sistema puede detectar que el problema es <b>-ta</b>, no simplemente «fallaste papa».</p></div>${r?`<div class="recommend-box"><small>FOCO RECOMENDADO</small><b>${esc(C[r.cid][0])}</b><span>${esc(reason(r))}</span><button class="primary full" data-cfocus="${r.cid}">Practicar foco</button></div>`:""}</section><div class="concept-summary"><div><b>${xs.filter(x=>x.m>=80).length}</b><small>fuertes</small></div><div><b>${xs.filter(x=>x.m!=null&&x.m<55).length}</b><small>frágiles</small></div><div><b>${xs.filter(x=>x.conf<45).length}</b><small>poca evidencia</small></div></div><section class="card"><div class="concept-title-row"><h3>Competencias</h3><button id="cdiag" class="secondary">Diagnóstico</button></div>${Object.entries(groups).map(([g,ys])=>`<div class="concept-group"><h4>${esc(g)}</h4>${ys.sort((a,b)=>(a.m??0)-(b.m??0)).map(x=>`<button class="concept-row" data-cfocus="${x.cid}"><div><b>${esc(C[x.cid][0])}</b><small>${x.status}${blockers(x.cid).length?" · depende de "+blockers(x.cid).map(z=>C[z][0]).join(", "):""}</small></div><div class="concept-score"><span>${x.m??"—"}%</span><div><i style="width:${x.m||0}%"></i></div><small>conf. ${x.conf}%</small></div></button>`).join("")}</div>`).join("")}</section>`}
 function wire(){document.querySelectorAll("[data-cfocus]").forEach(b=>b.onclick=()=>runConcept(b.dataset.cfocus));let d=document.querySelector("#cdiag");if(d)d.onclick=diagnostic}
 const basePractice=renderPractice;renderPractice=function(){basePractice();if(state.lang!=="qu")return;let h=document.createElement("div");h.innerHTML=dashboard();let hero=screen.querySelector(".hero");hero?hero.insertAdjacentElement("afterend",h):screen.prepend(h);wire()};
 const baseProfile=renderProfile;renderProfile=function(){baseProfile();if(state.lang!=="qu")return;let xs=Object.keys(C).map(est).filter(x=>introduced(x.cid)&&x.m!=null),avg=xs.length?Math.round(xs.reduce((a,x)=>a+x.m,0)/xs.length):0,w=[...xs].sort((a,b)=>a.m-b.m).slice(0,5),s=document.createElement("section");s.className="card";s.innerHTML=`<h3>🧬 Dominio lingüístico</h3><div class="skill-grid"><div class="skill"><b>${avg}%</b><small>dominio conceptual medio</small></div><div class="skill"><b>${xs.length}</b><small>conceptos medidos</small></div><div class="skill"><b>${xs.filter(x=>x.m>=80).length}</b><small>fuertes</small></div><div class="skill"><b>${xs.filter(x=>x.conf<45).length}</b><small>poca evidencia</small></div></div>${w.map(x=>`<div class="mini-concept"><b>${esc(C[x.cid][0])}</b><span>${x.m}%</span></div>`).join("")}<button id="cp" class="secondary full">Abrir mapa</button>`;screen.appendChild(s);document.querySelector("#cp").onclick=()=>render("practice")};
 window.RaicesConcepts={catalog:C,estimate:est,tags,recommendation,runConcept,diagnostic};
})();